package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"unicode"
)

type plugin struct {
	Name       string
	Package    string
	Type       string
	ImportPath string
}

func main() {
	root := flag.String("root", ".", "project root")
	addonsDir := flag.String("addons-dir", os.Getenv("NOVA_ADDONS_DIR"), "external addons directory")
	enabled := flag.String("enabled", os.Getenv("NOVA_ADDONS"), "comma or space separated addon names; empty means all")
	link := flag.Bool("link", false, "link enabled external addons into app/business")
	flag.Parse()

	projectRoot, err := filepath.Abs(*root)
	check(err)

	businessDir := filepath.Join(projectRoot, "app", "business")
	if *link && *addonsDir != "" {
		check(linkAddons(businessDir, *addonsDir, splitNames(*enabled)))
	}

	plugins, err := discoverPlugins(businessDir)
	check(err)
	check(writeProvider(projectRoot, plugins))
}

func linkAddons(businessDir, addonsDir string, enabled map[string]bool) error {
	absAddonsDir, err := filepath.Abs(addonsDir)
	if err != nil {
		return err
	}

	names, err := discoverAddonNames(absAddonsDir, enabled)
	if err != nil {
		return err
	}

	for _, name := range names {
		src := filepath.Join(absAddonsDir, name)
		dst := filepath.Join(businessDir, name)

		info, err := os.Lstat(dst)
		if err == nil {
			if info.Mode()&os.ModeSymlink == 0 {
				continue
			}
			target, err := os.Readlink(dst)
			if err != nil {
				return err
			}
			if !filepath.IsAbs(target) {
				target = filepath.Join(filepath.Dir(dst), target)
			}
			if filepath.Clean(target) == filepath.Clean(src) {
				continue
			}
			return fmt.Errorf("%s already links to %s", dst, target)
		}
		if !os.IsNotExist(err) {
			return err
		}
		if err := os.Symlink(src, dst); err != nil {
			return err
		}
	}

	return nil
}

func discoverAddonNames(addonsDir string, enabled map[string]bool) ([]string, error) {
	entries, err := os.ReadDir(addonsDir)
	if err != nil {
		return nil, err
	}

	var names []string
	for _, entry := range entries {
		if strings.HasPrefix(entry.Name(), ".") {
			continue
		}
		entryPath := filepath.Join(addonsDir, entry.Name())
		info, err := os.Stat(entryPath)
		if err != nil || !info.IsDir() {
			continue
		}
		if len(enabled) > 0 && !enabled[entry.Name()] {
			continue
		}
		if !hasFile(entryPath, "register.go") &&
			!hasFile(entryPath, "register_nonsupport.go") {
			continue
		}
		names = append(names, entry.Name())
	}

	sort.Strings(names)
	return names, nil
}

func discoverPlugins(businessDir string) ([]plugin, error) {
	entries, err := os.ReadDir(businessDir)
	if err != nil {
		return nil, err
	}

	var plugins []plugin
	for _, entry := range entries {
		if strings.HasPrefix(entry.Name(), ".") {
			continue
		}

		dir := filepath.Join(businessDir, entry.Name())
		info, err := os.Stat(dir)
		if err != nil || !info.IsDir() {
			continue
		}
		if !hasFile(dir, "register.go") && !hasFile(dir, "register_nonsupport.go") {
			continue
		}

		pkg, typ, err := pluginPackageAndType(dir)
		if err != nil {
			return nil, err
		}
		plugins = append(plugins, plugin{
			Name:       entry.Name(),
			Package:    pkg,
			Type:       typ,
			ImportPath: "nova-factory-server/app/business/" + entry.Name(),
		})
	}

	sort.Slice(plugins, func(i, j int) bool {
		return plugins[i].Name < plugins[j].Name
	})
	return plugins, nil
}

func pluginPackageAndType(dir string) (string, string, error) {
	files, err := filepath.Glob(filepath.Join(dir, "*.go"))
	if err != nil {
		return "", "", err
	}
	sort.Strings(files)

	var packageName string
	for _, file := range files {
		fset := token.NewFileSet()
		parsed, err := parser.ParseFile(fset, file, nil, parser.SkipObjectResolution)
		if err != nil {
			return "", "", err
		}
		if packageName == "" {
			packageName = parsed.Name.Name
		}

		for _, decl := range parsed.Decls {
			fn, ok := decl.(*ast.FuncDecl)
			if !ok || fn.Name.Name != "NewGinEngine" || fn.Type.Results == nil {
				continue
			}
			for _, result := range fn.Type.Results.List {
				if star, ok := result.Type.(*ast.StarExpr); ok {
					if ident, ok := star.X.(*ast.Ident); ok {
						return packageName, ident.Name, nil
					}
				}
			}
		}
	}

	return "", "", fmt.Errorf("missing NewGinEngine return type in %s", dir)
}

func writeProvider(projectRoot string, plugins []plugin) error {
	var b bytes.Buffer

	b.WriteString("// Code generated by tools/addonsync. DO NOT EDIT.\n\n")
	b.WriteString("package business\n\n")
	b.WriteString("import (\n")
	b.WriteString("\t\"github.com/google/wire\"\n")
	for _, plugin := range plugins {
		fmt.Fprintf(&b, "\t%s \"%s\"\n", importAlias(plugin.Name), plugin.ImportPath)
	}
	b.WriteString(")\n\n")

	b.WriteString("type Plugins struct {\n")
	for _, plugin := range plugins {
		fmt.Fprintf(&b, "\t%s *%s.%s\n", fieldName(plugin.Type), importAlias(plugin.Name), plugin.Type)
	}
	b.WriteString("}\n\n")

	b.WriteString("func NewPlugins(\n")
	for _, plugin := range plugins {
		fmt.Fprintf(&b, "\t%s *%s.%s,\n", paramName(plugin.Name), importAlias(plugin.Name), plugin.Type)
	}
	b.WriteString(") *Plugins {\n")
	b.WriteString("\treturn &Plugins{\n")
	for _, plugin := range plugins {
		fmt.Fprintf(&b, "\t\t%s: %s,\n", fieldName(plugin.Type), paramName(plugin.Name))
	}
	b.WriteString("\t}\n")
	b.WriteString("}\n\n")

	b.WriteString("var ProviderSet = wire.NewSet(\n")
	for _, plugin := range plugins {
		fmt.Fprintf(&b, "\t%s.ProviderSet,\n", importAlias(plugin.Name))
	}
	b.WriteString("\tNewPlugins,\n")
	b.WriteString(")\n")

	formatted, err := format.Source(b.Bytes())
	if err != nil {
		return err
	}

	return os.WriteFile(filepath.Join(projectRoot, "app", "business", "provider_gen.go"), formatted, 0644)
}

func splitNames(value string) map[string]bool {
	value = strings.TrimSpace(value)
	if value == "" || value == "all" {
		return nil
	}

	names := map[string]bool{}
	for _, name := range strings.FieldsFunc(value, func(r rune) bool {
		return r == ',' || unicode.IsSpace(r)
	}) {
		if name != "" {
			names[name] = true
		}
	}
	return names
}

func hasFile(dir, name string) bool {
	info, err := os.Stat(filepath.Join(dir, name))
	return err == nil && !info.IsDir()
}

func importAlias(name string) string {
	return strings.Map(func(r rune) rune {
		if unicode.IsLetter(r) || unicode.IsDigit(r) || r == '_' {
			return r
		}
		return '_'
	}, name)
}

func fieldName(name string) string {
	if name == "" {
		return name
	}
	return strings.ToUpper(name[:1]) + name[1:]
}

func paramName(name string) string {
	return importAlias(name) + "Plugin"
}

func check(err error) {
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
