// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"google.golang.org/grpc"
	"nova-factory-server/app/business/metric/device/metricController"
	"nova-factory-server/app/routes"
)

// Injectors from wire.go:

func wireApp() (*grpc.Server, func(), error) {
	metric := metricController.NewMetric()
	metricServer := &metricController.MetricServer{
		Metric: metric,
	}
	server := routes.NewGrpcEngine(metricServer)
	return server, func() {
	}, nil
}
