// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"google.golang.org/grpc"
	"nova-factory-server/app/business/iot/asset/camera/cameradao/cameraDaoImpl"
	"nova-factory-server/app/business/iot/metric/device/metriccontroller"
	"nova-factory-server/app/business/iot/metric/device/metricdao/metricdaoimpl"
	"nova-factory-server/app/business/iot/metric/device/metricservice/metricserviceimpl"
	"nova-factory-server/app/datasource/cache"
	"nova-factory-server/app/datasource/mysql"
	"nova-factory-server/app/routes"
)

// Injectors from wire.go:

func wireApp() (*grpc.Server, func(), error) {
	iMetricDao := metricdaoimpl.NewMetricDaoImpl()
	cacheCache := cache.NewCache()
	iMetricService := metricserviceimpl.NewIMetricServiceImpl(iMetricDao, cacheCache)
	iControlLogDao := metricdaoimpl.NewIControlLogDaoImpl()
	iControlLogService := metricserviceimpl.NewIControlLogServiceImpl(iControlLogDao)
	metric := metriccontroller.NewMetric(iMetricService, iControlLogService)
	db := mysql.NewDB()
	iCameraDao := cameraDaoImpl.NewCameraDao(db)
	iCameraService := metricserviceimpl.NewICameraServiceImpl(cacheCache, iCameraDao)
	cameraGrpc := metriccontroller.NewCamera(iCameraService)
	metricServer := &metriccontroller.MetricServer{
		Metric:     metric,
		CameraGrpc: cameraGrpc,
	}
	server := routes.NewGrpcEngine(metricServer)
	return server, func() {
	}, nil
}
