CREATE TABLE IF NOT EXISTS `erp_sales_order_agent_config` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `name` VARCHAR(128) NOT NULL COMMENT '配置名称',
    `agent_id` VARCHAR(128) NOT NULL COMMENT '智能体AgentID',
    `status` TINYINT NOT NULL DEFAULT 1 COMMENT '状态：1启用，0禁用',
    `remark` VARCHAR(500) DEFAULT NULL COMMENT '备注',
    `dept_id` bigint(20) NULL DEFAULT NULL COMMENT '部门ID',
    `create_by` bigint(20) NULL DEFAULT NULL COMMENT '创建者',
    `create_time` datetime(0) NULL DEFAULT NULL COMMENT '创建时间',
    `update_by` bigint(20) NULL DEFAULT NULL COMMENT '更新者',
    `update_time` datetime(0) NULL DEFAULT NULL COMMENT '更新时间',
    `state` tinyint(1) NULL DEFAULT 0 COMMENT '操作状态（0正常 -1删除）',
    PRIMARY KEY (`id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='销售订单智能体配置表';

CREATE TABLE IF NOT EXISTS `erp_integration_config` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `type` VARCHAR(128) NOT NULL COMMENT '接入类型',
    `data` TEXT  COMMENT '配置快照',
    `status` TINYINT NOT NULL DEFAULT 1 COMMENT '状态：1启用，0禁用',
    `dept_id` bigint(20) NULL DEFAULT NULL COMMENT '部门ID',
    `create_by` bigint(20) NULL DEFAULT NULL COMMENT '创建者',
    `create_time` datetime(0) NULL DEFAULT NULL COMMENT '创建时间',
    `update_by` bigint(20) NULL DEFAULT NULL COMMENT '更新者',
    `update_time` datetime(0) NULL DEFAULT NULL COMMENT '更新时间',
    `state` tinyint(1) NULL DEFAULT 0 COMMENT '操作状态（0正常 -1删除）',
    PRIMARY KEY (`id`),
    UNIQUE INDEX `type`(`type`) USING BTREE
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='erp集成系统';

CREATE TABLE IF NOT EXISTS `erp_order_audit` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `tid` VARCHAR(50) NOT NULL COMMENT '网店订单编号',
    `weight` DECIMAL(18,4) DEFAULT NULL COMMENT '订单重量',
    `size` DECIMAL(18,4) DEFAULT NULL COMMENT '订单尺寸/体积',

    `buyer_nick` VARCHAR(50) DEFAULT NULL COMMENT '买家账号',
    `buyer_message` VARCHAR(50) DEFAULT NULL COMMENT '买家留言',
    `seller_memo` VARCHAR(50) DEFAULT NULL COMMENT '卖家备注',

    `total` DECIMAL(20,8) DEFAULT NULL COMMENT '订单总金额（含运费）',
    `privilege` DECIMAL(20,8) NOT NULL DEFAULT 0.00000000 COMMENT '订单优惠金额',
    `post_fee` DECIMAL(20,8) NOT NULL DEFAULT 0.00000000 COMMENT '运费',

    `receiver_name` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '收货人名称',
    `receiver_province` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '收货省编码',
    `receiver_province_name` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '收货省名称',
    `receiver_city` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '收货市编码',
    `receiver_city_name` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '收货市名称',
    `receiver_district` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '收货区编码',
    `receiver_district_name` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '收货区名称',
    `receiver_street` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '收货街道编码',
    `receiver_street_name` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '收货街道名称',
    `receiver_address` VARCHAR(255) NOT NULL COMMENT '收货详细地址',
    `receiver_phone` VARCHAR(50) DEFAULT NULL COMMENT '收货电话',
    `receiver_mobile` VARCHAR(50) NOT NULL COMMENT '收货人手机号',
    `receiver_zip` VARCHAR(20) DEFAULT NULL COMMENT '邮编',

    `status` VARCHAR(200) NOT NULL COMMENT '来源订单状态',
    `order_type` VARCHAR(50) NOT NULL COMMENT '订单类型（Cod/NoCod）',
    `invoice_name` VARCHAR(50) DEFAULT NULL COMMENT '发票抬头',
    `seller_flag` VARCHAR(50) DEFAULT NULL COMMENT '卖家旗帜',
    `pay_time` DATETIME(0) DEFAULT NULL COMMENT '付款时间',

    `logist_b_type_code` VARCHAR(100) DEFAULT NULL COMMENT '物流公司编码',
    `logist_bill_code` VARCHAR(100) DEFAULT NULL COMMENT '物流单号',
    `b_type_code` VARCHAR(50) DEFAULT NULL COMMENT '往来单位编码',

    `details_json` LONGTEXT COMMENT '订单商品明细JSON',
    `accounts_json` LONGTEXT COMMENT '订单账户信息JSON',
    `source_json` LONGTEXT COMMENT '原始订单报文JSON',

    `audit_status` TINYINT NOT NULL DEFAULT 0 COMMENT '审核状态：0待审核 1审核通过 2审核驳回',
    `audit_remark` VARCHAR(500) DEFAULT NULL COMMENT '审核意见',
    `audit_by` BIGINT(20) NULL DEFAULT NULL COMMENT '审核人',
    `audit_time` DATETIME(0) DEFAULT NULL COMMENT '审核时间',

    `transfer_status` TINYINT NOT NULL DEFAULT 0 COMMENT '入正式订单状态：0未入库 1已入库 2入库失败',
    `transfer_message` VARCHAR(500) DEFAULT NULL COMMENT '入正式订单结果描述',
    `transfer_time` DATETIME(0) DEFAULT NULL COMMENT '入正式订单时间',
    `erp_order_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '审核通过后生成的正式订单ID',

    `dept_id` BIGINT(20) NULL DEFAULT NULL COMMENT '部门ID',
    `create_by` BIGINT(20) NULL DEFAULT NULL COMMENT '创建者',
    `create_time` DATETIME(0) NULL DEFAULT NULL COMMENT '创建时间',
    `update_by` BIGINT(20) NULL DEFAULT NULL COMMENT '更新者',
    `update_time` DATETIME(0) NULL DEFAULT NULL COMMENT '更新时间',
    `state` TINYINT(1) NULL DEFAULT 0 COMMENT '操作状态（0正常 -1删除）',

    PRIMARY KEY (`id`),
    UNIQUE INDEX `uk_erp_order_audit_tid` (`tid`) USING BTREE,
    INDEX `idx_erp_order_audit_status` (`audit_status`) USING BTREE,
    INDEX `idx_erp_order_audit_transfer_status` (`transfer_status`) USING BTREE,
    INDEX `idx_erp_order_audit_erp_order_id` (`erp_order_id`) USING BTREE
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ERP订单审核表';

CREATE TABLE IF NOT EXISTS `erp_order` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `tid` VARCHAR(50) NOT NULL COMMENT '网店订单编号',
    `weight` DECIMAL(18,4) DEFAULT NULL COMMENT '订单重量',
    `size` DECIMAL(18,4) DEFAULT NULL COMMENT '订单尺寸/体积',

    `buyer_nick` VARCHAR(50) DEFAULT NULL COMMENT '买家账号',
    `buyer_message` VARCHAR(50) DEFAULT NULL COMMENT '买家留言',
    `seller_memo` VARCHAR(50) DEFAULT NULL COMMENT '卖家备注',

    `total` DECIMAL(20,8) DEFAULT NULL COMMENT '订单总金额（含运费）',
    `privilege` DECIMAL(20,8) NOT NULL DEFAULT 0.00000000 COMMENT '订单优惠金额',
    `post_fee` DECIMAL(20,8) NOT NULL DEFAULT 0.00000000 COMMENT '运费',

    `receiver_name` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '收货人名称',

    `receiver_province` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '收货省编码',
    `receiver_province_name` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '收货省名称',

    `receiver_city` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '收货市编码',
    `receiver_city_name` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '收货市名称',

    `receiver_district` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '收货区编码',
    `receiver_district_name` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '收货区名称',

    `receiver_street` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '收货街道编码',
    `receiver_street_name` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '收货街道名称',

    `receiver_address` VARCHAR(255) NOT NULL COMMENT '收货详细地址',
    `receiver_phone` VARCHAR(50) DEFAULT NULL COMMENT '收货电话',
    `receiver_mobile` VARCHAR(50) NOT NULL COMMENT '收货人手机号',
    `receiver_zip` VARCHAR(20) DEFAULT NULL COMMENT '邮编',

    `status` VARCHAR(200) NOT NULL COMMENT '订单状态',
    `order_type` VARCHAR(50) NOT NULL COMMENT '订单类型（Cod/NoCod）',
    `invoice_name` VARCHAR(50) DEFAULT NULL COMMENT '发票抬头',
    `seller_flag` VARCHAR(50) DEFAULT NULL COMMENT '卖家旗帜',
    `pay_time` DATETIME(0) DEFAULT NULL COMMENT '付款时间',

    `logist_b_type_code` VARCHAR(100) DEFAULT NULL COMMENT '物流公司编码',
    `logist_bill_code` VARCHAR(100) DEFAULT NULL COMMENT '物流单号',
    `b_type_code` VARCHAR(50) DEFAULT NULL COMMENT '往来单位编码',

    `details_json` LONGTEXT COMMENT '订单商品明细JSON',
    `accounts_json` LONGTEXT COMMENT '订单账户信息JSON',

    `bill_code` VARCHAR(100) DEFAULT NULL COMMENT '管家婆返回订单编号',
    `sync_message` VARCHAR(500) DEFAULT NULL COMMENT '同步结果描述',
    `sync_status` TINYINT NOT NULL DEFAULT 0 COMMENT '同步状态：0待同步 1成功 2失败',
    `sync_time` DATETIME(0) DEFAULT NULL COMMENT '同步时间',

    `dept_id` BIGINT(20) NULL DEFAULT NULL COMMENT '部门ID',
    `create_by` BIGINT(20) NULL DEFAULT NULL COMMENT '创建者',
    `create_time` DATETIME(0) NULL DEFAULT NULL COMMENT '创建时间',
    `update_by` BIGINT(20) NULL DEFAULT NULL COMMENT '更新者',
    `update_time` DATETIME(0) NULL DEFAULT NULL COMMENT '更新时间',
    `state` TINYINT(1) NULL DEFAULT 0 COMMENT '操作状态（0正常 -1删除）',

    PRIMARY KEY (`id`),
    UNIQUE INDEX `uk_erp_order_tid` (`tid`) USING BTREE,
    INDEX `idx_erp_order_status` (`status`) USING BTREE,
    INDEX `idx_erp_order_sync_status` (`sync_status`) USING BTREE
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ERP订单主表';


CREATE TABLE IF NOT EXISTS `erp_order_detail` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `order_id` BIGINT UNSIGNED NOT NULL COMMENT '订单主表ID',
    `tid` VARCHAR(50) NOT NULL COMMENT '网店订单编号',
    `oid` VARCHAR(50) NOT NULL COMMENT '网店订单明细编号',

    `barcode` VARCHAR(50) DEFAULT NULL COMMENT '商品条码',
    `eshop_goods_id` VARCHAR(100) DEFAULT NULL COMMENT '网店商品ID',
    `outer_iid` VARCHAR(100) DEFAULT NULL COMMENT '网店商家编码',
    `eshop_goods_name` VARCHAR(100) NOT NULL COMMENT '网店商品名称',
    `eshop_sku_id` VARCHAR(100) DEFAULT NULL COMMENT '网店商品SKUID',
    `eshop_sku_name` VARCHAR(100) DEFAULT NULL COMMENT '网店商品SKU名称',

    `num_iid` BIGINT(20) DEFAULT NULL COMMENT '商品ID（方案B）',
    `sku_id` BIGINT(20) DEFAULT NULL COMMENT '规格ID（方案B）',

    `num` DECIMAL(18,4) NOT NULL COMMENT '基本单位数量',
    `payment` DECIMAL(20,8) NOT NULL COMMENT '商品总额',
    `pic_path` VARCHAR(255) DEFAULT NULL COMMENT '商品图片路径',
    `weight` DECIMAL(18,4) DEFAULT NULL COMMENT '重量',
    `size` DECIMAL(18,4) DEFAULT NULL COMMENT '尺寸/体积',

    `unit_id` BIGINT(20) DEFAULT NULL COMMENT '销售单位ID',
    `unit_qty` DECIMAL(18,4) DEFAULT NULL COMMENT '销售单位数量',

    `dept_id` BIGINT(20) NULL DEFAULT NULL COMMENT '部门ID',
    `create_by` BIGINT(20) NULL DEFAULT NULL COMMENT '创建者',
    `create_time` DATETIME(0) NULL DEFAULT NULL COMMENT '创建时间',
    `update_by` BIGINT(20) NULL DEFAULT NULL COMMENT '更新者',
    `update_time` DATETIME(0) NULL DEFAULT NULL COMMENT '更新时间',
    `state` TINYINT(1) NULL DEFAULT 0 COMMENT '操作状态（0正常 -1删除）',

    PRIMARY KEY (`id`),
    UNIQUE INDEX `uk_erp_order_detail_oid` (`oid`) USING BTREE,
    INDEX `idx_erp_order_detail_order_id` (`order_id`) USING BTREE,
    INDEX `idx_erp_order_detail_tid` (`tid`) USING BTREE
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ERP订单明细表';


CREATE TABLE IF NOT EXISTS `erp_order_account` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `order_id` BIGINT UNSIGNED NOT NULL COMMENT '订单主表ID',
    `tid` VARCHAR(50) NOT NULL COMMENT '网店订单编号',
    `finance_code` VARCHAR(50) NOT NULL COMMENT '账户编码',
    `total` DECIMAL(20,8) NOT NULL COMMENT '收款金额',

    `dept_id` BIGINT(20) NULL DEFAULT NULL COMMENT '部门ID',
    `create_by` BIGINT(20) NULL DEFAULT NULL COMMENT '创建者',
    `create_time` DATETIME(0) NULL DEFAULT NULL COMMENT '创建时间',
    `update_by` BIGINT(20) NULL DEFAULT NULL COMMENT '更新者',
    `update_time` DATETIME(0) NULL DEFAULT NULL COMMENT '更新时间',
    `state` TINYINT(1) NULL DEFAULT 0 COMMENT '操作状态（0正常 -1删除）',

    PRIMARY KEY (`id`),
    INDEX `idx_erp_order_account_order_id` (`order_id`) USING BTREE,
    INDEX `idx_erp_order_account_tid` (`tid`) USING BTREE,
    INDEX `idx_erp_order_account_finance_code` (`finance_code`) USING BTREE
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ERP订单账户表';


CREATE TABLE IF NOT EXISTS `erp_logistics_company` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `code` VARCHAR(64) NOT NULL COMMENT '物流公司编码',
    `company` VARCHAR(128) NOT NULL COMMENT '关联公司',
    `name` VARCHAR(128) NOT NULL COMMENT '物流公司名称',
    `short_name` VARCHAR(64) DEFAULT NULL COMMENT '物流公司简称',
    `contact_name` VARCHAR(64) DEFAULT NULL COMMENT '联系人',
    `contact_phone` VARCHAR(32) DEFAULT NULL COMMENT '联系电话',
    `address` VARCHAR(255) DEFAULT NULL COMMENT '联系地址',
    
    `province_code` VARCHAR(32) DEFAULT NULL COMMENT '省编码',
    `province_name` VARCHAR(64) NOT NULL COMMENT '省名称',
    `city_code` VARCHAR(32) DEFAULT NULL COMMENT '市编码',
    `city_name` VARCHAR(64) NOT NULL COMMENT '市名称',
    `district_code` VARCHAR(32) DEFAULT NULL COMMENT '区编码',
    `district_name` VARCHAR(64) NOT NULL COMMENT '区名称',
    `street_code` VARCHAR(32) DEFAULT NULL COMMENT '街道编码',
    `street_name` VARCHAR(64) DEFAULT NULL COMMENT '街道名称',

    `remark` VARCHAR(500) DEFAULT NULL COMMENT '备注',
    `sort` INT NOT NULL DEFAULT 0 COMMENT '排序值',
    `status` TINYINT NOT NULL DEFAULT 1 COMMENT '状态：1启用，0禁用',
    `dept_id` BIGINT(20) NULL DEFAULT NULL COMMENT '部门ID',
    `create_by` BIGINT(20) NULL DEFAULT NULL COMMENT '创建者',
    `create_time` DATETIME(0) NULL DEFAULT NULL COMMENT '创建时间',
    `update_by` BIGINT(20) NULL DEFAULT NULL COMMENT '更新者',
    `update_time` DATETIME(0) NULL DEFAULT NULL COMMENT '更新时间',
    `state` TINYINT(1) NULL DEFAULT 0 COMMENT '操作状态（0正常 -1删除）',
    PRIMARY KEY (`id`),
    UNIQUE INDEX `uk_erp_logistics_company_code` (`code`) USING BTREE,
    UNIQUE INDEX `uk_erp_logistics_company_name` (`name`) USING BTREE,
    INDEX `idx_erp_logistics_company_status` (`status`) USING BTREE,
    INDEX `idx_erp_logistics_company_sort` (`sort`) USING BTREE
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ERP物流公司管理表';


-- 根据 ERP 模块 DO 实体自动生成的 MySQL 建表语句
-- 来源目录: yudao-module-erp/.../dal/dataobject
-- 说明: 仓库中未找到现成 ERP CREATE TABLE，此文件按实体字段与 BaseDO 公共字段生成，字符串长度按通用规则推断。
-- 兼容说明: 本文件作为 erp.sql 的补充脚本使用，保留 erp.sql 中已有表定义，不执行 DROP TABLE。
-- 执行建议: 先执行 erp.sql，再执行本文件；本文件中的表均使用 CREATE TABLE IF NOT EXISTS 保证可重复执行。
-- 结构联通: erp_order.logist_b_type_code <-> erp_logistics_company.code。
-- 结构联通: erp_order.b_type_code <-> erp_customer.code。
-- 结构联通: erp_order_account.finance_code <-> erp_account.no。
-- 结构联通: erp_order_detail.unit_id <-> erp_product_unit.id，erp_order_detail.barcode <-> erp_product.bar_code。
-- 结构联通: erp_sale_out.order_id / erp_sale_return.order_id <-> erp_order.id；明细 order_item_id <-> erp_order_detail.id。
SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS `erp_account` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '结算账户编号',
    `name` varchar(255) NULL COMMENT '账户名称',
    `no` varchar(64) NULL COMMENT '账户编码，对接 erp_order_account.finance_code',
    `remark` varchar(500) NULL COMMENT '备注',
    `status` int NULL COMMENT '开启状态',
    `sort` int NULL COMMENT '排序',
    `default_status` bit(1) NULL COMMENT '是否默认',
    `dept_id` bigint(20) NULL DEFAULT NULL COMMENT '部门ID',
    `create_by` bigint(20) NULL DEFAULT NULL COMMENT '创建者',
    `create_time` datetime(0) NULL DEFAULT NULL COMMENT '创建时间',
    `update_by` bigint(20) NULL DEFAULT NULL COMMENT '更新者',
    `update_time` datetime(0) NULL DEFAULT NULL COMMENT '更新时间',
    `state` tinyint(1) NULL DEFAULT 0 COMMENT '操作状态（0正常 -1删除）',
    KEY `idx_status` (`status`),
    KEY `idx_default_status` (`default_status`),
    UNIQUE KEY `uk_no` (`no`),
    PRIMARY KEY (`id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ERP 结算账户 DO';

CREATE TABLE IF NOT EXISTS `erp_finance_payment` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
    `no` varchar(64) NULL COMMENT '付款单号',
    `status` int NULL COMMENT '付款状态',
    `payment_time` datetime NULL COMMENT '付款时间',
    `finance_user_id` bigint NULL COMMENT '财务人员编号',
    `supplier_id` bigint NULL COMMENT '供应商编号',
    `account_id` bigint NULL COMMENT '付款账户编号',
    `total_price` decimal(24,6) NULL COMMENT '合计价格，单位：元',
    `discount_price` decimal(24,6) NULL COMMENT '优惠金额，单位：元',
    `payment_price` decimal(24,6) NULL COMMENT '实付金额，单位：分；paymentPrice = totalPrice - discountPrice',
    `remark` varchar(500) NULL COMMENT '备注',
    `dept_id` bigint(20) NULL DEFAULT NULL COMMENT '部门ID',
    `create_by` bigint(20) NULL DEFAULT NULL COMMENT '创建者',
    `create_time` datetime(0) NULL DEFAULT NULL COMMENT '创建时间',
    `update_by` bigint(20) NULL DEFAULT NULL COMMENT '更新者',
    `update_time` datetime(0) NULL DEFAULT NULL COMMENT '更新时间',
    `state` tinyint(1) NULL DEFAULT 0 COMMENT '操作状态（0正常 -1删除）',
    UNIQUE KEY `uk_no` (`no`),
    KEY `idx_supplier_id` (`supplier_id`),
    KEY `idx_account_id` (`account_id`),
    KEY `idx_finance_user_id` (`finance_user_id`),
    KEY `idx_payment_time` (`payment_time`),
    KEY `idx_status` (`status`),
    PRIMARY KEY (`id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ERP 付款单 DO';

CREATE TABLE IF NOT EXISTS `erp_finance_payment_item` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '入库项编号',
    `payment_id` bigint NULL COMMENT '付款单编号',
    `biz_type` int NULL COMMENT '业务类型',
    `biz_id` bigint NULL COMMENT '业务编号；例如说：',
    `biz_no` varchar(64) NULL COMMENT '业务单号；例如说：',
    `total_price` decimal(24,6) NULL COMMENT '应付金额，单位：分',
    `paid_price` decimal(24,6) NULL COMMENT '已付金额，单位：分',
    `payment_price` decimal(24,6) NULL COMMENT '本次付款，单位：分',
    `remark` varchar(500) NULL COMMENT '备注',
    `dept_id` bigint(20) NULL DEFAULT NULL COMMENT '部门ID',
    `create_by` bigint(20) NULL DEFAULT NULL COMMENT '创建者',
    `create_time` datetime(0) NULL DEFAULT NULL COMMENT '创建时间',
    `update_by` bigint(20) NULL DEFAULT NULL COMMENT '更新者',
    `update_time` datetime(0) NULL DEFAULT NULL COMMENT '更新时间',
    `state` tinyint(1) NULL DEFAULT 0 COMMENT '操作状态（0正常 -1删除）',
    KEY `idx_payment_id` (`payment_id`),
    KEY `idx_biz_type_biz_id` (`biz_type`, `biz_id`),
    KEY `idx_biz_no` (`biz_no`),
    PRIMARY KEY (`id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ERP 付款项 DO';

CREATE TABLE IF NOT EXISTS `erp_finance_receipt` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
    `no` varchar(64) NULL COMMENT '收款单号',
    `status` int NULL COMMENT '收款状态',
    `receipt_time` datetime NULL COMMENT '收款时间',
    `finance_user_id` bigint NULL COMMENT '财务人员编号',
    `customer_id` bigint NULL COMMENT '客户编号',
    `account_id` bigint NULL COMMENT '收款账户编号',
    `total_price` decimal(24,6) NULL COMMENT '合计价格，单位：元',
    `discount_price` decimal(24,6) NULL COMMENT '优惠金额，单位：元',
    `receipt_price` decimal(24,6) NULL COMMENT '实付金额，单位：分；receiptPrice = totalPrice - discountPrice',
    `remark` varchar(500) NULL COMMENT '备注',
    `dept_id` bigint(20) NULL DEFAULT NULL COMMENT '部门ID',
    `create_by` bigint(20) NULL DEFAULT NULL COMMENT '创建者',
    `create_time` datetime(0) NULL DEFAULT NULL COMMENT '创建时间',
    `update_by` bigint(20) NULL DEFAULT NULL COMMENT '更新者',
    `update_time` datetime(0) NULL DEFAULT NULL COMMENT '更新时间',
    `state` tinyint(1) NULL DEFAULT 0 COMMENT '操作状态（0正常 -1删除）',
    UNIQUE KEY `uk_no` (`no`),
    KEY `idx_customer_id` (`customer_id`),
    KEY `idx_account_id` (`account_id`),
    KEY `idx_finance_user_id` (`finance_user_id`),
    KEY `idx_receipt_time` (`receipt_time`),
    KEY `idx_status` (`status`),
    PRIMARY KEY (`id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ERP 收款单 DO';

CREATE TABLE IF NOT EXISTS `erp_finance_receipt_item` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '入库项编号',
    `receipt_id` bigint NULL COMMENT '收款单编号',
    `biz_type` int NULL COMMENT '业务类型',
    `biz_id` bigint NULL COMMENT '业务编号；例如说：',
    `biz_no` varchar(64) NULL COMMENT '业务单号；例如说：',
    `total_price` decimal(24,6) NULL COMMENT '应收金额，单位：分',
    `receipted_price` decimal(24,6) NULL COMMENT '已收金额，单位：分',
    `receipt_price` decimal(24,6) NULL COMMENT '本次收款，单位：分',
    `remark` varchar(500) NULL COMMENT '备注',
    `dept_id` bigint(20) NULL DEFAULT NULL COMMENT '部门ID',
    `create_by` bigint(20) NULL DEFAULT NULL COMMENT '创建者',
    `create_time` datetime(0) NULL DEFAULT NULL COMMENT '创建时间',
    `update_by` bigint(20) NULL DEFAULT NULL COMMENT '更新者',
    `update_time` datetime(0) NULL DEFAULT NULL COMMENT '更新时间',
    `state` tinyint(1) NULL DEFAULT 0 COMMENT '操作状态（0正常 -1删除）',
    KEY `idx_receipt_id` (`receipt_id`),
    KEY `idx_biz_type_biz_id` (`biz_type`, `biz_id`),
    KEY `idx_biz_no` (`biz_no`),
    PRIMARY KEY (`id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ERP 收款项 DO';

CREATE TABLE IF NOT EXISTS `erp_product_category` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '分类编号',
    `parent_id` bigint NULL COMMENT '父分类编号',
    `name` varchar(255) NULL COMMENT '分类名称',
    `code` varchar(64) NULL COMMENT '分类编码',
    `sort` int NULL COMMENT '分类排序',
    `status` int NULL COMMENT '开启状态',
    `dept_id` bigint(20) NULL DEFAULT NULL COMMENT '部门ID',
    `create_by` bigint(20) NULL DEFAULT NULL COMMENT '创建者',
    `create_time` datetime(0) NULL DEFAULT NULL COMMENT '创建时间',
    `update_by` bigint(20) NULL DEFAULT NULL COMMENT '更新者',
    `update_time` datetime(0) NULL DEFAULT NULL COMMENT '更新时间',
    `state` tinyint(1) NULL DEFAULT 0 COMMENT '操作状态（0正常 -1删除）',
    KEY `idx_parent_id` (`parent_id`),
    KEY `idx_parent_id_name` (`parent_id`, `name`),
    KEY `idx_status` (`status`),
    KEY `idx_code` (`code`),
    PRIMARY KEY (`id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ERP 产品分类 DO';

CREATE TABLE IF NOT EXISTS `erp_product` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '产品编号',
    `name` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '产品名称',
    `product_code` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '商品编码',
    `bar_code` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '产品条码，对接 erp_order_detail.barcode',
    `category_id` bigint DEFAULT '0' COMMENT '产品分类编号',
    `unit_id` bigint DEFAULT '0' COMMENT '单位编号，关联 erp_product_unit.id，可与 erp_order_detail.unit_id 对齐',
    `status` tinyint(1) DEFAULT '0' COMMENT '产品状态',
    `standard` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '产品规格',
    `remark` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '产品备注',
    `expiry_day` int DEFAULT NULL COMMENT '保质期天数',
    `weight` decimal(24,6) DEFAULT NULL COMMENT '基础重量（kg）',
    `purchase_price` decimal(24,6) DEFAULT NULL COMMENT '采购价格，单位：元',
    `sale_price` decimal(24,6) DEFAULT NULL COMMENT '销售价格，单位：元',
    `min_price` decimal(24,6) DEFAULT NULL COMMENT '最低价格，单位：元',
    `raw_data` text COLLATE utf8mb4_unicode_ci COMMENT '配置快照',
    `dept_id` bigint DEFAULT NULL COMMENT '部门ID',
    `create_by` bigint DEFAULT NULL COMMENT '创建者',
    `create_time` datetime DEFAULT NULL COMMENT '创建时间',
    `update_by` bigint DEFAULT NULL COMMENT '更新者',
    `update_time` datetime DEFAULT NULL COMMENT '更新时间',
    `state` tinyint(1) DEFAULT '0' COMMENT '操作状态（0正常 -1删除）',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uniq_product_code` (`product_code`),
    KEY `idx_category_id` (`category_id`),
    KEY `idx_unit_id` (`unit_id`),
    KEY `idx_status` (`status`),
    KEY `idx_create_time` (`create_time`),
    KEY `idx_bar_code` (`bar_code`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ERP 产品 DO';

CREATE TABLE IF NOT EXISTS `erp_product_unit` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '单位编号',
    `name` varchar(255) NULL COMMENT '单位名字',
    `status` int NULL COMMENT '单位状态',
    `dept_id` bigint(20) NULL DEFAULT NULL COMMENT '部门ID',
    `create_by` bigint(20) NULL DEFAULT NULL COMMENT '创建者',
    `create_time` datetime(0) NULL DEFAULT NULL COMMENT '创建时间',
    `update_by` bigint(20) NULL DEFAULT NULL COMMENT '更新者',
    `update_time` datetime(0) NULL DEFAULT NULL COMMENT '更新时间',
    `state` tinyint(1) NULL DEFAULT 0 COMMENT '操作状态（0正常 -1删除）',
    KEY `idx_status` (`status`),
    KEY `idx_name` (`name`),
    PRIMARY KEY (`id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ERP 产品单位 DO';

CREATE TABLE IF NOT EXISTS `erp_purchase_in` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
    `no` varchar(64) NULL COMMENT '采购入库单号',
    `status` int NULL COMMENT '入库状态',
    `supplier_id` bigint NULL COMMENT '供应商编号',
    `account_id` bigint NULL COMMENT '结算账户编号',
    `in_time` datetime NULL COMMENT '入库时间',
    `order_id` bigint NULL COMMENT '采购订单编号',
    `order_no` varchar(64) NULL COMMENT '采购订单号；冗余',
    `total_count` decimal(24,6) NULL COMMENT '合计数量',
    `total_price` decimal(24,6) NULL COMMENT '最终合计价格，单位：元；totalPrice = totalProductPrice + totalTaxPrice - discountPrice + otherPrice',
    `payment_price` decimal(24,6) NULL COMMENT '已支付金额，单位：元；目的：和  结合，记录已支付金额',
    `total_product_price` decimal(24,6) NULL COMMENT '合计产品价格，单位：元',
    `total_tax_price` decimal(24,6) NULL COMMENT '合计税额，单位：元',
    `discount_percent` decimal(24,6) NULL COMMENT '优惠率，百分比',
    `discount_price` decimal(24,6) NULL COMMENT '优惠金额，单位：元；discountPrice = (totalProductPrice + totalTaxPrice) * discountPercent',
    `other_price` decimal(24,6) NULL COMMENT '其它金额，单位：元',
    `file_url` varchar(255) NULL COMMENT '附件地址',
    `remark` varchar(500) NULL COMMENT '备注',
    `dept_id` bigint(20) NULL DEFAULT NULL COMMENT '部门ID',
    `create_by` bigint(20) NULL DEFAULT NULL COMMENT '创建者',
    `create_time` datetime(0) NULL DEFAULT NULL COMMENT '创建时间',
    `update_by` bigint(20) NULL DEFAULT NULL COMMENT '更新者',
    `update_time` datetime(0) NULL DEFAULT NULL COMMENT '更新时间',
    `state` tinyint(1) NULL DEFAULT 0 COMMENT '操作状态（0正常 -1删除）',
    UNIQUE KEY `uk_no` (`no`),
    KEY `idx_supplier_id` (`supplier_id`),
    KEY `idx_account_id` (`account_id`),
    KEY `idx_order_id` (`order_id`),
    KEY `idx_in_time` (`in_time`),
    KEY `idx_status` (`status`),
    PRIMARY KEY (`id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ERP 采购入库 DO';

CREATE TABLE IF NOT EXISTS `erp_purchase_in_items` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
    `in_id` bigint NULL COMMENT '采购入库编号',
    `order_item_id` bigint NULL COMMENT '采购订单项编号；目的：方便更新关联的采购订单项的入库数量',
    `warehouse_id` bigint NULL COMMENT '仓库编号',
    `product_id` bigint NULL COMMENT '产品编号',
    `product_unit_id` bigint NULL COMMENT '产品单位单位；冗余',
    `product_price` decimal(24,6) NULL COMMENT '产品单位单价，单位：元',
    `count` decimal(24,6) NULL COMMENT '数量',
    `total_price` decimal(24,6) NULL COMMENT '总价，单位：元；totalPrice = productPrice * count',
    `tax_percent` decimal(24,6) NULL COMMENT '税率，百分比',
    `tax_price` decimal(24,6) NULL COMMENT '税额，单位：元；taxPrice = totalPrice * taxPercent',
    `remark` varchar(500) NULL COMMENT '备注',
    `dept_id` bigint(20) NULL DEFAULT NULL COMMENT '部门ID',
    `create_by` bigint(20) NULL DEFAULT NULL COMMENT '创建者',
    `create_time` datetime(0) NULL DEFAULT NULL COMMENT '创建时间',
    `update_by` bigint(20) NULL DEFAULT NULL COMMENT '更新者',
    `update_time` datetime(0) NULL DEFAULT NULL COMMENT '更新时间',
    `state` tinyint(1) NULL DEFAULT 0 COMMENT '操作状态（0正常 -1删除）',
    KEY `idx_in_id` (`in_id`),
    KEY `idx_order_item_id` (`order_item_id`),
    KEY `idx_product_id` (`product_id`),
    KEY `idx_warehouse_id` (`warehouse_id`),
    PRIMARY KEY (`id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ERP 采购入库项 DO';

CREATE TABLE IF NOT EXISTS `erp_purchase_order` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
    `no` varchar(64) NULL COMMENT '采购订单号',
    `status` int NULL COMMENT '采购状态',
    `supplier_id` bigint NULL COMMENT '供应商编号',
    `account_id` bigint NULL COMMENT '结算账户编号',
    `order_time` datetime NULL COMMENT '下单时间',
    `total_count` decimal(24,6) NULL COMMENT '合计数量',
    `total_price` decimal(24,6) NULL COMMENT '最终合计价格，单位：元；totalPrice = totalProductPrice + totalTaxPrice - discountPrice',
    `total_product_price` decimal(24,6) NULL COMMENT '合计产品价格，单位：元',
    `total_tax_price` decimal(24,6) NULL COMMENT '合计税额，单位：元',
    `discount_percent` decimal(24,6) NULL COMMENT '优惠率，百分比',
    `discount_price` decimal(24,6) NULL COMMENT '优惠金额，单位：元；discountPrice = (totalProductPrice + totalTaxPrice) * discountPercent',
    `deposit_price` decimal(24,6) NULL COMMENT '定金金额，单位：元',
    `file_url` varchar(255) NULL COMMENT '附件地址',
    `remark` varchar(500) NULL COMMENT '备注',
    `in_count` decimal(24,6) NULL COMMENT '采购入库数量',
    `return_count` decimal(24,6) NULL COMMENT '采购退货数量',
    `dept_id` bigint(20) NULL DEFAULT NULL COMMENT '部门ID',
    `create_by` bigint(20) NULL DEFAULT NULL COMMENT '创建者',
    `create_time` datetime(0) NULL DEFAULT NULL COMMENT '创建时间',
    `update_by` bigint(20) NULL DEFAULT NULL COMMENT '更新者',
    `update_time` datetime(0) NULL DEFAULT NULL COMMENT '更新时间',
    `state` tinyint(1) NULL DEFAULT 0 COMMENT '操作状态（0正常 -1删除）',
    UNIQUE KEY `uk_no` (`no`),
    KEY `idx_supplier_id` (`supplier_id`),
    KEY `idx_account_id` (`account_id`),
    KEY `idx_order_time` (`order_time`),
    KEY `idx_status` (`status`),
    PRIMARY KEY (`id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ERP 采购订单 DO';

CREATE TABLE IF NOT EXISTS `erp_purchase_order_items` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
    `order_id` bigint NULL COMMENT '采购订单编号',
    `product_id` bigint NULL COMMENT '产品编号',
    `product_unit_id` bigint NULL COMMENT '产品单位单位；冗余',
    `product_price` decimal(24,6) NULL COMMENT '产品单位单价，单位：元',
    `count` decimal(24,6) NULL COMMENT '数量',
    `total_price` decimal(24,6) NULL COMMENT '总价，单位：元；totalPrice = productPrice * count',
    `tax_percent` decimal(24,6) NULL COMMENT '税率，百分比',
    `tax_price` decimal(24,6) NULL COMMENT '税额，单位：元；taxPrice = totalPrice * taxPercent',
    `remark` varchar(500) NULL COMMENT '备注',
    `in_count` decimal(24,6) NULL COMMENT '采购入库数量',
    `return_count` decimal(24,6) NULL COMMENT '采购退货数量',
    `dept_id` bigint(20) NULL DEFAULT NULL COMMENT '部门ID',
    `create_by` bigint(20) NULL DEFAULT NULL COMMENT '创建者',
    `create_time` datetime(0) NULL DEFAULT NULL COMMENT '创建时间',
    `update_by` bigint(20) NULL DEFAULT NULL COMMENT '更新者',
    `update_time` datetime(0) NULL DEFAULT NULL COMMENT '更新时间',
    `state` tinyint(1) NULL DEFAULT 0 COMMENT '操作状态（0正常 -1删除）',
    KEY `idx_order_id` (`order_id`),
    KEY `idx_product_id` (`product_id`),
    PRIMARY KEY (`id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ERP 采购订单项 DO';

CREATE TABLE IF NOT EXISTS `erp_purchase_return` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
    `no` varchar(64) NULL COMMENT '采购退货单号',
    `status` int NULL COMMENT '退货状态',
    `supplier_id` bigint NULL COMMENT '供应商编号',
    `account_id` bigint NULL COMMENT '结算账户编号',
    `return_time` datetime NULL COMMENT '退货时间',
    `order_id` bigint NULL COMMENT '采购订单编号',
    `order_no` varchar(64) NULL COMMENT '采购订单号；冗余',
    `total_count` decimal(24,6) NULL COMMENT '合计数量',
    `total_price` decimal(24,6) NULL COMMENT '最终合计价格，单位：元；totalPrice = totalProductPrice + totalTaxPrice - discountPrice + otherPrice',
    `refund_price` decimal(24,6) NULL COMMENT '已退款金额，单位：元；目的：和  结合，记录已支付金额',
    `total_product_price` decimal(24,6) NULL COMMENT '合计产品价格，单位：元',
    `total_tax_price` decimal(24,6) NULL COMMENT '合计税额，单位：元',
    `discount_percent` decimal(24,6) NULL COMMENT '优惠率，百分比',
    `discount_price` decimal(24,6) NULL COMMENT '优惠金额，单位：元；discountPrice = (totalProductPrice + totalTaxPrice) * discountPercent',
    `other_price` decimal(24,6) NULL COMMENT '其它金额，单位：元',
    `file_url` varchar(255) NULL COMMENT '附件地址',
    `remark` varchar(500) NULL COMMENT '备注',
    `dept_id` bigint(20) NULL DEFAULT NULL COMMENT '部门ID',
    `create_by` bigint(20) NULL DEFAULT NULL COMMENT '创建者',
    `create_time` datetime(0) NULL DEFAULT NULL COMMENT '创建时间',
    `update_by` bigint(20) NULL DEFAULT NULL COMMENT '更新者',
    `update_time` datetime(0) NULL DEFAULT NULL COMMENT '更新时间',
    `state` tinyint(1) NULL DEFAULT 0 COMMENT '操作状态（0正常 -1删除）',
    UNIQUE KEY `uk_no` (`no`),
    KEY `idx_supplier_id` (`supplier_id`),
    KEY `idx_account_id` (`account_id`),
    KEY `idx_order_id` (`order_id`),
    KEY `idx_return_time` (`return_time`),
    KEY `idx_status` (`status`),
    PRIMARY KEY (`id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ERP 采购退货 DO';

CREATE TABLE IF NOT EXISTS `erp_purchase_return_items` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
    `return_id` bigint NULL COMMENT '采购退货编号',
    `order_item_id` bigint NULL COMMENT '采购订单项编号；目的：方便更新关联的采购订单项的退货数量',
    `warehouse_id` bigint NULL COMMENT '仓库编号',
    `product_id` bigint NULL COMMENT '产品编号',
    `product_unit_id` bigint NULL COMMENT '产品单位单位；冗余',
    `product_price` decimal(24,6) NULL COMMENT '产品单位单价，单位：元',
    `count` decimal(24,6) NULL COMMENT '数量',
    `total_price` decimal(24,6) NULL COMMENT '总价，单位：元；totalPrice = productPrice * count',
    `tax_percent` decimal(24,6) NULL COMMENT '税率，百分比',
    `tax_price` decimal(24,6) NULL COMMENT '税额，单位：元；taxPrice = totalPrice * taxPercent',
    `remark` varchar(500) NULL COMMENT '备注',
    `dept_id` bigint(20) NULL DEFAULT NULL COMMENT '部门ID',
    `create_by` bigint(20) NULL DEFAULT NULL COMMENT '创建者',
    `create_time` datetime(0) NULL DEFAULT NULL COMMENT '创建时间',
    `update_by` bigint(20) NULL DEFAULT NULL COMMENT '更新者',
    `update_time` datetime(0) NULL DEFAULT NULL COMMENT '更新时间',
    `state` tinyint(1) NULL DEFAULT 0 COMMENT '操作状态（0正常 -1删除）',
    KEY `idx_return_id` (`return_id`),
    KEY `idx_order_item_id` (`order_item_id`),
    KEY `idx_product_id` (`product_id`),
    KEY `idx_warehouse_id` (`warehouse_id`),
    PRIMARY KEY (`id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ERP 采购退货项 DO';

CREATE TABLE IF NOT EXISTS `erp_supplier` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '供应商编号',
    `name` varchar(255) NULL COMMENT '供应商名称',
    `code` varchar(64) NULL COMMENT '供应商编码',
    `contact` varchar(255) NULL COMMENT '联系人',
    `mobile` varchar(32) NULL COMMENT '手机号码',
    `telephone` varchar(32) NULL COMMENT '联系电话',
    `email` varchar(255) NULL COMMENT '电子邮箱',
    `fax` varchar(255) NULL COMMENT '传真',
    `remark` varchar(500) NULL COMMENT '备注',
    `status` int NULL COMMENT '开启状态',
    `sort` int NULL COMMENT '排序',
    `tax_no` varchar(64) NULL COMMENT '纳税人识别号',
    `tax_percent` decimal(24,6) NULL COMMENT '税率',
    `bank_name` varchar(255) NULL COMMENT '开户行',
    `bank_account` varchar(255) NULL COMMENT '开户账号',
    `bank_address` varchar(255) NULL COMMENT '开户地址',
    `dept_id` bigint(20) NULL DEFAULT NULL COMMENT '部门ID',
    `create_by` bigint(20) NULL DEFAULT NULL COMMENT '创建者',
    `create_time` datetime(0) NULL DEFAULT NULL COMMENT '创建时间',
    `update_by` bigint(20) NULL DEFAULT NULL COMMENT '更新者',
    `update_time` datetime(0) NULL DEFAULT NULL COMMENT '更新时间',
    `state` tinyint(1) NULL DEFAULT 0 COMMENT '操作状态（0正常 -1删除）',
    KEY `idx_status` (`status`),
    KEY `idx_mobile` (`mobile`),
    KEY `idx_telephone` (`telephone`),
    KEY `idx_tax_no` (`tax_no`),
    UNIQUE KEY `uk_code` (`code`),
    PRIMARY KEY (`id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ERP 供应商 DO';

CREATE TABLE IF NOT EXISTS `erp_customer` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '客户编号',
    `name` varchar(255) NULL COMMENT '客户名称',
    `code` varchar(64) NULL COMMENT '客户编码，对接 erp_order.b_type_code',
    `contact` varchar(255) NULL COMMENT '联系人',
    `mobile` varchar(32) NULL COMMENT '手机号码',
    `telephone` varchar(32) NULL COMMENT '联系电话',
    `email` varchar(255) NULL COMMENT '电子邮箱',
    `fax` varchar(255) NULL COMMENT '传真',
    `remark` varchar(500) NULL COMMENT '备注',
    `status` int NULL COMMENT '开启状态',
    `sort` int NULL COMMENT '排序',
    `tax_no` varchar(64) NULL COMMENT '纳税人识别号',
    `tax_percent` decimal(24,6) NULL COMMENT '税率',
    `bank_name` varchar(255) NULL COMMENT '开户行',
    `bank_account` varchar(255) NULL COMMENT '开户账号',
    `bank_address` varchar(255) NULL COMMENT '开户地址',
    `dept_id` bigint(20) NULL DEFAULT NULL COMMENT '部门ID',
    `create_by` bigint(20) NULL DEFAULT NULL COMMENT '创建者',
    `create_time` datetime(0) NULL DEFAULT NULL COMMENT '创建时间',
    `update_by` bigint(20) NULL DEFAULT NULL COMMENT '更新者',
    `update_time` datetime(0) NULL DEFAULT NULL COMMENT '更新时间',
    `state` tinyint(1) NULL DEFAULT 0 COMMENT '操作状态（0正常 -1删除）',
    KEY `idx_status` (`status`),
    KEY `idx_mobile` (`mobile`),
    KEY `idx_telephone` (`telephone`),
    KEY `idx_tax_no` (`tax_no`),
    UNIQUE KEY `uk_code` (`code`),
    PRIMARY KEY (`id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ERP 客户 DO';


CREATE TABLE IF NOT EXISTS `erp_sale_out` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
    `no` varchar(64) NULL COMMENT '销售出库单号',
    `status` int NULL COMMENT '出库状态',
    `customer_id` bigint NULL COMMENT '客户编号',
    `account_id` bigint NULL COMMENT '结算账户编号',
    `sale_user_id` bigint NULL COMMENT '销售员编号',
    `out_time` datetime NULL COMMENT '出库时间',
    `order_id` bigint NULL COMMENT '销售订单编号，关联 erp_order.id',
    `order_no` varchar(64) NULL COMMENT '销售订单号；冗余',
    `total_count` decimal(24,6) NULL COMMENT '合计数量',
    `total_price` decimal(24,6) NULL COMMENT '最终合计价格，单位：元；totalPrice = totalProductPrice + totalTaxPrice - discountPrice + otherPrice',
    `receipt_price` decimal(24,6) NULL COMMENT '已收款金额，单位：元；目的：和  结合，记录已收款金额',
    `total_product_price` decimal(24,6) NULL COMMENT '合计产品价格，单位：元',
    `total_tax_price` decimal(24,6) NULL COMMENT '合计税额，单位：元',
    `discount_percent` decimal(24,6) NULL COMMENT '优惠率，百分比',
    `discount_price` decimal(24,6) NULL COMMENT '优惠金额，单位：元；discountPrice = (totalProductPrice + totalTaxPrice) * discountPercent',
    `other_price` decimal(24,6) NULL COMMENT '其它金额，单位：元',
    `file_url` varchar(255) NULL COMMENT '附件地址',
    `remark` varchar(500) NULL COMMENT '备注',
    `dept_id` bigint(20) NULL DEFAULT NULL COMMENT '部门ID',
    `create_by` bigint(20) NULL DEFAULT NULL COMMENT '创建者',
    `create_time` datetime(0) NULL DEFAULT NULL COMMENT '创建时间',
    `update_by` bigint(20) NULL DEFAULT NULL COMMENT '更新者',
    `update_time` datetime(0) NULL DEFAULT NULL COMMENT '更新时间',
    `state` tinyint(1) NULL DEFAULT 0 COMMENT '操作状态（0正常 -1删除）',
    UNIQUE KEY `uk_no` (`no`),
    KEY `idx_customer_id` (`customer_id`),
    KEY `idx_account_id` (`account_id`),
    KEY `idx_sale_user_id` (`sale_user_id`),
    KEY `idx_order_id` (`order_id`),
    KEY `idx_out_time` (`out_time`),
    KEY `idx_status` (`status`),
    PRIMARY KEY (`id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ERP 销售出库 DO';

CREATE TABLE IF NOT EXISTS `erp_sale_out_items` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
    `out_id` bigint NULL COMMENT '销售出库编号',
    `order_item_id` bigint NULL COMMENT '销售订单项编号，关联 erp_order_detail.id；用于更新销售订单项的出库数量',
    `warehouse_id` bigint NULL COMMENT '仓库编号',
    `product_id` bigint NULL COMMENT '产品编号',
    `product_unit_id` bigint NULL COMMENT '产品单位单位；冗余',
    `product_price` decimal(24,6) NULL COMMENT '产品单位单价，单位：元',
    `count` decimal(24,6) NULL COMMENT '数量',
    `total_price` decimal(24,6) NULL COMMENT '总价，单位：元；totalPrice = productPrice * count',
    `tax_percent` decimal(24,6) NULL COMMENT '税率，百分比',
    `tax_price` decimal(24,6) NULL COMMENT '税额，单位：元；taxPrice = totalPrice * taxPercent',
    `remark` varchar(500) NULL COMMENT '备注',
    `dept_id` bigint(20) NULL DEFAULT NULL COMMENT '部门ID',
    `create_by` bigint(20) NULL DEFAULT NULL COMMENT '创建者',
    `create_time` datetime(0) NULL DEFAULT NULL COMMENT '创建时间',
    `update_by` bigint(20) NULL DEFAULT NULL COMMENT '更新者',
    `update_time` datetime(0) NULL DEFAULT NULL COMMENT '更新时间',
    `state` tinyint(1) NULL DEFAULT 0 COMMENT '操作状态（0正常 -1删除）',
    KEY `idx_out_id` (`out_id`),
    KEY `idx_order_item_id` (`order_item_id`),
    KEY `idx_product_id` (`product_id`),
    KEY `idx_warehouse_id` (`warehouse_id`),
    PRIMARY KEY (`id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ERP 销售出库项 DO';

CREATE TABLE IF NOT EXISTS `erp_sale_return` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
    `no` varchar(64) NULL COMMENT '销售退货单号',
    `status` int NULL COMMENT '退货状态',
    `customer_id` bigint NULL COMMENT '客户编号',
    `account_id` bigint NULL COMMENT '结算账户编号',
    `sale_user_id` bigint NULL COMMENT '销售员编号',
    `return_time` datetime NULL COMMENT '退货时间',
    `order_id` bigint NULL COMMENT '销售订单编号，关联 erp_order.id',
    `order_no` varchar(64) NULL COMMENT '销售订单号；冗余',
    `total_count` decimal(24,6) NULL COMMENT '合计数量',
    `total_price` decimal(24,6) NULL COMMENT '最终合计价格，单位：元；totalPrice = totalProductPrice + totalTaxPrice - discountPrice + otherPrice',
    `refund_price` decimal(24,6) NULL COMMENT '已退款金额，单位：元；目的：和  结合，记录已退款金额',
    `total_product_price` decimal(24,6) NULL COMMENT '合计产品价格，单位：元',
    `total_tax_price` decimal(24,6) NULL COMMENT '合计税额，单位：元',
    `discount_percent` decimal(24,6) NULL COMMENT '优惠率，百分比',
    `discount_price` decimal(24,6) NULL COMMENT '优惠金额，单位：元；discountPrice = (totalProductPrice + totalTaxPrice) * discountPercent',
    `other_price` decimal(24,6) NULL COMMENT '其它金额，单位：元',
    `file_url` varchar(255) NULL COMMENT '附件地址',
    `remark` varchar(500) NULL COMMENT '备注',
    `dept_id` bigint(20) NULL DEFAULT NULL COMMENT '部门ID',
    `create_by` bigint(20) NULL DEFAULT NULL COMMENT '创建者',
    `create_time` datetime(0) NULL DEFAULT NULL COMMENT '创建时间',
    `update_by` bigint(20) NULL DEFAULT NULL COMMENT '更新者',
    `update_time` datetime(0) NULL DEFAULT NULL COMMENT '更新时间',
    `state` tinyint(1) NULL DEFAULT 0 COMMENT '操作状态（0正常 -1删除）',
    UNIQUE KEY `uk_no` (`no`),
    KEY `idx_customer_id` (`customer_id`),
    KEY `idx_account_id` (`account_id`),
    KEY `idx_sale_user_id` (`sale_user_id`),
    KEY `idx_order_id` (`order_id`),
    KEY `idx_return_time` (`return_time`),
    KEY `idx_status` (`status`),
    PRIMARY KEY (`id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ERP 销售退货 DO';

CREATE TABLE IF NOT EXISTS `erp_sale_return_items` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
    `return_id` bigint NULL COMMENT '销售退货编号',
    `order_item_id` bigint NULL COMMENT '销售订单项编号，关联 erp_order_detail.id；用于更新销售订单项的退货数量',
    `warehouse_id` bigint NULL COMMENT '仓库编号',
    `product_id` bigint NULL COMMENT '产品编号',
    `product_unit_id` bigint NULL COMMENT '产品单位单位；冗余',
    `product_price` decimal(24,6) NULL COMMENT '产品单位单价，单位：元',
    `count` decimal(24,6) NULL COMMENT '数量',
    `total_price` decimal(24,6) NULL COMMENT '总价，单位：元；totalPrice = productPrice * count',
    `tax_percent` decimal(24,6) NULL COMMENT '税率，百分比',
    `tax_price` decimal(24,6) NULL COMMENT '税额，单位：元；taxPrice = totalPrice * taxPercent',
    `remark` varchar(500) NULL COMMENT '备注',
    `dept_id` bigint(20) NULL DEFAULT NULL COMMENT '部门ID',
    `create_by` bigint(20) NULL DEFAULT NULL COMMENT '创建者',
    `create_time` datetime(0) NULL DEFAULT NULL COMMENT '创建时间',
    `update_by` bigint(20) NULL DEFAULT NULL COMMENT '更新者',
    `update_time` datetime(0) NULL DEFAULT NULL COMMENT '更新时间',
    `state` tinyint(1) NULL DEFAULT 0 COMMENT '操作状态（0正常 -1删除）',
    KEY `idx_return_id` (`return_id`),
    KEY `idx_order_item_id` (`order_item_id`),
    KEY `idx_product_id` (`product_id`),
    KEY `idx_warehouse_id` (`warehouse_id`),
    PRIMARY KEY (`id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ERP 销售退货项 DO';

CREATE TABLE IF NOT EXISTS `erp_stock_check` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '盘点编号',
    `no` varchar(64) NULL COMMENT '盘点单号',
    `check_time` datetime NULL COMMENT '盘点时间',
    `total_count` decimal(24,6) NULL COMMENT '合计数量',
    `total_price` decimal(24,6) NULL COMMENT '合计金额，单位：元',
    `status` int NULL COMMENT '状态',
    `remark` varchar(500) NULL COMMENT '备注',
    `file_url` varchar(255) NULL COMMENT '附件 URL',
    `dept_id` bigint(20) NULL DEFAULT NULL COMMENT '部门ID',
    `create_by` bigint(20) NULL DEFAULT NULL COMMENT '创建者',
    `create_time` datetime(0) NULL DEFAULT NULL COMMENT '创建时间',
    `update_by` bigint(20) NULL DEFAULT NULL COMMENT '更新者',
    `update_time` datetime(0) NULL DEFAULT NULL COMMENT '更新时间',
    `state` tinyint(1) NULL DEFAULT 0 COMMENT '操作状态（0正常 -1删除）',
    UNIQUE KEY `uk_no` (`no`),
    KEY `idx_check_time` (`check_time`),
    KEY `idx_status` (`status`),
    PRIMARY KEY (`id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ERP 库存盘点单 DO';

CREATE TABLE IF NOT EXISTS `erp_stock_check_item` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '盘点项编号',
    `check_id` bigint NULL COMMENT '盘点编号',
    `warehouse_id` bigint NULL COMMENT '仓库编号',
    `product_id` bigint NULL COMMENT '产品编号',
    `product_unit_id` bigint NULL COMMENT '产品单位编号；冗余',
    `product_price` decimal(24,6) NULL COMMENT '产品单价',
    `stock_count` decimal(24,6) NULL COMMENT '账面数量（当前库存）',
    `actual_count` decimal(24,6) NULL COMMENT '实际数量（实际库存）',
    `count` decimal(24,6) NULL COMMENT '盈亏数量；count = stockCount - actualCount',
    `total_price` decimal(24,6) NULL COMMENT '合计金额，单位：元',
    `remark` varchar(500) NULL COMMENT '备注',
    `dept_id` bigint(20) NULL DEFAULT NULL COMMENT '部门ID',
    `create_by` bigint(20) NULL DEFAULT NULL COMMENT '创建者',
    `create_time` datetime(0) NULL DEFAULT NULL COMMENT '创建时间',
    `update_by` bigint(20) NULL DEFAULT NULL COMMENT '更新者',
    `update_time` datetime(0) NULL DEFAULT NULL COMMENT '更新时间',
    `state` tinyint(1) NULL DEFAULT 0 COMMENT '操作状态（0正常 -1删除）',
    KEY `idx_check_id` (`check_id`),
    KEY `idx_product_id` (`product_id`),
    KEY `idx_warehouse_id` (`warehouse_id`),
    PRIMARY KEY (`id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ERP 库存盘点单项 DO';

CREATE TABLE IF NOT EXISTS `erp_stock` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
    `product_id` bigint DEFAULT 0 COMMENT '产品编号',
    `warehouse_id` bigint DEFAULT 0 COMMENT '仓库编号',
    `count` decimal(24,6) DEFAULT 0.0 COMMENT '库存数量',
    `enablenum` decimal(24,6) DEFAULT 0.0 COMMENT '可发货数量 = 库存数量 - 已发货未结存数量 （已发货未结存数量 表示：全渠道系统中已发货，但是线下系统还没过账扣减库存的数量）',
    `ensalenum` decimal(24,6) DEFAULT 0.0 COMMENT '可用数量 = 可发数量-已锁定库存数量',
    `dept_id` bigint(20) NULL DEFAULT 0 COMMENT '部门ID',
    `create_by` bigint(20) NULL DEFAULT NULL COMMENT '创建者',
    `create_time` datetime(0) NULL DEFAULT NULL COMMENT '创建时间',
    `update_by` bigint(20) NULL DEFAULT NULL COMMENT '更新者',
    `update_time` datetime(0) NULL DEFAULT NULL COMMENT '更新时间',
    `state` tinyint(1) NULL DEFAULT 0 COMMENT '操作状态（0正常 -1删除）',
    UNIQUE KEY `uk_product_warehouse` (`product_id`, `warehouse_id`),
    KEY `idx_product_id` (`product_id`),
    PRIMARY KEY (`id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ERP 产品库存 DO';

CREATE TABLE IF NOT EXISTS `erp_stock_in` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '入库编号',
    `no` varchar(64) NULL COMMENT '入库单号',
    `supplier_id` bigint NULL COMMENT '供应商编号',
    `in_time` datetime NULL COMMENT '入库时间',
    `total_count` decimal(24,6) NULL COMMENT '合计数量',
    `total_price` decimal(24,6) NULL COMMENT '合计金额，单位：元',
    `status` int NULL COMMENT '状态',
    `remark` varchar(500) NULL COMMENT '备注',
    `file_url` varchar(255) NULL COMMENT '附件 URL',
    `dept_id` bigint(20) NULL DEFAULT NULL COMMENT '部门ID',
    `create_by` bigint(20) NULL DEFAULT NULL COMMENT '创建者',
    `create_time` datetime(0) NULL DEFAULT NULL COMMENT '创建时间',
    `update_by` bigint(20) NULL DEFAULT NULL COMMENT '更新者',
    `update_time` datetime(0) NULL DEFAULT NULL COMMENT '更新时间',
    `state` tinyint(1) NULL DEFAULT 0 COMMENT '操作状态（0正常 -1删除）',
    UNIQUE KEY `uk_no` (`no`),
    KEY `idx_supplier_id` (`supplier_id`),
    KEY `idx_in_time` (`in_time`),
    KEY `idx_status` (`status`),
    PRIMARY KEY (`id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ERP 其它入库单 DO';

CREATE TABLE IF NOT EXISTS `erp_stock_in_item` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '入库项编号',
    `in_id` bigint NULL COMMENT '入库编号',
    `warehouse_id` bigint NULL COMMENT '仓库编号',
    `product_id` bigint NULL COMMENT '产品编号',
    `product_unit_id` bigint NULL COMMENT '产品单位编号；冗余',
    `product_price` decimal(24,6) NULL COMMENT '产品单价',
    `count` decimal(24,6) NULL COMMENT '产品数量',
    `total_price` decimal(24,6) NULL COMMENT '合计金额，单位：元',
    `remark` varchar(500) NULL COMMENT '备注',
    `dept_id` bigint(20) NULL DEFAULT NULL COMMENT '部门ID',
    `create_by` bigint(20) NULL DEFAULT NULL COMMENT '创建者',
    `create_time` datetime(0) NULL DEFAULT NULL COMMENT '创建时间',
    `update_by` bigint(20) NULL DEFAULT NULL COMMENT '更新者',
    `update_time` datetime(0) NULL DEFAULT NULL COMMENT '更新时间',
    `state` tinyint(1) NULL DEFAULT 0 COMMENT '操作状态（0正常 -1删除）',
    KEY `idx_in_id` (`in_id`),
    KEY `idx_product_id` (`product_id`),
    KEY `idx_warehouse_id` (`warehouse_id`),
    PRIMARY KEY (`id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ERP 其它入库单项 DO';

CREATE TABLE IF NOT EXISTS `erp_stock_move` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '调拨编号',
    `no` varchar(64) NULL COMMENT '调拨单号',
    `move_time` datetime NULL COMMENT '调拨时间',
    `total_count` decimal(24,6) NULL COMMENT '合计数量',
    `total_price` decimal(24,6) NULL COMMENT '合计金额，单位：元',
    `status` int NULL COMMENT '状态',
    `remark` varchar(500) NULL COMMENT '备注',
    `file_url` varchar(255) NULL COMMENT '附件 URL',
    `dept_id` bigint(20) NULL DEFAULT NULL COMMENT '部门ID',
    `create_by` bigint(20) NULL DEFAULT NULL COMMENT '创建者',
    `create_time` datetime(0) NULL DEFAULT NULL COMMENT '创建时间',
    `update_by` bigint(20) NULL DEFAULT NULL COMMENT '更新者',
    `update_time` datetime(0) NULL DEFAULT NULL COMMENT '更新时间',
    `state` tinyint(1) NULL DEFAULT 0 COMMENT '操作状态（0正常 -1删除）',
    UNIQUE KEY `uk_no` (`no`),
    KEY `idx_move_time` (`move_time`),
    KEY `idx_status` (`status`),
    PRIMARY KEY (`id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ERP 库存调拨单 DO';

CREATE TABLE IF NOT EXISTS `erp_stock_move_item` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '调拨项编号',
    `move_id` bigint NULL COMMENT '调拨编号',
    `from_warehouse_id` bigint NULL COMMENT '调出仓库编号',
    `to_warehouse_id` bigint NULL COMMENT '调入仓库编号',
    `product_id` bigint NULL COMMENT '产品编号',
    `product_unit_id` bigint NULL COMMENT '产品单位编号；冗余',
    `product_price` decimal(24,6) NULL COMMENT '产品单价',
    `count` decimal(24,6) NULL COMMENT '产品数量',
    `total_price` decimal(24,6) NULL COMMENT '合计金额，单位：元',
    `remark` varchar(500) NULL COMMENT '备注',
    `dept_id` bigint(20) NULL DEFAULT NULL COMMENT '部门ID',
    `create_by` bigint(20) NULL DEFAULT NULL COMMENT '创建者',
    `create_time` datetime(0) NULL DEFAULT NULL COMMENT '创建时间',
    `update_by` bigint(20) NULL DEFAULT NULL COMMENT '更新者',
    `update_time` datetime(0) NULL DEFAULT NULL COMMENT '更新时间',
    `state` tinyint(1) NULL DEFAULT 0 COMMENT '操作状态（0正常 -1删除）',
    KEY `idx_move_id` (`move_id`),
    KEY `idx_product_id` (`product_id`),
    KEY `idx_from_warehouse_id` (`from_warehouse_id`),
    KEY `idx_to_warehouse_id` (`to_warehouse_id`),
    PRIMARY KEY (`id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ERP 库存调拨单项 DO';

CREATE TABLE IF NOT EXISTS `erp_stock_out` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '出库编号',
    `no` varchar(64) NULL COMMENT '出库单号',
    `customer_id` bigint NULL COMMENT '客户编号，关联 erp_customer.id',
    `out_time` datetime NULL COMMENT '出库时间',
    `total_count` decimal(24,6) NULL COMMENT '合计数量',
    `total_price` decimal(24,6) NULL COMMENT '合计金额，单位：元',
    `status` int NULL COMMENT '状态',
    `remark` varchar(500) NULL COMMENT '备注',
    `file_url` varchar(255) NULL COMMENT '附件 URL',
    `dept_id` bigint(20) NULL DEFAULT NULL COMMENT '部门ID',
    `create_by` bigint(20) NULL DEFAULT NULL COMMENT '创建者',
    `create_time` datetime(0) NULL DEFAULT NULL COMMENT '创建时间',
    `update_by` bigint(20) NULL DEFAULT NULL COMMENT '更新者',
    `update_time` datetime(0) NULL DEFAULT NULL COMMENT '更新时间',
    `state` tinyint(1) NULL DEFAULT 0 COMMENT '操作状态（0正常 -1删除）',
    UNIQUE KEY `uk_no` (`no`),
    KEY `idx_customer_id` (`customer_id`),
    KEY `idx_out_time` (`out_time`),
    KEY `idx_status` (`status`),
    PRIMARY KEY (`id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ERP 其它出库单 DO';

CREATE TABLE IF NOT EXISTS `erp_stock_out_item` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '出库项编号',
    `out_id` bigint NULL COMMENT '出库编号',
    `warehouse_id` bigint NULL COMMENT '仓库编号',
    `product_id` bigint NULL COMMENT '产品编号',
    `product_unit_id` bigint NULL COMMENT '产品单位编号；冗余',
    `product_price` decimal(24,6) NULL COMMENT '产品单价',
    `count` decimal(24,6) NULL COMMENT '产品数量',
    `total_price` decimal(24,6) NULL COMMENT '合计金额，单位：元',
    `remark` varchar(500) NULL COMMENT '备注',
    `dept_id` bigint(20) NULL DEFAULT NULL COMMENT '部门ID',
    `create_by` bigint(20) NULL DEFAULT NULL COMMENT '创建者',
    `create_time` datetime(0) NULL DEFAULT NULL COMMENT '创建时间',
    `update_by` bigint(20) NULL DEFAULT NULL COMMENT '更新者',
    `update_time` datetime(0) NULL DEFAULT NULL COMMENT '更新时间',
    `state` tinyint(1) NULL DEFAULT 0 COMMENT '操作状态（0正常 -1删除）',
    KEY `idx_out_id` (`out_id`),
    KEY `idx_product_id` (`product_id`),
    KEY `idx_warehouse_id` (`warehouse_id`),
    PRIMARY KEY (`id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ERP 其它出库单项 DO';

CREATE TABLE IF NOT EXISTS `erp_stock_record` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
    `product_id` bigint NULL COMMENT '产品编号',
    `warehouse_id` bigint NULL COMMENT '仓库编号',
    `count` decimal(24,6) NULL COMMENT '出入库数量；正数，表示入库；负数，表示出库',
    `total_count` decimal(24,6) NULL COMMENT '总库存量；出入库之后，目前的库存量',
    `biz_type` int NULL COMMENT '业务类型',
    `biz_id` bigint NULL COMMENT '业务编号；例如说：',
    `biz_item_id` bigint NULL COMMENT '业务项编号；例如说：',
    `biz_no` varchar(64) NULL COMMENT '业务单号；例如说：',
    `dept_id` bigint(20) NULL DEFAULT NULL COMMENT '部门ID',
    `create_by` bigint(20) NULL DEFAULT NULL COMMENT '创建者',
    `create_time` datetime(0) NULL DEFAULT NULL COMMENT '创建时间',
    `update_by` bigint(20) NULL DEFAULT NULL COMMENT '更新者',
    `update_time` datetime(0) NULL DEFAULT NULL COMMENT '更新时间',
    `state` tinyint(1) NULL DEFAULT 0 COMMENT '操作状态（0正常 -1删除）',
    KEY `idx_product_warehouse` (`product_id`, `warehouse_id`),
    KEY `idx_biz_type` (`biz_type`),
    KEY `idx_biz_type_biz_id` (`biz_type`, `biz_id`),
    KEY `idx_biz_item_id` (`biz_item_id`),
    KEY `idx_create_time` (`create_time`),
    PRIMARY KEY (`id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ERP 产品库存明细 DO';

CREATE TABLE IF NOT EXISTS `erp_warehouse` (
   `id` bigint NOT NULL AUTO_INCREMENT COMMENT '仓库id',
   `code` varchar(255) NULL COMMENT '仓库编号',
   `name` varchar(255) NULL COMMENT '仓库名称',
    `address` varchar(255) NULL COMMENT '仓库地址',
    `sort` bigint NULL COMMENT '排序',
    `remark` varchar(500) NULL COMMENT '备注',
    `principal` varchar(255) NULL COMMENT '负责人',
    `warehouse_price` decimal(24,6) NULL COMMENT '仓储费，单位：元',
    `truckage_price` decimal(24,6) NULL COMMENT '搬运费，单位：元',
    `status` int NULL COMMENT '开启状态',
    `default_status`  tinyint(1) NULL DEFAULT 0 NULL COMMENT '是否默认',
    `dept_id` bigint(20) NULL DEFAULT NULL COMMENT '部门ID',
    `create_by` bigint(20) NULL DEFAULT NULL COMMENT '创建者',
    `create_time` datetime(0) NULL DEFAULT NULL COMMENT '创建时间',
    `update_by` bigint(20) NULL DEFAULT NULL COMMENT '更新者',
    `update_time` datetime(0) NULL DEFAULT NULL COMMENT '更新时间',
    `state` tinyint(1) NULL DEFAULT 0 COMMENT '操作状态（0正常 -1删除）',
    KEY `idx_status` (`status`),
    KEY `idx_default_status` (`default_status`),
    KEY `idx_name` (`name`),
    PRIMARY KEY (`id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ERP 仓库 DO';
