CREATE TABLE IF NOT EXISTS `erp_sales_order_agent_config` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `name` VARCHAR(128) NOT NULL COMMENT '配置名称',
    `agent_id` VARCHAR(128) NOT NULL COMMENT '智能体AgentID',
    `status` TINYINT NOT NULL DEFAULT 1 COMMENT '状态：1启用，0禁用',
    `remark` VARCHAR(500) DEFAULT NULL COMMENT '备注',
    `dept_id` bigint(20) NULL DEFAULT NULL COMMENT '部门ID',
    `create_by` bigint(20) NULL DEFAULT NULL COMMENT '创建者',
    `create_time` datetime(0) NULL DEFAULT NULL COMMENT '创建时间',
    `update_by` bigint(20) NULL DEFAULT NULL COMMENT '更新者',
    `update_time` datetime(0) NULL DEFAULT NULL COMMENT '更新时间',
    `state` tinyint(1) NULL DEFAULT 0 COMMENT '操作状态（0正常 -1删除）',
    PRIMARY KEY (`id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='销售订单智能体配置表';

CREATE TABLE IF NOT EXISTS `erp_integration_config` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `type` VARCHAR(128) NOT NULL COMMENT '接入类型',
    `data` TEXT  COMMENT '配置快照',
    `status` TINYINT NOT NULL DEFAULT 1 COMMENT '状态：1启用，0禁用',
    `dept_id` bigint(20) NULL DEFAULT NULL COMMENT '部门ID',
    `create_by` bigint(20) NULL DEFAULT NULL COMMENT '创建者',
    `create_time` datetime(0) NULL DEFAULT NULL COMMENT '创建时间',
    `update_by` bigint(20) NULL DEFAULT NULL COMMENT '更新者',
    `update_time` datetime(0) NULL DEFAULT NULL COMMENT '更新时间',
    `state` tinyint(1) NULL DEFAULT 0 COMMENT '操作状态（0正常 -1删除）',
    PRIMARY KEY (`id`),
    UNIQUE INDEX `type`(`type`) USING BTREE
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='erp集成系统';

CREATE TABLE IF NOT EXISTS `erp_order` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `tid` VARCHAR(50) NOT NULL COMMENT '网店订单编号',
    `weight` DECIMAL(18,4) DEFAULT NULL COMMENT '订单重量',
    `size` DECIMAL(18,4) DEFAULT NULL COMMENT '订单尺寸/体积',
    `buyernick` VARCHAR(50) DEFAULT NULL COMMENT '买家账号',
    `buyermessage` VARCHAR(50) DEFAULT NULL COMMENT '买家留言',
    `sellermemo` VARCHAR(50) DEFAULT NULL COMMENT '卖家备注',
    `total` DECIMAL(20,8) DEFAULT NULL COMMENT '订单总金额（含运费）',
    `privilege` DECIMAL(20,8) NOT NULL DEFAULT 0.00000000 COMMENT '订单优惠金额',
    `postfee` DECIMAL(20,8) NOT NULL DEFAULT 0.00000000 COMMENT '运费',
    `receivername` VARCHAR(50) NOT NULL COMMENT '收货人名称',
    `receiverstate` VARCHAR(50) NOT NULL COMMENT '收货省',
    `receivercity` VARCHAR(100) NOT NULL COMMENT '收货市',
    `receiverdistrict` VARCHAR(50) NOT NULL COMMENT '收货区',
    `receiveraddress` VARCHAR(255) NOT NULL COMMENT '收货地址',
    `receiverphone` VARCHAR(50) DEFAULT NULL COMMENT '收货电话',
    `receivermobile` VARCHAR(50) NOT NULL COMMENT '收货人手机号',
    `receiverzip` VARCHAR(20) DEFAULT NULL COMMENT '邮编',
    `status` VARCHAR(200) NOT NULL COMMENT '订单状态',
    `type` VARCHAR(50) NOT NULL COMMENT '订单类型（Cod/NoCod）',
    `invoicename` VARCHAR(50) DEFAULT NULL COMMENT '发票抬头',
    `sellerflag` VARCHAR(50) DEFAULT NULL COMMENT '卖家旗帜',
    `paytime` DATETIME(0) DEFAULT NULL COMMENT '付款时间',
    `logistbtypecode` VARCHAR(100) DEFAULT NULL COMMENT '物流公司编码',
    `logistbillcode` VARCHAR(100) DEFAULT NULL COMMENT '物流单号',
    `btypecode` VARCHAR(50) DEFAULT NULL COMMENT '往来单位编码',
    `details_json` LONGTEXT COMMENT '订单商品明细JSON',
    `accounts_json` LONGTEXT COMMENT '订单账户信息JSON',
    `billcode` VARCHAR(100) DEFAULT NULL COMMENT '管家婆返回订单编号',
    `sync_message` VARCHAR(500) DEFAULT NULL COMMENT '同步结果描述',
    `sync_status` TINYINT NOT NULL DEFAULT 0 COMMENT '同步状态：0待同步 1成功 2失败',
    `sync_time` DATETIME(0) DEFAULT NULL COMMENT '同步时间',
    `dept_id` BIGINT(20) NULL DEFAULT NULL COMMENT '部门ID',
    `create_by` BIGINT(20) NULL DEFAULT NULL COMMENT '创建者',
    `create_time` DATETIME(0) NULL DEFAULT NULL COMMENT '创建时间',
    `update_by` BIGINT(20) NULL DEFAULT NULL COMMENT '更新者',
    `update_time` DATETIME(0) NULL DEFAULT NULL COMMENT '更新时间',
    `state` TINYINT(1) NULL DEFAULT 0 COMMENT '操作状态（0正常 -1删除）',
    PRIMARY KEY (`id`),
    UNIQUE INDEX `uk_erp_order_tid` (`tid`) USING BTREE,
    INDEX `idx_erp_order_status` (`status`) USING BTREE,
    INDEX `idx_erp_order_sync_status` (`sync_status`) USING BTREE
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ERP订单主表';

CREATE TABLE IF NOT EXISTS `erp_order_detail` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `order_id` BIGINT UNSIGNED NOT NULL COMMENT '订单主表ID',
    `tid` VARCHAR(50) NOT NULL COMMENT '网店订单编号',
    `oid` VARCHAR(50) NOT NULL COMMENT '网店订单明细编号',
    `barcode` VARCHAR(50) DEFAULT NULL COMMENT '商品条码',
    `eshopgoodsid` VARCHAR(100) DEFAULT NULL COMMENT '网店商品ID',
    `outeriid` VARCHAR(100) DEFAULT NULL COMMENT '网店商家编码',
    `eshopgoodsname` VARCHAR(100) NOT NULL COMMENT '网店商品名称',
    `eshopskuid` VARCHAR(100) DEFAULT NULL COMMENT '网店商品SKUID',
    `eshopskuname` VARCHAR(100) DEFAULT NULL COMMENT '网店商品SKU名称',
    `numiid` BIGINT(20) DEFAULT NULL COMMENT '商品ID（方案B）',
    `skuid` BIGINT(20) DEFAULT NULL COMMENT '规格ID（方案B）',
    `num` DECIMAL(18,4) NOT NULL COMMENT '基本单位数量',
    `payment` DECIMAL(20,8) NOT NULL COMMENT '商品总额',
    `picpath` VARCHAR(255) DEFAULT NULL COMMENT '商品图片路径',
    `weight` DECIMAL(18,4) DEFAULT NULL COMMENT '重量',
    `size` DECIMAL(18,4) DEFAULT NULL COMMENT '尺寸/体积',
    `unitid` BIGINT(20) DEFAULT NULL COMMENT '销售单位ID',
    `unitqty` DECIMAL(18,4) DEFAULT NULL COMMENT '销售单位数量',
    `dept_id` BIGINT(20) NULL DEFAULT NULL COMMENT '部门ID',
    `create_by` BIGINT(20) NULL DEFAULT NULL COMMENT '创建者',
    `create_time` DATETIME(0) NULL DEFAULT NULL COMMENT '创建时间',
    `update_by` BIGINT(20) NULL DEFAULT NULL COMMENT '更新者',
    `update_time` DATETIME(0) NULL DEFAULT NULL COMMENT '更新时间',
    `state` TINYINT(1) NULL DEFAULT 0 COMMENT '操作状态（0正常 -1删除）',
    PRIMARY KEY (`id`),
    UNIQUE INDEX `uk_erp_order_detail_oid` (`oid`) USING BTREE,
    INDEX `idx_erp_order_detail_order_id` (`order_id`) USING BTREE,
    INDEX `idx_erp_order_detail_tid` (`tid`) USING BTREE
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ERP订单明细表';

CREATE TABLE IF NOT EXISTS `erp_order_account` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `order_id` BIGINT UNSIGNED NOT NULL COMMENT '订单主表ID',
    `tid` VARCHAR(50) NOT NULL COMMENT '网店订单编号',
    `finance_code` VARCHAR(50) NOT NULL COMMENT '账户编码',
    `total` DECIMAL(20,8) NOT NULL COMMENT '收款金额',
    `dept_id` BIGINT(20) NULL DEFAULT NULL COMMENT '部门ID',
    `create_by` BIGINT(20) NULL DEFAULT NULL COMMENT '创建者',
    `create_time` DATETIME(0) NULL DEFAULT NULL COMMENT '创建时间',
    `update_by` BIGINT(20) NULL DEFAULT NULL COMMENT '更新者',
    `update_time` DATETIME(0) NULL DEFAULT NULL COMMENT '更新时间',
    `state` TINYINT(1) NULL DEFAULT 0 COMMENT '操作状态（0正常 -1删除）',
    PRIMARY KEY (`id`),
    INDEX `idx_erp_order_account_order_id` (`order_id`) USING BTREE,
    INDEX `idx_erp_order_account_tid` (`tid`) USING BTREE,
    INDEX `idx_erp_order_account_finance_code` (`finance_code`) USING BTREE
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ERP订单账户表';
