package aidatasetserviceimpl

import "github.com/google/wire"

var ProviderSet = wire.NewSet(NewIDataSetServiceImpl, NewHttpClient, NewIDataSetDocumentServiceImpl,
	NewIChunkServiceImpl, NewIAssistantServiceImpl, NewIChartServiceImpl, NewIAiPredictionServiceImpl, NewIAiPredictionExceptionServiceImpl, NewIAiPredictionControlServiceImpl, NewIAiModelProviderServiceImpl, NewIAiLLMSettingServiceImpl, NewIAiUserLLMServiceImpl)
