// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v3.21.12
// source: manifest/protobuf/aiagent/confighotload/v1/agent.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentRegQuest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AgentRegQuest) Reset() {
	*x = AgentRegQuest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_manifest_protobuf_aiagent_confighotload_v1_agent_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AgentRegQuest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentRegQuest) ProtoMessage() {}

func (x *AgentRegQuest) ProtoReflect() protoreflect.Message {
	mi := &file_manifest_protobuf_aiagent_confighotload_v1_agent_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentRegQuest.ProtoReflect.Descriptor instead.
func (*AgentRegQuest) Descriptor() ([]byte, []int) {
	return file_manifest_protobuf_aiagent_confighotload_v1_agent_proto_rawDescGZIP(), []int{0}
}

type AgentRegResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 响应状态码
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	// 响应消息
	Msg string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *AgentRegResponse) Reset() {
	*x = AgentRegResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_manifest_protobuf_aiagent_confighotload_v1_agent_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AgentRegResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentRegResponse) ProtoMessage() {}

func (x *AgentRegResponse) ProtoReflect() protoreflect.Message {
	mi := &file_manifest_protobuf_aiagent_confighotload_v1_agent_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentRegResponse.ProtoReflect.Descriptor instead.
func (*AgentRegResponse) Descriptor() ([]byte, []int) {
	return file_manifest_protobuf_aiagent_confighotload_v1_agent_proto_rawDescGZIP(), []int{1}
}

func (x *AgentRegResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *AgentRegResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type AgentHeartbeatReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AgentId uint64 `protobuf:"varint,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"` // agent 的id
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`                 // agent 的配置版本
}

func (x *AgentHeartbeatReq) Reset() {
	*x = AgentHeartbeatReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_manifest_protobuf_aiagent_confighotload_v1_agent_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AgentHeartbeatReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentHeartbeatReq) ProtoMessage() {}

func (x *AgentHeartbeatReq) ProtoReflect() protoreflect.Message {
	mi := &file_manifest_protobuf_aiagent_confighotload_v1_agent_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentHeartbeatReq.ProtoReflect.Descriptor instead.
func (*AgentHeartbeatReq) Descriptor() ([]byte, []int) {
	return file_manifest_protobuf_aiagent_confighotload_v1_agent_proto_rawDescGZIP(), []int{2}
}

func (x *AgentHeartbeatReq) GetAgentId() uint64 {
	if x != nil {
		return x.AgentId
	}
	return 0
}

func (x *AgentHeartbeatReq) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type AgentHeartbeatRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 配置uuid
	Version string `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	AgentId uint64 `protobuf:"varint,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"` // agent 的id
}

func (x *AgentHeartbeatRes) Reset() {
	*x = AgentHeartbeatRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_manifest_protobuf_aiagent_confighotload_v1_agent_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AgentHeartbeatRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentHeartbeatRes) ProtoMessage() {}

func (x *AgentHeartbeatRes) ProtoReflect() protoreflect.Message {
	mi := &file_manifest_protobuf_aiagent_confighotload_v1_agent_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentHeartbeatRes.ProtoReflect.Descriptor instead.
func (*AgentHeartbeatRes) Descriptor() ([]byte, []int) {
	return file_manifest_protobuf_aiagent_confighotload_v1_agent_proto_rawDescGZIP(), []int{3}
}

func (x *AgentHeartbeatRes) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *AgentHeartbeatRes) GetAgentId() uint64 {
	if x != nil {
		return x.AgentId
	}
	return 0
}

type AgentGetConfigReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version string `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	AgentId uint64 `protobuf:"varint,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"` // agent 的id
}

func (x *AgentGetConfigReq) Reset() {
	*x = AgentGetConfigReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_manifest_protobuf_aiagent_confighotload_v1_agent_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AgentGetConfigReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentGetConfigReq) ProtoMessage() {}

func (x *AgentGetConfigReq) ProtoReflect() protoreflect.Message {
	mi := &file_manifest_protobuf_aiagent_confighotload_v1_agent_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentGetConfigReq.ProtoReflect.Descriptor instead.
func (*AgentGetConfigReq) Descriptor() ([]byte, []int) {
	return file_manifest_protobuf_aiagent_confighotload_v1_agent_proto_rawDescGZIP(), []int{4}
}

func (x *AgentGetConfigReq) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *AgentGetConfigReq) GetAgentId() uint64 {
	if x != nil {
		return x.AgentId
	}
	return 0
}

type AgentGetConfigRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content string `protobuf:"bytes,1,opt,name=Content,proto3" json:"Content,omitempty"`
}

func (x *AgentGetConfigRes) Reset() {
	*x = AgentGetConfigRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_manifest_protobuf_aiagent_confighotload_v1_agent_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AgentGetConfigRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentGetConfigRes) ProtoMessage() {}

func (x *AgentGetConfigRes) ProtoReflect() protoreflect.Message {
	mi := &file_manifest_protobuf_aiagent_confighotload_v1_agent_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentGetConfigRes.ProtoReflect.Descriptor instead.
func (*AgentGetConfigRes) Descriptor() ([]byte, []int) {
	return file_manifest_protobuf_aiagent_confighotload_v1_agent_proto_rawDescGZIP(), []int{5}
}

func (x *AgentGetConfigRes) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type AgentRef struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // "db" / "file" / "builtin"
	Id   string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`     // "123" / "sales" / "erp/sales"
}

func (x *AgentRef) Reset() {
	*x = AgentRef{}
	if protoimpl.UnsafeEnabled {
		mi := &file_manifest_protobuf_aiagent_confighotload_v1_agent_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AgentRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentRef) ProtoMessage() {}

func (x *AgentRef) ProtoReflect() protoreflect.Message {
	mi := &file_manifest_protobuf_aiagent_confighotload_v1_agent_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentRef.ProtoReflect.Descriptor instead.
func (*AgentRef) Descriptor() ([]byte, []int) {
	return file_manifest_protobuf_aiagent_confighotload_v1_agent_proto_rawDescGZIP(), []int{6}
}

func (x *AgentRef) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AgentRef) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// --- 变更订阅请求（双向流） ---
type WatchAgentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GatewayId int64 `protobuf:"varint,1,opt,name=gatewayId,proto3" json:"gatewayId,omitempty"`
}

func (x *WatchAgentRequest) Reset() {
	*x = WatchAgentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_manifest_protobuf_aiagent_confighotload_v1_agent_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WatchAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchAgentRequest) ProtoMessage() {}

func (x *WatchAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_manifest_protobuf_aiagent_confighotload_v1_agent_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchAgentRequest.ProtoReflect.Descriptor instead.
func (*WatchAgentRequest) Descriptor() ([]byte, []int) {
	return file_manifest_protobuf_aiagent_confighotload_v1_agent_proto_rawDescGZIP(), []int{7}
}

func (x *WatchAgentRequest) GetGatewayId() int64 {
	if x != nil {
		return x.GatewayId
	}
	return 0
}

// --- 变更推送事件 ---
type ConfigChangeEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ref        *AgentRef              `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	NewVersion string                 `protobuf:"bytes,2,opt,name=new_version,json=newVersion,proto3" json:"new_version,omitempty"`
	ConfigHash string                 `protobuf:"bytes,3,opt,name=config_hash,json=configHash,proto3" json:"config_hash,omitempty"`
	Action     string                 `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"`
	Content    string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	Timestamp  *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *ConfigChangeEvent) Reset() {
	*x = ConfigChangeEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_manifest_protobuf_aiagent_confighotload_v1_agent_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigChangeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigChangeEvent) ProtoMessage() {}

func (x *ConfigChangeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_manifest_protobuf_aiagent_confighotload_v1_agent_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigChangeEvent.ProtoReflect.Descriptor instead.
func (*ConfigChangeEvent) Descriptor() ([]byte, []int) {
	return file_manifest_protobuf_aiagent_confighotload_v1_agent_proto_rawDescGZIP(), []int{8}
}

func (x *ConfigChangeEvent) GetRef() *AgentRef {
	if x != nil {
		return x.Ref
	}
	return nil
}

func (x *ConfigChangeEvent) GetNewVersion() string {
	if x != nil {
		return x.NewVersion
	}
	return ""
}

func (x *ConfigChangeEvent) GetConfigHash() string {
	if x != nil {
		return x.ConfigHash
	}
	return ""
}

func (x *ConfigChangeEvent) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ConfigChangeEvent) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ConfigChangeEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// WebrtcBroadcastReply WebRTC广播响应。
type AgentBroadcastReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 响应状态码
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	// 响应消息
	Msg string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *AgentBroadcastReply) Reset() {
	*x = AgentBroadcastReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_manifest_protobuf_aiagent_confighotload_v1_agent_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AgentBroadcastReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentBroadcastReply) ProtoMessage() {}

func (x *AgentBroadcastReply) ProtoReflect() protoreflect.Message {
	mi := &file_manifest_protobuf_aiagent_confighotload_v1_agent_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentBroadcastReply.ProtoReflect.Descriptor instead.
func (*AgentBroadcastReply) Descriptor() ([]byte, []int) {
	return file_manifest_protobuf_aiagent_confighotload_v1_agent_proto_rawDescGZIP(), []int{9}
}

func (x *AgentBroadcastReply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *AgentBroadcastReply) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// WebrtcBroadcastRequest WebRTC广播请求。
type AgentBroadcastRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 请求唯一ID，便于链路追踪
	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// 来源服务标识（通常为HTTP服务）
	AgentId string `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// 操作类型
	Action    string `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	GatewayId int64  `protobuf:"varint,4,opt,name=gatewayId,proto3" json:"gatewayId,omitempty"`
	Username  string `protobuf:"bytes,5,opt,name=username,proto3" json:"username,omitempty"`
	Password  string `protobuf:"bytes,6,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *AgentBroadcastRequest) Reset() {
	*x = AgentBroadcastRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_manifest_protobuf_aiagent_confighotload_v1_agent_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AgentBroadcastRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentBroadcastRequest) ProtoMessage() {}

func (x *AgentBroadcastRequest) ProtoReflect() protoreflect.Message {
	mi := &file_manifest_protobuf_aiagent_confighotload_v1_agent_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentBroadcastRequest.ProtoReflect.Descriptor instead.
func (*AgentBroadcastRequest) Descriptor() ([]byte, []int) {
	return file_manifest_protobuf_aiagent_confighotload_v1_agent_proto_rawDescGZIP(), []int{10}
}

func (x *AgentBroadcastRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *AgentBroadcastRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentBroadcastRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *AgentBroadcastRequest) GetGatewayId() int64 {
	if x != nil {
		return x.GatewayId
	}
	return 0
}

func (x *AgentBroadcastRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AgentBroadcastRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

var File_manifest_protobuf_aiagent_confighotload_v1_agent_proto protoreflect.FileDescriptor

var file_manifest_protobuf_aiagent_confighotload_v1_agent_proto_rawDesc = []byte{
	0x0a, 0x36, 0x6d, 0x61, 0x6e, 0x69, 0x66, 0x65, 0x73, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x61, 0x69, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2f, 0x63, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x68, 0x6f, 0x74, 0x6c, 0x6f, 0x61, 0x64, 0x2f, 0x76, 0x31, 0x2f, 0x61, 0x67, 0x65,
	0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x1a,
	0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x0f, 0x0a, 0x0d, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x67, 0x51, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x38, 0x0a, 0x10, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x67, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x48, 0x0a, 0x11, 0x41,
	0x67, 0x65, 0x6e, 0x74, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x52, 0x65, 0x71,
	0x12, 0x19, 0x0a, 0x08, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x07, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x48, 0x0a, 0x11, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x48, 0x65,
	0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x52, 0x65, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x22,
	0x48, 0x0a, 0x11, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x19,
	0x0a, 0x08, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x07, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x2d, 0x0a, 0x11, 0x41, 0x67, 0x65,
	0x6e, 0x74, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x73, 0x12, 0x18,
	0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x2e, 0x0a, 0x08, 0x41, 0x67, 0x65, 0x6e,
	0x74, 0x52, 0x65, 0x66, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x31, 0x0a, 0x11, 0x57, 0x61, 0x74, 0x63,
	0x68, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a,
	0x09, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x09, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x49, 0x64, 0x22, 0xe4, 0x01, 0x0a, 0x11,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x12, 0x21, 0x0a, 0x03, 0x72, 0x65, 0x66, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f,
	0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x66, 0x52,
	0x03, 0x72, 0x65, 0x66, 0x12, 0x1f, 0x0a, 0x0b, 0x6e, 0x65, 0x77, 0x5f, 0x76, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6e, 0x65, 0x77, 0x56, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x5f,
	0x68, 0x61, 0x73, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x48, 0x61, 0x73, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18,
	0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x38, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x22, 0x3b, 0x0a, 0x13, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x42, 0x72, 0x6f, 0x61, 0x64,
	0x63, 0x61, 0x73, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a,
	0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22,
	0xbf, 0x01, 0x0a, 0x15, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61,
	0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x67, 0x65, 0x6e,
	0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x67, 0x65, 0x6e,
	0x74, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x67,
	0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09,
	0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65,
	0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65,
	0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x64, 0x32, 0xfc, 0x02, 0x0a, 0x16, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x72,
	0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x46, 0x0a, 0x0e,
	0x41, 0x67, 0x65, 0x6e, 0x74, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x12, 0x18,
	0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x48, 0x65, 0x61, 0x72,
	0x74, 0x62, 0x65, 0x61, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x18, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74,
	0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x52,
	0x65, 0x73, 0x22, 0x00, 0x12, 0x46, 0x0a, 0x0e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x47, 0x65, 0x74,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x18, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x41,
	0x67, 0x65, 0x6e, 0x74, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x71,
	0x1a, 0x18, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x47, 0x65,
	0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x49, 0x0a, 0x11,
	0x57, 0x61, 0x74, 0x63, 0x68, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65,
	0x73, 0x12, 0x18, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x57, 0x61, 0x74, 0x63, 0x68, 0x41,
	0x67, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x61, 0x67,
	0x65, 0x6e, 0x74, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x30, 0x01, 0x12, 0x4a, 0x0a, 0x0e, 0x41, 0x67, 0x65, 0x6e, 0x74,
	0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x12, 0x1c, 0x2e, 0x61, 0x67, 0x65, 0x6e,
	0x74, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e,
	0x41, 0x67, 0x65, 0x6e, 0x74, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x3b, 0x0a, 0x08, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x67, 0x12,
	0x14, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x67,
	0x51, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x41, 0x67,
	0x65, 0x6e, 0x74, 0x52, 0x65, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x42, 0x12, 0x5a, 0x10, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x68, 0x6f, 0x74, 0x6c, 0x6f, 0x61,
	0x64, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_manifest_protobuf_aiagent_confighotload_v1_agent_proto_rawDescOnce sync.Once
	file_manifest_protobuf_aiagent_confighotload_v1_agent_proto_rawDescData = file_manifest_protobuf_aiagent_confighotload_v1_agent_proto_rawDesc
)

func file_manifest_protobuf_aiagent_confighotload_v1_agent_proto_rawDescGZIP() []byte {
	file_manifest_protobuf_aiagent_confighotload_v1_agent_proto_rawDescOnce.Do(func() {
		file_manifest_protobuf_aiagent_confighotload_v1_agent_proto_rawDescData = protoimpl.X.CompressGZIP(file_manifest_protobuf_aiagent_confighotload_v1_agent_proto_rawDescData)
	})
	return file_manifest_protobuf_aiagent_confighotload_v1_agent_proto_rawDescData
}

var file_manifest_protobuf_aiagent_confighotload_v1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_manifest_protobuf_aiagent_confighotload_v1_agent_proto_goTypes = []interface{}{
	(*AgentRegQuest)(nil),         // 0: agent.AgentRegQuest
	(*AgentRegResponse)(nil),      // 1: agent.AgentRegResponse
	(*AgentHeartbeatReq)(nil),     // 2: agent.AgentHeartbeatReq
	(*AgentHeartbeatRes)(nil),     // 3: agent.AgentHeartbeatRes
	(*AgentGetConfigReq)(nil),     // 4: agent.AgentGetConfigReq
	(*AgentGetConfigRes)(nil),     // 5: agent.AgentGetConfigRes
	(*AgentRef)(nil),              // 6: agent.AgentRef
	(*WatchAgentRequest)(nil),     // 7: agent.WatchAgentRequest
	(*ConfigChangeEvent)(nil),     // 8: agent.ConfigChangeEvent
	(*AgentBroadcastReply)(nil),   // 9: agent.AgentBroadcastReply
	(*AgentBroadcastRequest)(nil), // 10: agent.AgentBroadcastRequest
	(*timestamppb.Timestamp)(nil), // 11: google.protobuf.Timestamp
}
var file_manifest_protobuf_aiagent_confighotload_v1_agent_proto_depIdxs = []int32{
	6,  // 0: agent.ConfigChangeEvent.ref:type_name -> agent.AgentRef
	11, // 1: agent.ConfigChangeEvent.timestamp:type_name -> google.protobuf.Timestamp
	2,  // 2: agent.AgentControllerService.AgentHeartbeat:input_type -> agent.AgentHeartbeatReq
	4,  // 3: agent.AgentControllerService.AgentGetConfig:input_type -> agent.AgentGetConfigReq
	7,  // 4: agent.AgentControllerService.WatchAgentChanges:input_type -> agent.WatchAgentRequest
	10, // 5: agent.AgentControllerService.AgentBroadcast:input_type -> agent.AgentBroadcastRequest
	0,  // 6: agent.AgentControllerService.AgentReg:input_type -> agent.AgentRegQuest
	3,  // 7: agent.AgentControllerService.AgentHeartbeat:output_type -> agent.AgentHeartbeatRes
	5,  // 8: agent.AgentControllerService.AgentGetConfig:output_type -> agent.AgentGetConfigRes
	8,  // 9: agent.AgentControllerService.WatchAgentChanges:output_type -> agent.ConfigChangeEvent
	9,  // 10: agent.AgentControllerService.AgentBroadcast:output_type -> agent.AgentBroadcastReply
	1,  // 11: agent.AgentControllerService.AgentReg:output_type -> agent.AgentRegResponse
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_manifest_protobuf_aiagent_confighotload_v1_agent_proto_init() }
func file_manifest_protobuf_aiagent_confighotload_v1_agent_proto_init() {
	if File_manifest_protobuf_aiagent_confighotload_v1_agent_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_manifest_protobuf_aiagent_confighotload_v1_agent_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AgentRegQuest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_manifest_protobuf_aiagent_confighotload_v1_agent_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AgentRegResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_manifest_protobuf_aiagent_confighotload_v1_agent_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AgentHeartbeatReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_manifest_protobuf_aiagent_confighotload_v1_agent_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AgentHeartbeatRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_manifest_protobuf_aiagent_confighotload_v1_agent_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AgentGetConfigReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_manifest_protobuf_aiagent_confighotload_v1_agent_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AgentGetConfigRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_manifest_protobuf_aiagent_confighotload_v1_agent_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AgentRef); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_manifest_protobuf_aiagent_confighotload_v1_agent_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WatchAgentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_manifest_protobuf_aiagent_confighotload_v1_agent_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfigChangeEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_manifest_protobuf_aiagent_confighotload_v1_agent_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AgentBroadcastReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_manifest_protobuf_aiagent_confighotload_v1_agent_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AgentBroadcastRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_manifest_protobuf_aiagent_confighotload_v1_agent_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_manifest_protobuf_aiagent_confighotload_v1_agent_proto_goTypes,
		DependencyIndexes: file_manifest_protobuf_aiagent_confighotload_v1_agent_proto_depIdxs,
		MessageInfos:      file_manifest_protobuf_aiagent_confighotload_v1_agent_proto_msgTypes,
	}.Build()
	File_manifest_protobuf_aiagent_confighotload_v1_agent_proto = out.File
	file_manifest_protobuf_aiagent_confighotload_v1_agent_proto_rawDesc = nil
	file_manifest_protobuf_aiagent_confighotload_v1_agent_proto_goTypes = nil
	file_manifest_protobuf_aiagent_confighotload_v1_agent_proto_depIdxs = nil
}
