// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: manifest/protobuf/aiagent/confighotload/v1/agent.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	AgentControllerService_AgentHeartbeat_FullMethodName    = "/agent.AgentControllerService/AgentHeartbeat"
	AgentControllerService_AgentGetConfig_FullMethodName    = "/agent.AgentControllerService/AgentGetConfig"
	AgentControllerService_WatchAgentChanges_FullMethodName = "/agent.AgentControllerService/WatchAgentChanges"
	AgentControllerService_AgentBroadcast_FullMethodName    = "/agent.AgentControllerService/AgentBroadcast"
	AgentControllerService_AgentReg_FullMethodName          = "/agent.AgentControllerService/AgentReg"
)

// AgentControllerServiceClient is the client API for AgentControllerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentControllerServiceClient interface {
	// agent 心跳
	AgentHeartbeat(ctx context.Context, in *AgentHeartbeatReq, opts ...grpc.CallOption) (*AgentHeartbeatRes, error)
	// 获取配置
	AgentGetConfig(ctx context.Context, in *AgentGetConfigReq, opts ...grpc.CallOption) (*AgentGetConfigRes, error)
	// 双向流订阅变更
	WatchAgentChanges(ctx context.Context, in *WatchAgentRequest, opts ...grpc.CallOption) (AgentControllerService_WatchAgentChangesClient, error)
	// AgentBroadcast 接收广播请求并转发到下游节点。
	AgentBroadcast(ctx context.Context, in *AgentBroadcastRequest, opts ...grpc.CallOption) (*AgentBroadcastReply, error)
	// AgentReg 注册请求
	AgentReg(ctx context.Context, in *AgentRegQuest, opts ...grpc.CallOption) (*AgentRegResponse, error)
}

type agentControllerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentControllerServiceClient(cc grpc.ClientConnInterface) AgentControllerServiceClient {
	return &agentControllerServiceClient{cc}
}

func (c *agentControllerServiceClient) AgentHeartbeat(ctx context.Context, in *AgentHeartbeatReq, opts ...grpc.CallOption) (*AgentHeartbeatRes, error) {
	out := new(AgentHeartbeatRes)
	err := c.cc.Invoke(ctx, AgentControllerService_AgentHeartbeat_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentControllerServiceClient) AgentGetConfig(ctx context.Context, in *AgentGetConfigReq, opts ...grpc.CallOption) (*AgentGetConfigRes, error) {
	out := new(AgentGetConfigRes)
	err := c.cc.Invoke(ctx, AgentControllerService_AgentGetConfig_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentControllerServiceClient) WatchAgentChanges(ctx context.Context, in *WatchAgentRequest, opts ...grpc.CallOption) (AgentControllerService_WatchAgentChangesClient, error) {
	stream, err := c.cc.NewStream(ctx, &AgentControllerService_ServiceDesc.Streams[0], AgentControllerService_WatchAgentChanges_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &agentControllerServiceWatchAgentChangesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type AgentControllerService_WatchAgentChangesClient interface {
	Recv() (*ConfigChangeEvent, error)
	grpc.ClientStream
}

type agentControllerServiceWatchAgentChangesClient struct {
	grpc.ClientStream
}

func (x *agentControllerServiceWatchAgentChangesClient) Recv() (*ConfigChangeEvent, error) {
	m := new(ConfigChangeEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *agentControllerServiceClient) AgentBroadcast(ctx context.Context, in *AgentBroadcastRequest, opts ...grpc.CallOption) (*AgentBroadcastReply, error) {
	out := new(AgentBroadcastReply)
	err := c.cc.Invoke(ctx, AgentControllerService_AgentBroadcast_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentControllerServiceClient) AgentReg(ctx context.Context, in *AgentRegQuest, opts ...grpc.CallOption) (*AgentRegResponse, error) {
	out := new(AgentRegResponse)
	err := c.cc.Invoke(ctx, AgentControllerService_AgentReg_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentControllerServiceServer is the server API for AgentControllerService service.
// All implementations must embed UnimplementedAgentControllerServiceServer
// for forward compatibility
type AgentControllerServiceServer interface {
	// agent 心跳
	AgentHeartbeat(context.Context, *AgentHeartbeatReq) (*AgentHeartbeatRes, error)
	// 获取配置
	AgentGetConfig(context.Context, *AgentGetConfigReq) (*AgentGetConfigRes, error)
	// 双向流订阅变更
	WatchAgentChanges(*WatchAgentRequest, AgentControllerService_WatchAgentChangesServer) error
	// AgentBroadcast 接收广播请求并转发到下游节点。
	AgentBroadcast(context.Context, *AgentBroadcastRequest) (*AgentBroadcastReply, error)
	// AgentReg 注册请求
	AgentReg(context.Context, *AgentRegQuest) (*AgentRegResponse, error)
	mustEmbedUnimplementedAgentControllerServiceServer()
}

// UnimplementedAgentControllerServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAgentControllerServiceServer struct {
}

func (UnimplementedAgentControllerServiceServer) AgentHeartbeat(context.Context, *AgentHeartbeatReq) (*AgentHeartbeatRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AgentHeartbeat not implemented")
}
func (UnimplementedAgentControllerServiceServer) AgentGetConfig(context.Context, *AgentGetConfigReq) (*AgentGetConfigRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AgentGetConfig not implemented")
}
func (UnimplementedAgentControllerServiceServer) WatchAgentChanges(*WatchAgentRequest, AgentControllerService_WatchAgentChangesServer) error {
	return status.Errorf(codes.Unimplemented, "method WatchAgentChanges not implemented")
}
func (UnimplementedAgentControllerServiceServer) AgentBroadcast(context.Context, *AgentBroadcastRequest) (*AgentBroadcastReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AgentBroadcast not implemented")
}
func (UnimplementedAgentControllerServiceServer) AgentReg(context.Context, *AgentRegQuest) (*AgentRegResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AgentReg not implemented")
}
func (UnimplementedAgentControllerServiceServer) mustEmbedUnimplementedAgentControllerServiceServer() {
}

// UnsafeAgentControllerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentControllerServiceServer will
// result in compilation errors.
type UnsafeAgentControllerServiceServer interface {
	mustEmbedUnimplementedAgentControllerServiceServer()
}

func RegisterAgentControllerServiceServer(s grpc.ServiceRegistrar, srv AgentControllerServiceServer) {
	s.RegisterService(&AgentControllerService_ServiceDesc, srv)
}

func _AgentControllerService_AgentHeartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentHeartbeatReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentControllerServiceServer).AgentHeartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentControllerService_AgentHeartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentControllerServiceServer).AgentHeartbeat(ctx, req.(*AgentHeartbeatReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentControllerService_AgentGetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentGetConfigReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentControllerServiceServer).AgentGetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentControllerService_AgentGetConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentControllerServiceServer).AgentGetConfig(ctx, req.(*AgentGetConfigReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentControllerService_WatchAgentChanges_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchAgentRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentControllerServiceServer).WatchAgentChanges(m, &agentControllerServiceWatchAgentChangesServer{stream})
}

type AgentControllerService_WatchAgentChangesServer interface {
	Send(*ConfigChangeEvent) error
	grpc.ServerStream
}

type agentControllerServiceWatchAgentChangesServer struct {
	grpc.ServerStream
}

func (x *agentControllerServiceWatchAgentChangesServer) Send(m *ConfigChangeEvent) error {
	return x.ServerStream.SendMsg(m)
}

func _AgentControllerService_AgentBroadcast_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentBroadcastRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentControllerServiceServer).AgentBroadcast(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentControllerService_AgentBroadcast_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentControllerServiceServer).AgentBroadcast(ctx, req.(*AgentBroadcastRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentControllerService_AgentReg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentRegQuest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentControllerServiceServer).AgentReg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentControllerService_AgentReg_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentControllerServiceServer).AgentReg(ctx, req.(*AgentRegQuest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentControllerService_ServiceDesc is the grpc.ServiceDesc for AgentControllerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentControllerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agent.AgentControllerService",
	HandlerType: (*AgentControllerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AgentHeartbeat",
			Handler:    _AgentControllerService_AgentHeartbeat_Handler,
		},
		{
			MethodName: "AgentGetConfig",
			Handler:    _AgentControllerService_AgentGetConfig_Handler,
		},
		{
			MethodName: "AgentBroadcast",
			Handler:    _AgentControllerService_AgentBroadcast_Handler,
		},
		{
			MethodName: "AgentReg",
			Handler:    _AgentControllerService_AgentReg_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchAgentChanges",
			Handler:       _AgentControllerService_WatchAgentChanges_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "manifest/protobuf/aiagent/confighotload/v1/agent.proto",
}
