// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire gen -tags "ai shop iot erp"
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
	"nova-factory-server/app/business/admin"
	"nova-factory-server/app/business/admin/monitor/monitorController"
	"nova-factory-server/app/business/admin/monitor/monitorDao/monitorDaoImpl"
	"nova-factory-server/app/business/admin/monitor/monitorService/monitorServiceImpl"
	"nova-factory-server/app/business/admin/product/productController"
	"nova-factory-server/app/business/admin/product/productDao/productDaoImpl"
	"nova-factory-server/app/business/admin/product/productService/productServiceImpl"
	"nova-factory-server/app/business/admin/system/systemController"
	"nova-factory-server/app/business/admin/system/systemDao/systemDaoImpl"
	"nova-factory-server/app/business/admin/system/systemService/systemServiceImpl"
	"nova-factory-server/app/business/admin/tool/toolController"
	"nova-factory-server/app/business/admin/tool/toolDao/toolDaoImpl"
	"nova-factory-server/app/business/admin/tool/toolService/toolServiceImpl"
	"nova-factory-server/app/business/ai"
	"nova-factory-server/app/business/ai/agent/aiDataSetController"
	"nova-factory-server/app/business/ai/agent/aiDataSetDao/aiDataSetDaoImpl"
	"nova-factory-server/app/business/ai/agent/aiDataSetService/aiDataSetServiceImpl"
	"nova-factory-server/app/business/erp"
	"nova-factory-server/app/business/erp/setting/settingController"
	"nova-factory-server/app/business/erp/setting/settingDao/settingDaoImpl"
	"nova-factory-server/app/business/erp/setting/settingService/settingServiceImpl"
	"nova-factory-server/app/business/iot"
	"nova-factory-server/app/business/iot/alert/alertController"
	"nova-factory-server/app/business/iot/alert/alertDao/alertDaoImpl"
	"nova-factory-server/app/business/iot/alert/alertService/alertServiceImpl"
	"nova-factory-server/app/business/iot/asset/building/buildingController"
	"nova-factory-server/app/business/iot/asset/building/buildingDao/buildingDaoImpl"
	"nova-factory-server/app/business/iot/asset/building/buildingService/buildingServiceImpl"
	"nova-factory-server/app/business/iot/asset/camera/cameraController"
	"nova-factory-server/app/business/iot/asset/camera/cameraDao/cameraDaoImpl"
	"nova-factory-server/app/business/iot/asset/camera/cameraService/cameraServiceImpl"
	"nova-factory-server/app/business/iot/asset/device/deviceController"
	"nova-factory-server/app/business/iot/asset/device/deviceDao/deviceDaoImpl"
	"nova-factory-server/app/business/iot/asset/device/deviceService/deviceServiceImpl"
	"nova-factory-server/app/business/iot/asset/material/materialController"
	"nova-factory-server/app/business/iot/asset/material/materialDao/materialDaoImpl"
	"nova-factory-server/app/business/iot/asset/material/materialService/materialServiceImpl"
	"nova-factory-server/app/business/iot/asset/resource/resourceController"
	"nova-factory-server/app/business/iot/asset/resource/resourceDao/resourceDaoImpl"
	"nova-factory-server/app/business/iot/asset/resource/resourceService/resourceServiceImpl"
	"nova-factory-server/app/business/iot/configuration/configurationController"
	"nova-factory-server/app/business/iot/configuration/configurationDao/configurationDaoImpl"
	"nova-factory-server/app/business/iot/configuration/configurationService/configurationServiceImpl"
	"nova-factory-server/app/business/iot/craft/craftRouteController"
	"nova-factory-server/app/business/iot/craft/craftRouteDao/craftRouteDaoImpl"
	"nova-factory-server/app/business/iot/craft/craftRouteService/craftRouteServiceImpl"
	"nova-factory-server/app/business/iot/daemonize/daemonizeController"
	"nova-factory-server/app/business/iot/daemonize/daemonizeDao/daemonizeDaoImpl"
	"nova-factory-server/app/business/iot/daemonize/daemonizeService/daemonizeServiceImpl"
	"nova-factory-server/app/business/iot/dashboard/dashboardController"
	"nova-factory-server/app/business/iot/dashboard/dashboardDao/dashboardDaoImpl"
	"nova-factory-server/app/business/iot/dashboard/dashboardService/dashboardServiceImpl"
	"nova-factory-server/app/business/iot/deviceMonitor/deviceMonitorController"
	"nova-factory-server/app/business/iot/deviceMonitor/deviceMonitorDao/deviceMonitorDaoImpl"
	"nova-factory-server/app/business/iot/deviceMonitor/deviceMonitorService/deviceMonitorServiceImpl"
	"nova-factory-server/app/business/iot/home/controller"
	"nova-factory-server/app/business/iot/home/homeService/homeServiceImpl"
	"nova-factory-server/app/business/iot/metric/device/metricController"
	"nova-factory-server/app/business/iot/metric/device/metricDao/metricDaoIMpl"
	"nova-factory-server/app/business/iot/metric/device/metricService/metricServiceImpl"
	controller2 "nova-factory-server/app/business/iot/system/controller"
	systemDaoImpl2 "nova-factory-server/app/business/iot/system/dao/systemDaoImpl"
	systemServiceImpl2 "nova-factory-server/app/business/iot/system/service/systemServiceImpl"
	"nova-factory-server/app/business/shop"
	"nova-factory-server/app/business/shop/shopController"
	"nova-factory-server/app/business/shop/shopDao/shopDaoImpl"
	"nova-factory-server/app/business/shop/shopService/shopServiceImpl"
	"nova-factory-server/app/datasource/cache"
	"nova-factory-server/app/datasource/clickhouse"
	"nova-factory-server/app/datasource/iotdb"
	"nova-factory-server/app/datasource/mysql"
	"nova-factory-server/app/datasource/objectFile"
	"nova-factory-server/app/routes"
)

// Injectors from wire.go:

func wireApp() (*gin.Engine, func(), error) {
	app := routes.NewGinApp()
	cacheCache := cache.NewCache()
	sqlyContext, cleanup, err := mysql.NewData()
	if err != nil {
		return nil, nil, err
	}
	iUserDao := systemDaoImpl.NewSysUserDao(sqlyContext)
	iPermissionDao := systemDaoImpl.NewSysPermissionDao(sqlyContext)
	iRoleDao := systemDaoImpl.NewSysRoleDao(sqlyContext)
	iLogininforDao := monitorDaoImpl.NewLogininforDao(sqlyContext)
	iConfigDao := systemDaoImpl.NewSysConfigDao(sqlyContext)
	iConfigService := systemServiceImpl.NewConfigService(iConfigDao, cacheCache)
	iLoginService := systemServiceImpl.NewLoginService(cacheCache, iUserDao, iPermissionDao, iRoleDao, iLogininforDao, iConfigService)
	iUserPostDao := systemDaoImpl.NewSysUserPostDao(sqlyContext)
	iUserRoleDao := systemDaoImpl.NewSysUserRoleDao(sqlyContext)
	objectFileObjectFile := objectFile.NewConfig()
	iDeptDao := systemDaoImpl.NewSysDeptDao(sqlyContext)
	iPostDao := systemDaoImpl.NewSysPostDao(sqlyContext)
	iUserDeptScopeDao := systemDaoImpl.NewSysUserDeptScopeDao(sqlyContext)
	iUserService := systemServiceImpl.NewUserService(sqlyContext, iUserDao, iUserPostDao, iUserRoleDao, objectFileObjectFile, iDeptDao, iRoleDao, iPostDao, iUserDeptScopeDao, iConfigService)
	iLogininforService := monitorServiceImpl.NewLogininforService(iLogininforDao)
	login := systemController.NewLogin(iLoginService, iUserService, iConfigService, iLogininforService)
	iPostService := systemServiceImpl.NewPostService(iPostDao)
	iRolePermissionDao := systemDaoImpl.NewSysRolePermissionDao(sqlyContext)
	iRoleService := systemServiceImpl.NewRoleService(sqlyContext, iRoleDao, iRolePermissionDao, iUserRoleDao)
	user := systemController.NewUser(iUserService, iPostService, iRoleService)
	iDeptService := systemServiceImpl.NewDeptService(iDeptDao, iRoleDao)
	dept := systemController.NewDept(iDeptService)
	iDictTypeDao := systemDaoImpl.NewSysDictTypeDao(sqlyContext)
	iDictTypeService := systemServiceImpl.NewDictTypeService(iDictTypeDao, cacheCache)
	iDictDataDao := systemDaoImpl.NewSysDictDataDao(sqlyContext)
	iDictDataService := systemServiceImpl.NewDictDataService(iDictDataDao, cacheCache)
	dictType := systemController.NewDictType(iDictTypeService, iDictDataService)
	dictData := systemController.NewDictData(iDictDataService)
	role := systemController.NewRole(iRoleService)
	post := systemController.NewPost(iPostService)
	profile := systemController.NewProfile(iUserService)
	config := systemController.NewConfig(iConfigService)
	iFileService := systemServiceImpl.NewFileService(objectFileObjectFile)
	file := systemController.NewFile(iFileService)
	iSseService := systemServiceImpl.NewSseService(cacheCache)
	sse := systemController.NewSse(iSseService)
	iSysNoticeDao := systemDaoImpl.NewSysNoticeDao(sqlyContext)
	iSysNoticeService := systemServiceImpl.NewNoticeService(iSysNoticeDao, iUserDao, iSseService)
	notice := systemController.NewNotice(iSysNoticeService)
	iSysPermissionService := systemServiceImpl.NewPermissionService(iPermissionDao)
	permission := systemController.NewPermission(iSysPermissionService)
	iSelectBoxService := systemServiceImpl.NewSelectService(iPermissionDao, iDeptDao)
	selectBox := systemController.NewSelectBox(iSelectBoxService)
	db := mysql.NewDB()
	iSysShiftDao := systemDaoImpl.NewISysShiftDaoImpl(db)
	iSysShiftService := systemServiceImpl.NewISysShiftServiceImpl(iSysShiftDao)
	shift := systemController.NewShift(iSysShiftService)
	system := &systemController.System{
		Login:      login,
		User:       user,
		Dept:       dept,
		DictType:   dictType,
		DictData:   dictData,
		Role:       role,
		Post:       post,
		Profile:    profile,
		Config:     config,
		File:       file,
		Sse:        sse,
		Notice:     notice,
		Permission: permission,
		SelectBox:  selectBox,
		Shift:      shift,
	}
	infoServer := monitorController.NewInfoServer()
	iUserOnlineService := monitorServiceImpl.NewUserOnlineService(cacheCache)
	userOnline := monitorController.NewUserOnline(iUserOnlineService)
	logininfor := monitorController.NewLogininfor(iLogininforService)
	iOperLog := monitorDaoImpl.NewOperLog(sqlyContext)
	iSysOperLogService := monitorServiceImpl.NewOperLog(iOperLog)
	operLog := monitorController.NewOperLog(iSysOperLogService)
	iJobDao := monitorDaoImpl.NewJobDao(sqlyContext)
	iJobService := monitorServiceImpl.NewJobService(cacheCache, iJobDao)
	job := monitorController.NewJob(iJobService)
	monitor := &monitorController.Monitor{
		Server:     infoServer,
		UserOnline: userOnline,
		Logfor:     logininfor,
		Oper:       operLog,
		Job:        job,
	}
	iGenTableColumn := toolDaoImpl.NewGenTableColumnDao(sqlyContext)
	iGenTable := toolDaoImpl.GetGenTableDao(sqlyContext)
	iGenTableService := toolServiceImpl.NewGenTabletService(iGenTableColumn, iGenTable)
	genTable := toolController.NewGenTable(iGenTableService)
	tool := &toolController.Tool{
		GenTable: genTable,
	}
	iSysProductLaboratoryDao := productDaoImpl.NewSysProductLaboratoryDao(db)
	iSysProductLaboratoryService := productServiceImpl.NewSysProductLaboratoryService(iSysProductLaboratoryDao, iUserDao)
	laboratory := productController.NewLaboratory(iSysProductLaboratoryService, iDictDataService)
	product := &productController.Product{
		Laboratory: laboratory,
	}
	adminAdmin := admin.NewGinEngine(app, cacheCache, system, monitor, tool, product)
	iotDb := iotdb.NewIotDb()
	iMaterialDao := materialDaoImpl.NewMaterialDaoImpl(db)
	iMaterialService := materialServiceImpl.NewMaterialService(iMaterialDao, iUserDao)
	materialInfo := materialController.NewMaterialInfo(iMaterialService)
	material := &materialController.Material{
		Material: materialInfo,
	}
	iCraftRouteDao := craftRouteDaoImpl.NewCraftRouteDaoImpl(db)
	iProcessDao := craftRouteDaoImpl.NewIProcessDaoImpl(db)
	iRouteProcessDao := craftRouteDaoImpl.NewIProcessRouteDaoImpl(db)
	iProcessContextDao := craftRouteDaoImpl.NewProcessContextDaoImpl(db)
	iSysCraftRouteConfigDao := craftRouteDaoImpl.NewISysCraftRouteConfigDaoImpl(db)
	iCraftRouteService := craftRouteServiceImpl.NewCraftRouteServiceImpl(iCraftRouteDao, iProcessDao, iRouteProcessDao, iProcessContextDao, iSysCraftRouteConfigDao)
	craft := craftRouteController.NewCraft(iCraftRouteService)
	iCraftProcessService := craftRouteServiceImpl.NewICraftProcessServiceImpl(iProcessDao, iUserDao)
	process := craftRouteController.NewProcess(iCraftProcessService)
	iCraftProcessContextService := craftRouteServiceImpl.NewICraftProcessContextServiceImpl(iProcessContextDao, iUserDao)
	processContext := craftRouteController.NewProcessContext(iCraftProcessContextService)
	iProcessRouteService := craftRouteServiceImpl.NewIProcessRouteServiceImpl(iRouteProcessDao, iProcessDao, iCraftRouteDao)
	routeProcess := craftRouteController.NewSysProRouteProcess(iProcessRouteService)
	iScheduleDao := craftRouteDaoImpl.NewIScheduleDaoImpl(db)
	iScheduleMapDao := craftRouteDaoImpl.NewIScheduleMapDaoImpl(db)
	iScheduleService := craftRouteServiceImpl.NewIScheduleServiceImpl(iScheduleDao, db, iScheduleMapDao, iCraftRouteDao, iSysCraftRouteConfigDao)
	iotAgentDao := daemonizeDaoImpl.NewIotAgentDaoImpl(db, cacheCache)
	iotAgentProcess := daemonizeDaoImpl.NewIotAgentProcessDaoImpl(cacheCache)
	iotAgentService := daemonizeServiceImpl.NewIotAgentServiceImpl(iotAgentDao, iotAgentProcess)
	schedule := craftRouteController.NewSchedule(iScheduleService, iotAgentService)
	craftRoute := &craftRouteController.CraftRoute{
		CraftRoute:     craft,
		Process:        process,
		ProcessContext: processContext,
		RouteProcess:   routeProcess,
		Schedule:       schedule,
	}
	clickHouse, err := clickhouse.NewClickHouse()
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	iMetricDao := metricDaoIMpl.NewMetricDaoImpl(clickHouse, iotDb)
	iMetricService := metricServiceImpl.NewIMetricServiceImpl(iMetricDao, cacheCache)
	iControlLogDao := metricDaoIMpl.NewIControlLogDaoImpl(clickHouse)
	iControlLogService := metricServiceImpl.NewIControlLogServiceImpl(iControlLogDao)
	metric := metricController.NewMetric(iMetricService, iControlLogService)
	iCameraDao := cameraDaoImpl.NewCameraDao(db)
	iCameraService := metricServiceImpl.NewICameraServiceImpl(cacheCache, iCameraDao)
	cameraGrpc := metricController.NewCamera(iCameraService)
	metricServer := &metricController.MetricServer{
		Metric:     metric,
		CameraGrpc: cameraGrpc,
	}
	iotAgentConfigDao := daemonizeDaoImpl.NewIotAgentConfigDaoImpl(db)
	daemonizeService := daemonizeServiceImpl.NewDaemonizeServiceImpl(iotAgentDao, iotAgentProcess, iotAgentConfigDao)
	daemonize := daemonizeController.NewDaemonize(daemonizeService)
	iotAgent := daemonizeController.NewIotAgentController(iotAgentService, daemonizeService)
	iDeviceDao := deviceDaoImpl.NewSysDeviceDaoImpl(db)
	iDeviceTemplateDao := deviceDaoImpl.NewIDeviceTemplateDaoImpl(db)
	iSysModbusDeviceConfigDataDao := deviceDaoImpl.NewISysModbusDeviceConfigDataDaoImp(db)
	alertRuleDao := alertDaoImpl.NewAlertRuleDaoImpl(db)
	alertSinkTemplateDao := alertDaoImpl.NewAlertSinkTemplateDaoImpl(db)
	iDeviceElectricDao := systemDaoImpl2.NewIDeviceElectricDaoImpl(db)
	iAiPredictionControlDao := aiDataSetDaoImpl.NewIAiPredictionControlDaoImpl(db)
	iGatewayConfigService := daemonizeServiceImpl.NewIGatewayConfigServiceImpl(iDeviceDao, iDeviceTemplateDao, iSysModbusDeviceConfigDataDao, alertRuleDao, alertSinkTemplateDao, iDeviceElectricDao, iDictDataDao, iAiPredictionControlDao)
	iotAgentConfigService := daemonizeServiceImpl.NewIotAgentConfigServiceImpl(iotAgentConfigDao)
	daemonizeControllerConfig := daemonizeController.NewConfig(iGatewayConfigService, iotAgentConfigService, iotAgentService)
	daemonizeServer := &daemonizeController.DaemonizeServer{
		Daemonize: daemonize,
		IotAgent:  iotAgent,
		Config:    daemonizeControllerConfig,
	}
	floorDao := buildingDaoImpl.NewFloorDaoImpl(db)
	iDeviceGroupDao := deviceDaoImpl.NewSysDeviceGroupDaoImpl(db)
	iDeviceDataReportDao := deviceMonitorDaoImpl.NewIDeviceDataReportDaoImpl(db)
	iDeviceService := deviceServiceImpl.NewDeviceService(iDeviceDao, iDeviceGroupDao, iUserDao, iMetricDao, iSysModbusDeviceConfigDataDao, iDeviceDataReportDao, cacheCache)
	deviceControlService := deviceMonitorServiceImpl.NewDeviceControlServiceImpl(iotAgentDao, cacheCache, iControlLogDao, iDeviceDao, iSysModbusDeviceConfigDataDao)
	buildingDao := buildingDaoImpl.NewBuildingDaoImpl(db)
	deviceMonitorService := deviceMonitorServiceImpl.NewDeviceMonitorServiceImpl(iDeviceDao, cacheCache, iMetricDao, iSysModbusDeviceConfigDataDao, floorDao, iDeviceService, deviceControlService, iControlLogDao, buildingDao)
	deviceMonitorControllerCameraGrpc := deviceMonitorController.NewCameraGrpc(iotAgentService)
	deviceMonitor := deviceMonitorController.NewDeviceMonitor(deviceMonitorService, deviceMonitorControllerCameraGrpc)
	iDeviceDataReportService := deviceMonitorServiceImpl.NewIDeviceDataReportServiceImpl(iDeviceDataReportDao, iDeviceDao)
	iDevMapService := metricServiceImpl.NewIDevMapServiceImpl(iDeviceDataReportDao, iDeviceDao)
	deviceReport := deviceMonitorController.NewDeviceReport(iMetricService, iDeviceDataReportService, iDevMapService)
	deviceUtilizationDao := deviceMonitorDaoImpl.NewDeviceUtilizationDaoImpl(iotDb, iSysShiftDao, iDeviceDao, buildingDao, iMetricDao, iDictDataDao)
	deviceUtilizationService := deviceMonitorServiceImpl.NewDeviceUtilizationServiceImpl(deviceUtilizationDao)
	deviceUtilization := deviceMonitorController.NewDeviceUtilization(deviceUtilizationService)
	controlLogService := deviceMonitorServiceImpl.NewControlLogServiceImpl(iControlLogDao, iDeviceDao, iSysModbusDeviceConfigDataDao)
	controlLog := deviceMonitorController.NewControlLog(controlLogService)
	deviceControl := deviceMonitorController.NewDeviceControl(deviceControlService)
	deviceMonitorControllerDeviceMonitorController := &deviceMonitorController.DeviceMonitorController{
		DeviceMonitor:     deviceMonitor,
		DeviceReport:      deviceReport,
		DeviceUtilization: deviceUtilization,
		ControlLog:        controlLog,
		DeviceControl:     deviceControl,
		CameraGrpc:        deviceMonitorControllerCameraGrpc,
	}
	alertActionDao := alertDaoImpl.NewAlertActionDaoImpl(db)
	alertAiReasonDao := alertDaoImpl.NewAlertAiReasonDaoImpl(db)
	alertRuleService := alertServiceImpl.NewAlertRuleServiceImpl(alertRuleDao, iotAgentDao, alertSinkTemplateDao, alertActionDao, alertAiReasonDao)
	alert := alertController.NewAlert(alertRuleService)
	alertTemplateService := alertServiceImpl.NewAlertTemplateServiceImpl(alertSinkTemplateDao)
	alertTemplate := alertController.NewAlertTemplate(alertTemplateService)
	alertLogClickhouseDao := alertDaoImpl.NewAlertLogClickhouseDaoImpl(clickHouse, iotAgentDao)
	alertLogService := alertServiceImpl.NewAlertLogServiceImpl(alertLogClickhouseDao, alertRuleDao, iotAgentDao, iDeviceDao, buildingDao, iSysModbusDeviceConfigDataDao)
	alertLog := alertController.NewAlertLog(alertLogService)
	alertActionService := alertServiceImpl.NewAlertActionServiceImpl(alertActionDao)
	alertAction := alertController.NewAlertAction(alertActionService, iDictDataService)
	alertAiReasonService := alertServiceImpl.NewAlertAiReasonServiceImpl(alertAiReasonDao)
	alertAiReason := alertController.NewAlertAiReason(alertAiReasonService)
	client := aiDataSetServiceImpl.NewHttpClient()
	iChartService := aiDataSetServiceImpl.NewIChartServiceImpl(client)
	runnerService := alertServiceImpl.NewRunnerServiceImpl(iChartService)
	alertLogDao := alertDaoImpl.NewAlertLogDaoImpl(db)
	runner := alertController.NewRunner(alertRuleService, runnerService, iChartService, iDeviceDao, alertLogDao)
	alertControllerController := &alertController.Controller{
		Alert:         alert,
		AlertTemplate: alertTemplate,
		AlertLog:      alertLog,
		AlertAction:   alertAction,
		AlertAiReason: alertAiReason,
		Runner:        runner,
	}
	buildingService := buildingServiceImpl.NewBuildingServiceImpl(buildingDao, floorDao)
	building := buildingController.NewBuilding(buildingService)
	floorService := buildingServiceImpl.NewFloorServiceImpl(floorDao)
	floor := buildingController.NewFloor(floorService)
	buildingControllerController := buildingController.Controller{
		Building: building,
		Floor:    floor,
	}
	dashboardDao := dashboardDaoImpl.NewDashboardDaoImpl(db)
	dashboardService := dashboardServiceImpl.NewDashboardServiceImpl(dashboardDao, iMetricDao)
	dashboard := dashboardController.NewDashboard(dashboardService)
	dashboardDataDao := dashboardDaoImpl.NewDashboardDataDaoImpl(db)
	dashboardDataService := dashboardServiceImpl.NewDashboardDataServiceImpl(dashboardDataDao)
	data := dashboardController.NewData(dashboardDataService)
	dashboardControllerController := dashboardController.Controller{
		Dashboard: dashboard,
		Data:      data,
	}
	iResourceFileDao := resourceDaoImpl.NewSysResourceFileDao(db)
	iResourceFileService := resourceServiceImpl.NewSysResourceFileService(iResourceFileDao)
	resourceFile := resourceController.NewResourceFile(iResourceFileService)
	resourceControllerResourceController := &resourceController.ResourceController{
		ResourceFile: resourceFile,
	}
	deviceMonitorCalcDao := deviceMonitorDaoImpl.NewDeviceMonitorCalcDaoImpl(iotDb, iDevMapService)
	homeService := homeServiceImpl.NewHomeServiceImpl(buildingDao, iDeviceService, iCraftRouteService, alertLogService, deviceMonitorCalcDao, cacheCache)
	home := controller.NewHome(homeService)
	configurationDao := configurationDaoImpl.NewConfigurationDaoImpl(db)
	configurationService := configurationServiceImpl.NewConfigurationServiceImpl(configurationDao)
	configuration := configurationController.NewConfiguration(configurationService)
	configurationControllerController := &configurationController.Controller{
		Configuration: configuration,
	}
	iDeviceElectricService := systemServiceImpl2.NewIDeviceElectricServiceImpl(iDeviceElectricDao, iDeviceDao, iMetricDao, iDeviceDataReportDao)
	electric := controller2.NewElectric(iDeviceElectricService, iDeviceService)
	controllerSystem := controller2.System{
		Electric: electric,
	}
	cameraServiceICameraService := cameraServiceImpl.NewCameraService(iCameraDao, cacheCache)
	camera := cameraController.NewCameraController(cameraServiceICameraService, iotAgentService)
	cameraControllerCameraController := cameraController.CameraController{
		Camera: camera,
	}
	deviceInfo := deviceController.NewDeviceInfo(iDeviceService)
	iDeviceGroupService := deviceServiceImpl.NewDeviceGroupService(iDeviceGroupDao, iUserDao)
	deviceGroup := deviceController.NewDeviceGroup(iDeviceGroupService)
	iDeviceTemplateService := deviceServiceImpl.NewDeviceTemplateServiceImpl(iDeviceTemplateDao, iSysModbusDeviceConfigDataDao)
	template, err := deviceController.NewTemplate(iDeviceTemplateService)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	iSysModbusDeviceConfigDataService := deviceServiceImpl.NewISysModbusDeviceConfigDataServiceImpl(iSysModbusDeviceConfigDataDao)
	templateData := deviceController.NewTemplateData(iSysModbusDeviceConfigDataService, iDeviceTemplateService, iDeviceService)
	iDeviceSubjectDao := deviceDaoImpl.NewIDeviceSubjectDaoImpl(db)
	iDeviceSubjectService := deviceServiceImpl.NewIDeviceSubjectServiceImpl(iDeviceSubjectDao)
	deviceSubject := deviceController.NewDeviceSubject(iDeviceSubjectService)
	iDeviceCheckPlanDao := deviceDaoImpl.NewIDeviceCheckPlanDaoImpl(db)
	iDeviceCheckPlanService := deviceServiceImpl.NewIDeviceCheckPlanServiceImpl(iDeviceCheckPlanDao)
	deviceCheckPlan := deviceController.NewDeviceCheckPlan(iDeviceCheckPlanService)
	iDeviceCheckMachineryDao := deviceDaoImpl.NewIDeviceCheckMachineryDaoImpl(db)
	iDeviceCheckMachineryService := deviceServiceImpl.NewIDeviceCheckMachineryServiceImpl(iDeviceCheckMachineryDao)
	deviceCheckMachinery := deviceController.NewDeviceCheckMachinery(iDeviceCheckMachineryService)
	iDeviceCheckSubjectDao := deviceDaoImpl.NewIDeviceCheckSubjectDaoImpl(db)
	iDeviceCheckSubjectService := deviceServiceImpl.NewIDeviceCheckSubjectServiceImpl(iDeviceCheckSubjectDao)
	deviceCheckSubject := deviceController.NewDeviceCheckSubject(iDeviceCheckSubjectService)
	device := &deviceController.Device{
		Info:                 deviceInfo,
		Group:                deviceGroup,
		Template:             template,
		TemplateData:         templateData,
		DeviceSubject:        deviceSubject,
		DeviceCheckPlan:      deviceCheckPlan,
		DeviceCheckMachinery: deviceCheckMachinery,
		DeviceCheckSubject:   deviceCheckSubject,
	}
	iotIot := iot.NewGinEngine(app, cacheCache, iotDb, material, craftRoute, metricServer, daemonizeServer, deviceMonitorControllerDeviceMonitorController, alertControllerController, buildingControllerController, dashboardControllerController, resourceControllerResourceController, home, configurationControllerController, controllerSystem, cameraControllerCameraController, device)
	iDataSetDao := aiDataSetDaoImpl.NewDataSetDaoImpl(db)
	iDataSetService := aiDataSetServiceImpl.NewIDataSetServiceImpl(iDataSetDao, iDeptDao, iUserDao, client)
	iDataSetDocumentDao := aiDataSetDaoImpl.NewIDataSetDocumentDaoImpl(db)
	iDataSetDocumentService := aiDataSetServiceImpl.NewIDataSetDocumentServiceImpl(client, iDataSetDao, iDataSetDocumentDao)
	iChunkService := aiDataSetServiceImpl.NewIChunkServiceImpl(client)
	iAssistantService := aiDataSetServiceImpl.NewIAssistantServiceImpl(client)
	dataset := aiDataSetController.NewDataset(iDataSetService, iDataSetDocumentService, iChunkService, iAssistantService, iChartService)
	iAiPredictionExceptionDao := aiDataSetDaoImpl.NewIAiPredictionExceptionDaoImpl(db)
	iAiPredictionExceptionService := aiDataSetServiceImpl.NewIAiPredictionExceptionServiceImpl(iAiPredictionExceptionDao)
	exception := aiDataSetController.NewException(iAiPredictionExceptionService)
	iAiPredictionListDao := aiDataSetDaoImpl.NewIAiPredictionListDaoImpl(db)
	iAiPredictionService := aiDataSetServiceImpl.NewIAiPredictionServiceImpl(iAiPredictionListDao)
	prediction := aiDataSetController.NewPrediction(iAiPredictionService)
	iAiPredictionControlService := aiDataSetServiceImpl.NewIAiPredictionControlServiceImpl(iAiPredictionControlDao)
	control := aiDataSetController.NewControl(iAiPredictionControlService)
	iAiLLMDao := aiDataSetDaoImpl.NewAiLLMDaoImpl(db)
	iAiModelProviderDao := aiDataSetDaoImpl.NewIAiModelProviderDaoImpl(db, iAiLLMDao)
	iAiModelProviderService := aiDataSetServiceImpl.NewIAiModelProviderServiceImpl(iAiModelProviderDao)
	model := aiDataSetController.NewModel(iAiModelProviderService)
	aiDataSet := &aiDataSetController.AiDataSet{
		Dataset:    dataset,
		Exception:  exception,
		Prediction: prediction,
		Control:    control,
		Model:      model,
	}
	factoryBootstrap := ai.NewFactoryBootstrap(db)
	aiAI := ai.NewGinEngine(app, cacheCache, aiDataSet, factoryBootstrap)
	iShopCategoryDao := shopDaoImpl.NewShopCategoryDao(db)
	iShopCategoryService := shopServiceImpl.NewShopCategoryService(iShopCategoryDao)
	category := shopController.NewCategory(iShopCategoryService)
	iShopGoodsDao := shopDaoImpl.NewShopGoodsDao(db)
	iShopGoodsService := shopServiceImpl.NewShopGoodsService(iShopGoodsDao)
	goods := shopController.NewGoods(iShopGoodsService)
	iShopSkuDao := shopDaoImpl.NewShopSkuDao(db)
	iShopSkuService := shopServiceImpl.NewShopSkuService(iShopSkuDao)
	sku := shopController.NewSku(iShopSkuService)
	iShopUserDao := shopDaoImpl.NewShopUserDao(db)
	iShopUserService := shopServiceImpl.NewShopUserService(iShopUserDao)
	shopControllerUser := shopController.NewUser(iShopUserService)
	shopControllerController := &shopController.Controller{
		Category: category,
		Goods:    goods,
		Sku:      sku,
		User:     shopControllerUser,
	}
	shopShop := shop.NewGinEngine(app, cacheCache, shopControllerController)
	iAgentConfigDao := settingDaoImpl.NewAgentConfigDao(db)
	iAgentConfigService := settingServiceImpl.NewAgentConfigService(iAgentConfigDao)
	agentConfig := settingController.NewAgentConfig(iAgentConfigService)
	settingControllerController := &settingController.Controller{
		AgentConfig: agentConfig,
	}
	erpErp := erp.NewGinEngine(app, cacheCache, settingControllerController)
	engine := finalEngine(app, adminAdmin, iotIot, aiAI, shopShop, erpErp)
	return engine, func() {
		cleanup()
	}, nil
}

// wire.go:

func finalEngine(app *routes.App, _ *admin.Admin, _ *iot.Iot, _ *ai.AI, _ *shop.Shop, _ *erp.Erp) *gin.Engine {
	return app.Engine
}
