// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"nova-factory-server/dao/model"
)

func newShopOrder(db *gorm.DB, opts ...gen.DOOption) shopOrder {
	_shopOrder := shopOrder{}

	_shopOrder.shopOrderDo.UseDB(db, opts...)
	_shopOrder.shopOrderDo.UseModel(&model.ShopOrder{})

	tableName := _shopOrder.shopOrderDo.TableName()
	_shopOrder.ALL = field.NewAsterisk(tableName)
	_shopOrder.ID = field.NewInt64(tableName, "id")
	_shopOrder.Tid = field.NewString(tableName, "tid")
	_shopOrder.UserID = field.NewInt64(tableName, "user_id")
	_shopOrder.Weight = field.NewFloat64(tableName, "weight")
	_shopOrder.Size = field.NewFloat64(tableName, "size")
	_shopOrder.BuyerNick = field.NewString(tableName, "buyer_nick")
	_shopOrder.BuyerMessage = field.NewString(tableName, "buyer_message")
	_shopOrder.SellerMemo = field.NewString(tableName, "seller_memo")
	_shopOrder.Total = field.NewFloat64(tableName, "total")
	_shopOrder.Privilege = field.NewFloat64(tableName, "privilege")
	_shopOrder.PostFee = field.NewFloat64(tableName, "post_fee")
	_shopOrder.ReceiverName = field.NewString(tableName, "receiver_name")
	_shopOrder.ReceiverProvince = field.NewString(tableName, "receiver_province")
	_shopOrder.ReceiverProvinceName = field.NewString(tableName, "receiver_province_name")
	_shopOrder.ReceiverCity = field.NewString(tableName, "receiver_city")
	_shopOrder.ReceiverCityName = field.NewString(tableName, "receiver_city_name")
	_shopOrder.ReceiverDistrict = field.NewString(tableName, "receiver_district")
	_shopOrder.ReceiverDistrictName = field.NewString(tableName, "receiver_district_name")
	_shopOrder.ReceiverStreet = field.NewString(tableName, "receiver_street")
	_shopOrder.ReceiverStreetName = field.NewString(tableName, "receiver_street_name")
	_shopOrder.ReceiverAddress = field.NewString(tableName, "receiver_address")
	_shopOrder.ReceiverPhone = field.NewString(tableName, "receiver_phone")
	_shopOrder.ReceiverMobile = field.NewString(tableName, "receiver_mobile")
	_shopOrder.ReceiverZip = field.NewString(tableName, "receiver_zip")
	_shopOrder.Status = field.NewString(tableName, "status")
	_shopOrder.OrderType = field.NewString(tableName, "order_type")
	_shopOrder.InvoiceName = field.NewString(tableName, "invoice_name")
	_shopOrder.SellerFlag = field.NewString(tableName, "seller_flag")
	_shopOrder.PayTime = field.NewTime(tableName, "pay_time")
	_shopOrder.LogistBTypeCode = field.NewString(tableName, "logist_b_type_code")
	_shopOrder.LogistBillCode = field.NewString(tableName, "logist_bill_code")
	_shopOrder.BTypeCode = field.NewString(tableName, "b_type_code")
	_shopOrder.DetailsJSON = field.NewString(tableName, "details_json")
	_shopOrder.AccountsJSON = field.NewString(tableName, "accounts_json")
	_shopOrder.TransactionID = field.NewString(tableName, "transaction_id")
	_shopOrder.NotifyRaw = field.NewString(tableName, "notify_raw")
	_shopOrder.MchID = field.NewString(tableName, "mch_id")
	_shopOrder.Appid = field.NewString(tableName, "appid")
	_shopOrder.PayerOpenid = field.NewString(tableName, "payer_openid")
	_shopOrder.PayChannel = field.NewInt32(tableName, "pay_channel")
	_shopOrder.BillCode = field.NewString(tableName, "bill_code")
	_shopOrder.SyncMessage = field.NewString(tableName, "sync_message")
	_shopOrder.SyncStatus = field.NewInt32(tableName, "sync_status")
	_shopOrder.SyncTime = field.NewTime(tableName, "sync_time")
	_shopOrder.DeptID = field.NewInt64(tableName, "dept_id")
	_shopOrder.CreateBy = field.NewInt64(tableName, "create_by")
	_shopOrder.CreateTime = field.NewTime(tableName, "create_time")
	_shopOrder.UpdateBy = field.NewInt64(tableName, "update_by")
	_shopOrder.UpdateTime = field.NewTime(tableName, "update_time")
	_shopOrder.State = field.NewBool(tableName, "state")

	_shopOrder.fillFieldMap()

	return _shopOrder
}

// shopOrder ERP订单主表
type shopOrder struct {
	shopOrderDo shopOrderDo

	ALL                  field.Asterisk
	ID                   field.Int64   // 主键ID
	Tid                  field.String  // 网店订单编号
	UserID               field.Int64   // 用户id
	Weight               field.Float64 // 订单重量
	Size                 field.Float64 // 订单尺寸/体积
	BuyerNick            field.String  // 买家账号
	BuyerMessage         field.String  // 买家留言
	SellerMemo           field.String  // 卖家备注
	Total                field.Float64 // 订单总金额（含运费）
	Privilege            field.Float64 // 订单优惠金额
	PostFee              field.Float64 // 运费
	ReceiverName         field.String  // 收货人名称
	ReceiverProvince     field.String  // 收货省编码
	ReceiverProvinceName field.String  // 收货省名称
	ReceiverCity         field.String  // 收货市编码
	ReceiverCityName     field.String  // 收货市名称
	ReceiverDistrict     field.String  // 收货区编码
	ReceiverDistrictName field.String  // 收货区名称
	ReceiverStreet       field.String  // 收货街道编码
	ReceiverStreetName   field.String  // 收货街道名称
	ReceiverAddress      field.String  // 收货详细地址
	ReceiverPhone        field.String  // 收货电话
	ReceiverMobile       field.String  // 收货人手机号
	ReceiverZip          field.String  // 邮编
	Status               field.String  // 订单状态
	OrderType            field.String  // 订单类型（Cod/NoCod）
	InvoiceName          field.String  // 发票抬头
	SellerFlag           field.String  // 卖家旗帜
	PayTime              field.Time    // 付款时间
	LogistBTypeCode      field.String  // 物流公司编码
	LogistBillCode       field.String  // 物流单号
	BTypeCode            field.String  // 往来单位编码
	DetailsJSON          field.String  // 订单商品明细JSON
	AccountsJSON         field.String  // 订单账户信息JSON
	TransactionID        field.String  // 微信支付交易单号
	NotifyRaw            field.String  // 微信支付回调原文
	MchID                field.String  // 微信商户号
	Appid                field.String  // 小程序AppID
	PayerOpenid          field.String  // 支付用户openid
	PayChannel           field.Int32   // 支付通道：0未知 1微信 2支付宝
	BillCode             field.String  // 管家婆返回订单编号
	SyncMessage          field.String  // 同步结果描述
	SyncStatus           field.Int32   // 同步状态：0待同步 1成功 2失败
	SyncTime             field.Time    // 同步时间
	DeptID               field.Int64   // 部门ID
	CreateBy             field.Int64   // 创建者
	CreateTime           field.Time    // 创建时间
	UpdateBy             field.Int64   // 更新者
	UpdateTime           field.Time    // 更新时间
	State                field.Bool    // 操作状态（0正常 -1删除）

	fieldMap map[string]field.Expr
}

func (s shopOrder) Table(newTableName string) *shopOrder {
	s.shopOrderDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s shopOrder) As(alias string) *shopOrder {
	s.shopOrderDo.DO = *(s.shopOrderDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *shopOrder) updateTableName(table string) *shopOrder {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewInt64(table, "id")
	s.Tid = field.NewString(table, "tid")
	s.UserID = field.NewInt64(table, "user_id")
	s.Weight = field.NewFloat64(table, "weight")
	s.Size = field.NewFloat64(table, "size")
	s.BuyerNick = field.NewString(table, "buyer_nick")
	s.BuyerMessage = field.NewString(table, "buyer_message")
	s.SellerMemo = field.NewString(table, "seller_memo")
	s.Total = field.NewFloat64(table, "total")
	s.Privilege = field.NewFloat64(table, "privilege")
	s.PostFee = field.NewFloat64(table, "post_fee")
	s.ReceiverName = field.NewString(table, "receiver_name")
	s.ReceiverProvince = field.NewString(table, "receiver_province")
	s.ReceiverProvinceName = field.NewString(table, "receiver_province_name")
	s.ReceiverCity = field.NewString(table, "receiver_city")
	s.ReceiverCityName = field.NewString(table, "receiver_city_name")
	s.ReceiverDistrict = field.NewString(table, "receiver_district")
	s.ReceiverDistrictName = field.NewString(table, "receiver_district_name")
	s.ReceiverStreet = field.NewString(table, "receiver_street")
	s.ReceiverStreetName = field.NewString(table, "receiver_street_name")
	s.ReceiverAddress = field.NewString(table, "receiver_address")
	s.ReceiverPhone = field.NewString(table, "receiver_phone")
	s.ReceiverMobile = field.NewString(table, "receiver_mobile")
	s.ReceiverZip = field.NewString(table, "receiver_zip")
	s.Status = field.NewString(table, "status")
	s.OrderType = field.NewString(table, "order_type")
	s.InvoiceName = field.NewString(table, "invoice_name")
	s.SellerFlag = field.NewString(table, "seller_flag")
	s.PayTime = field.NewTime(table, "pay_time")
	s.LogistBTypeCode = field.NewString(table, "logist_b_type_code")
	s.LogistBillCode = field.NewString(table, "logist_bill_code")
	s.BTypeCode = field.NewString(table, "b_type_code")
	s.DetailsJSON = field.NewString(table, "details_json")
	s.AccountsJSON = field.NewString(table, "accounts_json")
	s.TransactionID = field.NewString(table, "transaction_id")
	s.NotifyRaw = field.NewString(table, "notify_raw")
	s.MchID = field.NewString(table, "mch_id")
	s.Appid = field.NewString(table, "appid")
	s.PayerOpenid = field.NewString(table, "payer_openid")
	s.PayChannel = field.NewInt32(table, "pay_channel")
	s.BillCode = field.NewString(table, "bill_code")
	s.SyncMessage = field.NewString(table, "sync_message")
	s.SyncStatus = field.NewInt32(table, "sync_status")
	s.SyncTime = field.NewTime(table, "sync_time")
	s.DeptID = field.NewInt64(table, "dept_id")
	s.CreateBy = field.NewInt64(table, "create_by")
	s.CreateTime = field.NewTime(table, "create_time")
	s.UpdateBy = field.NewInt64(table, "update_by")
	s.UpdateTime = field.NewTime(table, "update_time")
	s.State = field.NewBool(table, "state")

	s.fillFieldMap()

	return s
}

func (s *shopOrder) WithContext(ctx context.Context) *shopOrderDo {
	return s.shopOrderDo.WithContext(ctx)
}

func (s shopOrder) TableName() string { return s.shopOrderDo.TableName() }

func (s shopOrder) Alias() string { return s.shopOrderDo.Alias() }

func (s shopOrder) Columns(cols ...field.Expr) gen.Columns { return s.shopOrderDo.Columns(cols...) }

func (s *shopOrder) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *shopOrder) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 50)
	s.fieldMap["id"] = s.ID
	s.fieldMap["tid"] = s.Tid
	s.fieldMap["user_id"] = s.UserID
	s.fieldMap["weight"] = s.Weight
	s.fieldMap["size"] = s.Size
	s.fieldMap["buyer_nick"] = s.BuyerNick
	s.fieldMap["buyer_message"] = s.BuyerMessage
	s.fieldMap["seller_memo"] = s.SellerMemo
	s.fieldMap["total"] = s.Total
	s.fieldMap["privilege"] = s.Privilege
	s.fieldMap["post_fee"] = s.PostFee
	s.fieldMap["receiver_name"] = s.ReceiverName
	s.fieldMap["receiver_province"] = s.ReceiverProvince
	s.fieldMap["receiver_province_name"] = s.ReceiverProvinceName
	s.fieldMap["receiver_city"] = s.ReceiverCity
	s.fieldMap["receiver_city_name"] = s.ReceiverCityName
	s.fieldMap["receiver_district"] = s.ReceiverDistrict
	s.fieldMap["receiver_district_name"] = s.ReceiverDistrictName
	s.fieldMap["receiver_street"] = s.ReceiverStreet
	s.fieldMap["receiver_street_name"] = s.ReceiverStreetName
	s.fieldMap["receiver_address"] = s.ReceiverAddress
	s.fieldMap["receiver_phone"] = s.ReceiverPhone
	s.fieldMap["receiver_mobile"] = s.ReceiverMobile
	s.fieldMap["receiver_zip"] = s.ReceiverZip
	s.fieldMap["status"] = s.Status
	s.fieldMap["order_type"] = s.OrderType
	s.fieldMap["invoice_name"] = s.InvoiceName
	s.fieldMap["seller_flag"] = s.SellerFlag
	s.fieldMap["pay_time"] = s.PayTime
	s.fieldMap["logist_b_type_code"] = s.LogistBTypeCode
	s.fieldMap["logist_bill_code"] = s.LogistBillCode
	s.fieldMap["b_type_code"] = s.BTypeCode
	s.fieldMap["details_json"] = s.DetailsJSON
	s.fieldMap["accounts_json"] = s.AccountsJSON
	s.fieldMap["transaction_id"] = s.TransactionID
	s.fieldMap["notify_raw"] = s.NotifyRaw
	s.fieldMap["mch_id"] = s.MchID
	s.fieldMap["appid"] = s.Appid
	s.fieldMap["payer_openid"] = s.PayerOpenid
	s.fieldMap["pay_channel"] = s.PayChannel
	s.fieldMap["bill_code"] = s.BillCode
	s.fieldMap["sync_message"] = s.SyncMessage
	s.fieldMap["sync_status"] = s.SyncStatus
	s.fieldMap["sync_time"] = s.SyncTime
	s.fieldMap["dept_id"] = s.DeptID
	s.fieldMap["create_by"] = s.CreateBy
	s.fieldMap["create_time"] = s.CreateTime
	s.fieldMap["update_by"] = s.UpdateBy
	s.fieldMap["update_time"] = s.UpdateTime
	s.fieldMap["state"] = s.State
}

func (s shopOrder) clone(db *gorm.DB) shopOrder {
	s.shopOrderDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s shopOrder) replaceDB(db *gorm.DB) shopOrder {
	s.shopOrderDo.ReplaceDB(db)
	return s
}

type shopOrderDo struct{ gen.DO }

func (s shopOrderDo) Debug() *shopOrderDo {
	return s.withDO(s.DO.Debug())
}

func (s shopOrderDo) WithContext(ctx context.Context) *shopOrderDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s shopOrderDo) ReadDB() *shopOrderDo {
	return s.Clauses(dbresolver.Read)
}

func (s shopOrderDo) WriteDB() *shopOrderDo {
	return s.Clauses(dbresolver.Write)
}

func (s shopOrderDo) Session(config *gorm.Session) *shopOrderDo {
	return s.withDO(s.DO.Session(config))
}

func (s shopOrderDo) Clauses(conds ...clause.Expression) *shopOrderDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s shopOrderDo) Returning(value interface{}, columns ...string) *shopOrderDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s shopOrderDo) Not(conds ...gen.Condition) *shopOrderDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s shopOrderDo) Or(conds ...gen.Condition) *shopOrderDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s shopOrderDo) Select(conds ...field.Expr) *shopOrderDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s shopOrderDo) Where(conds ...gen.Condition) *shopOrderDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s shopOrderDo) Order(conds ...field.Expr) *shopOrderDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s shopOrderDo) Distinct(cols ...field.Expr) *shopOrderDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s shopOrderDo) Omit(cols ...field.Expr) *shopOrderDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s shopOrderDo) Join(table schema.Tabler, on ...field.Expr) *shopOrderDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s shopOrderDo) LeftJoin(table schema.Tabler, on ...field.Expr) *shopOrderDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s shopOrderDo) RightJoin(table schema.Tabler, on ...field.Expr) *shopOrderDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s shopOrderDo) Group(cols ...field.Expr) *shopOrderDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s shopOrderDo) Having(conds ...gen.Condition) *shopOrderDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s shopOrderDo) Limit(limit int) *shopOrderDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s shopOrderDo) Offset(offset int) *shopOrderDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s shopOrderDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *shopOrderDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s shopOrderDo) Unscoped() *shopOrderDo {
	return s.withDO(s.DO.Unscoped())
}

func (s shopOrderDo) Create(values ...*model.ShopOrder) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s shopOrderDo) CreateInBatches(values []*model.ShopOrder, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s shopOrderDo) Save(values ...*model.ShopOrder) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s shopOrderDo) First() (*model.ShopOrder, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ShopOrder), nil
	}
}

func (s shopOrderDo) Take() (*model.ShopOrder, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ShopOrder), nil
	}
}

func (s shopOrderDo) Last() (*model.ShopOrder, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ShopOrder), nil
	}
}

func (s shopOrderDo) Find() ([]*model.ShopOrder, error) {
	result, err := s.DO.Find()
	return result.([]*model.ShopOrder), err
}

func (s shopOrderDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ShopOrder, err error) {
	buf := make([]*model.ShopOrder, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s shopOrderDo) FindInBatches(result *[]*model.ShopOrder, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s shopOrderDo) Attrs(attrs ...field.AssignExpr) *shopOrderDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s shopOrderDo) Assign(attrs ...field.AssignExpr) *shopOrderDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s shopOrderDo) Joins(fields ...field.RelationField) *shopOrderDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s shopOrderDo) Preload(fields ...field.RelationField) *shopOrderDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s shopOrderDo) FirstOrInit() (*model.ShopOrder, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ShopOrder), nil
	}
}

func (s shopOrderDo) FirstOrCreate() (*model.ShopOrder, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ShopOrder), nil
	}
}

func (s shopOrderDo) FindByPage(offset int, limit int) (result []*model.ShopOrder, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s shopOrderDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s shopOrderDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s shopOrderDo) Delete(models ...*model.ShopOrder) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *shopOrderDo) withDO(do gen.Dao) *shopOrderDo {
	s.DO = *do.(*gen.DO)
	return s
}
