// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"nova-factory-server/dao/model"
)

func newShopOrderRefund(db *gorm.DB, opts ...gen.DOOption) shopOrderRefund {
	_shopOrderRefund := shopOrderRefund{}

	_shopOrderRefund.shopOrderRefundDo.UseDB(db, opts...)
	_shopOrderRefund.shopOrderRefundDo.UseModel(&model.ShopOrderRefund{})

	tableName := _shopOrderRefund.shopOrderRefundDo.TableName()
	_shopOrderRefund.ALL = field.NewAsterisk(tableName)
	_shopOrderRefund.ID = field.NewInt64(tableName, "id")
	_shopOrderRefund.OrderID = field.NewInt64(tableName, "order_id")
	_shopOrderRefund.Tid = field.NewString(tableName, "tid")
	_shopOrderRefund.UserID = field.NewInt64(tableName, "user_id")
	_shopOrderRefund.PayChannel = field.NewInt32(tableName, "pay_channel")
	_shopOrderRefund.RefundChannel = field.NewInt32(tableName, "refund_channel")
	_shopOrderRefund.OutRefundNo = field.NewString(tableName, "out_refund_no")
	_shopOrderRefund.RefundAmount = field.NewFloat64(tableName, "refund_amount")
	_shopOrderRefund.TotalAmount = field.NewFloat64(tableName, "total_amount")
	_shopOrderRefund.Reason = field.NewString(tableName, "reason")
	_shopOrderRefund.PreviousStatus = field.NewString(tableName, "previous_status")
	_shopOrderRefund.Status = field.NewInt32(tableName, "status")
	_shopOrderRefund.AuditRemark = field.NewString(tableName, "audit_remark")
	_shopOrderRefund.AuditBy = field.NewInt64(tableName, "audit_by")
	_shopOrderRefund.AuditTime = field.NewTime(tableName, "audit_time")
	_shopOrderRefund.ThirdTransactionID = field.NewString(tableName, "third_transaction_id")
	_shopOrderRefund.ThirdRefundID = field.NewString(tableName, "third_refund_id")
	_shopOrderRefund.DetailsJSON = field.NewString(tableName, "details_json")
	_shopOrderRefund.ErpPlatformID = field.NewInt64(tableName, "erp_platform_id")
	_shopOrderRefund.ErpSyncStatus = field.NewInt32(tableName, "erp_sync_status")
	_shopOrderRefund.ErpSyncMessage = field.NewString(tableName, "erp_sync_message")
	_shopOrderRefund.ErpSyncTime = field.NewTime(tableName, "erp_sync_time")
	_shopOrderRefund.ErpSyncBillCode = field.NewString(tableName, "erp_sync_bill_code")
	_shopOrderRefund.CreateBy = field.NewInt64(tableName, "create_by")
	_shopOrderRefund.CreateTime = field.NewTime(tableName, "create_time")
	_shopOrderRefund.UpdateBy = field.NewInt64(tableName, "update_by")
	_shopOrderRefund.UpdateTime = field.NewTime(tableName, "update_time")
	_shopOrderRefund.State = field.NewBool(tableName, "state")

	_shopOrderRefund.fillFieldMap()

	return _shopOrderRefund
}

// shopOrderRefund 商城售后单主表
type shopOrderRefund struct {
	shopOrderRefundDo shopOrderRefundDo

	ALL                field.Asterisk
	ID                 field.Int64   // 主键ID
	OrderID            field.Int64   // 订单主表ID
	Tid                field.String  // 网店订单编号
	UserID             field.Int64   // 申请人ID
	PayChannel         field.Int32   // 原支付通道：0未知 1微信 2支付宝
	RefundChannel      field.Int32   // 实际退款通道：0未知 1微信 2支付宝
	OutRefundNo        field.String  // 商户退款单号
	RefundAmount       field.Float64 // 退款金额
	TotalAmount        field.Float64 // 原订单金额
	Reason             field.String  // 退款原因
	PreviousStatus     field.String  // 售前订单状态
	Status             field.Int32   // 售后状态：0待审核 1已审核 2退款中 3退款成功 4退款失败 5退款关闭 6已拒绝
	AuditRemark        field.String  // 审核备注
	AuditBy            field.Int64   // 审核人
	AuditTime          field.Time    // 审核时间
	ThirdTransactionID field.String  // 三方交易号
	ThirdRefundID      field.String  // 三方退款单号
	DetailsJSON        field.String  // 退款明细JSON
	ErpPlatformID      field.Int64   // erp平台ID
	ErpSyncStatus      field.Int32   // erp同步状态：0待同步 1成功 2失败
	ErpSyncMessage     field.String  // 同步结果描述
	ErpSyncTime        field.Time    // 同步时间
	ErpSyncBillCode    field.String  // erp返回单号
	CreateBy           field.Int64   // 创建者
	CreateTime         field.Time    // 创建时间
	UpdateBy           field.Int64   // 更新者
	UpdateTime         field.Time    // 更新时间
	State              field.Bool    // 操作状态（0正常 -1删除）

	fieldMap map[string]field.Expr
}

func (s shopOrderRefund) Table(newTableName string) *shopOrderRefund {
	s.shopOrderRefundDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s shopOrderRefund) As(alias string) *shopOrderRefund {
	s.shopOrderRefundDo.DO = *(s.shopOrderRefundDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *shopOrderRefund) updateTableName(table string) *shopOrderRefund {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewInt64(table, "id")
	s.OrderID = field.NewInt64(table, "order_id")
	s.Tid = field.NewString(table, "tid")
	s.UserID = field.NewInt64(table, "user_id")
	s.PayChannel = field.NewInt32(table, "pay_channel")
	s.RefundChannel = field.NewInt32(table, "refund_channel")
	s.OutRefundNo = field.NewString(table, "out_refund_no")
	s.RefundAmount = field.NewFloat64(table, "refund_amount")
	s.TotalAmount = field.NewFloat64(table, "total_amount")
	s.Reason = field.NewString(table, "reason")
	s.PreviousStatus = field.NewString(table, "previous_status")
	s.Status = field.NewInt32(table, "status")
	s.AuditRemark = field.NewString(table, "audit_remark")
	s.AuditBy = field.NewInt64(table, "audit_by")
	s.AuditTime = field.NewTime(table, "audit_time")
	s.ThirdTransactionID = field.NewString(table, "third_transaction_id")
	s.ThirdRefundID = field.NewString(table, "third_refund_id")
	s.DetailsJSON = field.NewString(table, "details_json")
	s.ErpPlatformID = field.NewInt64(table, "erp_platform_id")
	s.ErpSyncStatus = field.NewInt32(table, "erp_sync_status")
	s.ErpSyncMessage = field.NewString(table, "erp_sync_message")
	s.ErpSyncTime = field.NewTime(table, "erp_sync_time")
	s.ErpSyncBillCode = field.NewString(table, "erp_sync_bill_code")
	s.CreateBy = field.NewInt64(table, "create_by")
	s.CreateTime = field.NewTime(table, "create_time")
	s.UpdateBy = field.NewInt64(table, "update_by")
	s.UpdateTime = field.NewTime(table, "update_time")
	s.State = field.NewBool(table, "state")

	s.fillFieldMap()

	return s
}

func (s *shopOrderRefund) WithContext(ctx context.Context) *shopOrderRefundDo {
	return s.shopOrderRefundDo.WithContext(ctx)
}

func (s shopOrderRefund) TableName() string { return s.shopOrderRefundDo.TableName() }

func (s shopOrderRefund) Alias() string { return s.shopOrderRefundDo.Alias() }

func (s shopOrderRefund) Columns(cols ...field.Expr) gen.Columns {
	return s.shopOrderRefundDo.Columns(cols...)
}

func (s *shopOrderRefund) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *shopOrderRefund) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 28)
	s.fieldMap["id"] = s.ID
	s.fieldMap["order_id"] = s.OrderID
	s.fieldMap["tid"] = s.Tid
	s.fieldMap["user_id"] = s.UserID
	s.fieldMap["pay_channel"] = s.PayChannel
	s.fieldMap["refund_channel"] = s.RefundChannel
	s.fieldMap["out_refund_no"] = s.OutRefundNo
	s.fieldMap["refund_amount"] = s.RefundAmount
	s.fieldMap["total_amount"] = s.TotalAmount
	s.fieldMap["reason"] = s.Reason
	s.fieldMap["previous_status"] = s.PreviousStatus
	s.fieldMap["status"] = s.Status
	s.fieldMap["audit_remark"] = s.AuditRemark
	s.fieldMap["audit_by"] = s.AuditBy
	s.fieldMap["audit_time"] = s.AuditTime
	s.fieldMap["third_transaction_id"] = s.ThirdTransactionID
	s.fieldMap["third_refund_id"] = s.ThirdRefundID
	s.fieldMap["details_json"] = s.DetailsJSON
	s.fieldMap["erp_platform_id"] = s.ErpPlatformID
	s.fieldMap["erp_sync_status"] = s.ErpSyncStatus
	s.fieldMap["erp_sync_message"] = s.ErpSyncMessage
	s.fieldMap["erp_sync_time"] = s.ErpSyncTime
	s.fieldMap["erp_sync_bill_code"] = s.ErpSyncBillCode
	s.fieldMap["create_by"] = s.CreateBy
	s.fieldMap["create_time"] = s.CreateTime
	s.fieldMap["update_by"] = s.UpdateBy
	s.fieldMap["update_time"] = s.UpdateTime
	s.fieldMap["state"] = s.State
}

func (s shopOrderRefund) clone(db *gorm.DB) shopOrderRefund {
	s.shopOrderRefundDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s shopOrderRefund) replaceDB(db *gorm.DB) shopOrderRefund {
	s.shopOrderRefundDo.ReplaceDB(db)
	return s
}

type shopOrderRefundDo struct{ gen.DO }

func (s shopOrderRefundDo) Debug() *shopOrderRefundDo {
	return s.withDO(s.DO.Debug())
}

func (s shopOrderRefundDo) WithContext(ctx context.Context) *shopOrderRefundDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s shopOrderRefundDo) ReadDB() *shopOrderRefundDo {
	return s.Clauses(dbresolver.Read)
}

func (s shopOrderRefundDo) WriteDB() *shopOrderRefundDo {
	return s.Clauses(dbresolver.Write)
}

func (s shopOrderRefundDo) Session(config *gorm.Session) *shopOrderRefundDo {
	return s.withDO(s.DO.Session(config))
}

func (s shopOrderRefundDo) Clauses(conds ...clause.Expression) *shopOrderRefundDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s shopOrderRefundDo) Returning(value interface{}, columns ...string) *shopOrderRefundDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s shopOrderRefundDo) Not(conds ...gen.Condition) *shopOrderRefundDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s shopOrderRefundDo) Or(conds ...gen.Condition) *shopOrderRefundDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s shopOrderRefundDo) Select(conds ...field.Expr) *shopOrderRefundDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s shopOrderRefundDo) Where(conds ...gen.Condition) *shopOrderRefundDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s shopOrderRefundDo) Order(conds ...field.Expr) *shopOrderRefundDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s shopOrderRefundDo) Distinct(cols ...field.Expr) *shopOrderRefundDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s shopOrderRefundDo) Omit(cols ...field.Expr) *shopOrderRefundDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s shopOrderRefundDo) Join(table schema.Tabler, on ...field.Expr) *shopOrderRefundDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s shopOrderRefundDo) LeftJoin(table schema.Tabler, on ...field.Expr) *shopOrderRefundDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s shopOrderRefundDo) RightJoin(table schema.Tabler, on ...field.Expr) *shopOrderRefundDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s shopOrderRefundDo) Group(cols ...field.Expr) *shopOrderRefundDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s shopOrderRefundDo) Having(conds ...gen.Condition) *shopOrderRefundDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s shopOrderRefundDo) Limit(limit int) *shopOrderRefundDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s shopOrderRefundDo) Offset(offset int) *shopOrderRefundDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s shopOrderRefundDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *shopOrderRefundDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s shopOrderRefundDo) Unscoped() *shopOrderRefundDo {
	return s.withDO(s.DO.Unscoped())
}

func (s shopOrderRefundDo) Create(values ...*model.ShopOrderRefund) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s shopOrderRefundDo) CreateInBatches(values []*model.ShopOrderRefund, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s shopOrderRefundDo) Save(values ...*model.ShopOrderRefund) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s shopOrderRefundDo) First() (*model.ShopOrderRefund, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ShopOrderRefund), nil
	}
}

func (s shopOrderRefundDo) Take() (*model.ShopOrderRefund, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ShopOrderRefund), nil
	}
}

func (s shopOrderRefundDo) Last() (*model.ShopOrderRefund, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ShopOrderRefund), nil
	}
}

func (s shopOrderRefundDo) Find() ([]*model.ShopOrderRefund, error) {
	result, err := s.DO.Find()
	return result.([]*model.ShopOrderRefund), err
}

func (s shopOrderRefundDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ShopOrderRefund, err error) {
	buf := make([]*model.ShopOrderRefund, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s shopOrderRefundDo) FindInBatches(result *[]*model.ShopOrderRefund, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s shopOrderRefundDo) Attrs(attrs ...field.AssignExpr) *shopOrderRefundDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s shopOrderRefundDo) Assign(attrs ...field.AssignExpr) *shopOrderRefundDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s shopOrderRefundDo) Joins(fields ...field.RelationField) *shopOrderRefundDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s shopOrderRefundDo) Preload(fields ...field.RelationField) *shopOrderRefundDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s shopOrderRefundDo) FirstOrInit() (*model.ShopOrderRefund, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ShopOrderRefund), nil
	}
}

func (s shopOrderRefundDo) FirstOrCreate() (*model.ShopOrderRefund, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ShopOrderRefund), nil
	}
}

func (s shopOrderRefundDo) FindByPage(offset int, limit int) (result []*model.ShopOrderRefund, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s shopOrderRefundDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s shopOrderRefundDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s shopOrderRefundDo) Delete(models ...*model.ShopOrderRefund) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *shopOrderRefundDo) withDO(do gen.Dao) *shopOrderRefundDo {
	s.DO = *do.(*gen.DO)
	return s
}
