// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameShopOrder = "shop_order"

// ShopOrder ERP订单主表
type ShopOrder struct {
	ID                   uint64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键ID" json:"id"`                     // 主键ID
	Tid                  string     `gorm:"column:tid;not null;comment:网店订单编号" json:"tid"`                                      // 网店订单编号
	UserID               uint64     `gorm:"column:user_id;not null;comment:用户id" json:"user_id"`                                // 用户id
	Weight               float64    `gorm:"column:weight;comment:订单重量" json:"weight"`                                           // 订单重量
	Size                 float64    `gorm:"column:size;comment:订单尺寸/体积" json:"size"`                                            // 订单尺寸/体积
	BuyerNick            string     `gorm:"column:buyer_nick;comment:买家账号" json:"buyer_nick"`                                   // 买家账号
	BuyerMessage         string     `gorm:"column:buyer_message;comment:买家留言" json:"buyer_message"`                             // 买家留言
	SellerMemo           string     `gorm:"column:seller_memo;comment:卖家备注" json:"seller_memo"`                                 // 卖家备注
	Total                float64    `gorm:"column:total;comment:订单总金额（含运费）" json:"total"`                                       // 订单总金额（含运费）
	Privilege            float64    `gorm:"column:privilege;not null;default:0.00000000;comment:订单优惠金额" json:"privilege"`       // 订单优惠金额
	PostFee              float64    `gorm:"column:post_fee;not null;default:0.00000000;comment:运费" json:"post_fee"`             // 运费
	ReceiverName         string     `gorm:"column:receiver_name;not null;comment:收货人名称" json:"receiver_name"`                   // 收货人名称
	ReceiverProvince     string     `gorm:"column:receiver_province;not null;comment:收货省编码" json:"receiver_province"`           // 收货省编码
	ReceiverProvinceName string     `gorm:"column:receiver_province_name;not null;comment:收货省名称" json:"receiver_province_name"` // 收货省名称
	ReceiverCity         string     `gorm:"column:receiver_city;not null;comment:收货市编码" json:"receiver_city"`                   // 收货市编码
	ReceiverCityName     string     `gorm:"column:receiver_city_name;not null;comment:收货市名称" json:"receiver_city_name"`         // 收货市名称
	ReceiverDistrict     string     `gorm:"column:receiver_district;not null;comment:收货区编码" json:"receiver_district"`           // 收货区编码
	ReceiverDistrictName string     `gorm:"column:receiver_district_name;not null;comment:收货区名称" json:"receiver_district_name"` // 收货区名称
	ReceiverStreet       string     `gorm:"column:receiver_street;not null;comment:收货街道编码" json:"receiver_street"`              // 收货街道编码
	ReceiverStreetName   string     `gorm:"column:receiver_street_name;not null;comment:收货街道名称" json:"receiver_street_name"`    // 收货街道名称
	ReceiverAddress      string     `gorm:"column:receiver_address;not null;comment:收货详细地址" json:"receiver_address"`            // 收货详细地址
	ReceiverPhone        string     `gorm:"column:receiver_phone;comment:收货电话" json:"receiver_phone"`                           // 收货电话
	ReceiverMobile       string     `gorm:"column:receiver_mobile;not null;comment:收货人手机号" json:"receiver_mobile"`              // 收货人手机号
	ReceiverZip          string     `gorm:"column:receiver_zip;comment:邮编" json:"receiver_zip"`                                 // 邮编
	Status               string     `gorm:"column:status;not null;comment:订单状态" json:"status"`                                  // 订单状态
	OrderType            string     `gorm:"column:order_type;not null;comment:订单类型（Cod/NoCod）" json:"order_type"`               // 订单类型（Cod/NoCod）
	InvoiceName          string     `gorm:"column:invoice_name;comment:发票抬头" json:"invoice_name"`                               // 发票抬头
	SellerFlag           string     `gorm:"column:seller_flag;comment:卖家旗帜" json:"seller_flag"`                                 // 卖家旗帜
	PayTime              *time.Time `gorm:"column:pay_time;comment:付款时间" json:"pay_time"`                                       // 付款时间
	LogistBTypeCode      string     `gorm:"column:logist_b_type_code;comment:物流公司编码" json:"logist_b_type_code"`                 // 物流公司编码
	LogistBillCode       string     `gorm:"column:logist_bill_code;comment:物流单号" json:"logist_bill_code"`                       // 物流单号
	BTypeCode            string     `gorm:"column:b_type_code;comment:往来单位编码" json:"b_type_code"`                               // 往来单位编码
	DetailsJSON          string     `gorm:"column:details_json;comment:订单商品明细JSON" json:"details_json"`                         // 订单商品明细JSON
	AccountsJSON         string     `gorm:"column:accounts_json;comment:订单账户信息JSON" json:"accounts_json"`                       // 订单账户信息JSON
	TransactionID        string     `gorm:"column:transaction_id;comment:微信支付交易单号" json:"transaction_id"`                       // 微信支付交易单号
	NotifyRaw            string     `gorm:"column:notify_raw;comment:微信支付回调原文" json:"notify_raw"`                               // 微信支付回调原文
	MchID                string     `gorm:"column:mch_id;comment:微信商户号" json:"mch_id"`                                          // 微信商户号
	Appid                string     `gorm:"column:appid;comment:小程序AppID" json:"appid"`                                         // 小程序AppID
	PayerOpenid          string     `gorm:"column:payer_openid;comment:支付用户openid" json:"payer_openid"`                         // 支付用户openid
	PayChannel           int32      `gorm:"column:pay_channel;comment:支付通道：0未知 1微信 2支付宝" json:"pay_channel"`                    // 支付通道：0未知 1微信 2支付宝
	BillCode             string     `gorm:"column:bill_code;comment:管家婆返回订单编号" json:"bill_code"`                                // 管家婆返回订单编号
	SyncMessage          string     `gorm:"column:sync_message;comment:同步结果描述" json:"sync_message"`                             // 同步结果描述
	SyncStatus           int32      `gorm:"column:sync_status;not null;comment:同步状态：0待同步 1成功 2失败" json:"sync_status"`           // 同步状态：0待同步 1成功 2失败
	SyncTime             *time.Time `gorm:"column:sync_time;comment:同步时间" json:"sync_time"`                                     // 同步时间
	DeptID               int64      `gorm:"column:dept_id;comment:部门ID" json:"dept_id"`                                         // 部门ID
	CreateBy             int64      `gorm:"column:create_by;comment:创建者" json:"create_by"`                                      // 创建者
	CreateTime           *time.Time `gorm:"column:create_time;comment:创建时间" json:"create_time"`                                 // 创建时间
	UpdateBy             int64      `gorm:"column:update_by;comment:更新者" json:"update_by"`                                      // 更新者
	UpdateTime           *time.Time `gorm:"column:update_time;comment:更新时间" json:"update_time"`                                 // 更新时间
	State                int32      `gorm:"column:state;comment:操作状态（0正常 -1删除）" json:"state"`                                   // 操作状态（0正常 -1删除）
}

// TableName ShopOrder's table name
func (*ShopOrder) TableName() string {
	return TableNameShopOrder
}
