package main

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
)

func main() {
	cwd, _ := os.Getwd()
	srcDir := findProjectRoot(cwd)
	outputPath := filepath.Join(srcDir, "app", "utils", "gin_mcp", "pkg", "convert", "handler_docs_gen.go")

	entries := make(map[string]map[string]handlerDoc)
	err := filepath.WalkDir(filepath.Join(srcDir, "app"), func(path string, d os.DirEntry, err error) error {
		if err != nil {
			return nil
		}
		if d.IsDir() || !strings.HasSuffix(path, ".go") {
			return nil
		}
		extractFromFile(path, entries)
		return nil
	})
	if err != nil {
		fmt.Fprintf(os.Stderr, "walk error: %v\n", err)
		os.Exit(1)
	}

	if err := writeGenerated(outputPath, entries); err != nil {
		fmt.Fprintf(os.Stderr, "write error: %v\n", err)
		os.Exit(1)
	}
	fmt.Printf("Generated %s with %d files\n", outputPath, len(entries))
}

type handlerDoc struct {
	Summary     string
	Description string
	Params      map[string]string
	Returns     string
	Tags        []string
	OperationID string
}

func findProjectRoot(dir string) string {
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			// hit root, fall back to CWD
			return dir
		}
		dir = parent
	}
}

func extractFromFile(filePath string, out map[string]map[string]handlerDoc) {
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, filePath, nil, parser.ParseComments)
	if err != nil {
		return
	}

	absPath, err := filepath.Abs(filePath)
	if err != nil {
		absPath = filePath
	}

	docs := make(map[string]handlerDoc)
	for _, decl := range f.Decls {
		fn, ok := decl.(*ast.FuncDecl)
		if !ok || fn.Doc == nil {
			continue
		}
		doc := parseDoc(fn.Doc.Text())
		if doc.isEmpty() {
			continue
		}
		docs[fn.Name.String()] = doc
	}

	if len(docs) > 0 {
		out[absPath] = docs
	}
}

func parseDoc(text string) handlerDoc {
	doc := handlerDoc{Params: make(map[string]string)}
	lines := strings.Split(text, "\n")
	for _, line := range lines {
		lineTrim := strings.TrimSpace(line)
		line = strings.ToLower(lineTrim)
		switch {
		case strings.HasPrefix(line, "@summary"):
			doc.Summary = strings.TrimSpace(strings.TrimPrefix(lineTrim, "@summary"))
		case strings.HasPrefix(line, "@description"):
			doc.Description = strings.TrimSpace(strings.TrimPrefix(lineTrim, "@description"))
		case strings.HasPrefix(line, "@param"):
			paramText := strings.TrimSpace(strings.TrimPrefix(lineTrim, "@param"))
			parts := strings.SplitN(paramText, " ", 2)
			if len(parts) == 2 {
				doc.Params[strings.TrimSpace(parts[0])] = strings.TrimSpace(parts[1])
			}
		case strings.HasPrefix(line, "@return"):
			doc.Returns = strings.TrimSpace(strings.TrimPrefix(lineTrim, "@return"))
		case strings.HasPrefix(line, "@tags"):
			tagsText := strings.TrimSpace(strings.TrimPrefix(lineTrim, "@tags"))
			for _, sep := range []string{",", " "} {
				parts := strings.Split(tagsText, sep)
				tagsText = ""
				for _, part := range parts {
					trimmed := strings.TrimSpace(part)
					if trimmed == "" {
						continue
					}
					found := false
					for _, t := range doc.Tags {
						if t == trimmed {
							found = true
							break
						}
					}
					if !found {
						doc.Tags = append(doc.Tags, trimmed)
					}
				}
				if sep == "," {
					tagsText = strings.Join(doc.Tags, " ")
					doc.Tags = nil
				}
			}
		case strings.HasPrefix(line, "@operationid"):
			opID := strings.TrimSpace(strings.TrimPrefix(lineTrim, "@operationId"))
			if opID != "" && doc.OperationID == "" {
				doc.OperationID = opID
			}
		}
	}
	return doc
}

func (d handlerDoc) isEmpty() bool {
	return d.Summary == "" && d.Description == "" && len(d.Params) == 0 &&
		d.Returns == "" && len(d.Tags) == 0 && d.OperationID == ""
}

func writeGenerated(path string, entries map[string]map[string]handlerDoc) error {
	var sb strings.Builder
	sb.WriteString("// Code generated by handler-doc-gen; DO NOT EDIT.\n\n")
	sb.WriteString("package convert\n\n")
	sb.WriteString("var handlerDocMap = map[string]map[string]HandlerDoc{\n")

	for filePath, docs := range entries {
		sb.WriteString(fmt.Sprintf("\t%q: {\n", filePath))
		for name, doc := range docs {
			sb.WriteString(fmt.Sprintf("\t\t%q: {\n", name))
			sb.WriteString(fmt.Sprintf("\t\t\tSummary:     %q,\n", doc.Summary))
			sb.WriteString(fmt.Sprintf("\t\t\tDescription: %q,\n", doc.Description))
			sb.WriteString(fmt.Sprintf("\t\t\tReturns:     %q,\n", doc.Returns))
			if len(doc.Params) > 0 {
				sb.WriteString("\t\t\tParams: map[string]string{\n")
				for k, v := range doc.Params {
					sb.WriteString(fmt.Sprintf("\t\t\t\t%q: %q,\n", k, v))
				}
				sb.WriteString("\t\t\t},\n")
			}
			if len(doc.Tags) > 0 {
				sb.WriteString("\t\t\tTags: []string{")
				for i, t := range doc.Tags {
					if i > 0 {
						sb.WriteString(", ")
					}
					sb.WriteString(fmt.Sprintf("%q", t))
				}
				sb.WriteString("},\n")
			}
			sb.WriteString(fmt.Sprintf("\t\t\tOperationID: %q,\n", doc.OperationID))
			sb.WriteString("\t\t},\n")
		}
		sb.WriteString("\t},\n")
	}
	sb.WriteString("}\n")

	return os.WriteFile(path, []byte(sb.String()), 0644)
}
