CREATE TABLE IF NOT EXISTS `shop_category` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `parent_id` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '父分类ID，0表示根分类',
  `ancestor_path` VARCHAR(1024) NOT NULL DEFAULT '/' COMMENT '祖先路径，例如/1/3/8/',
  `depth` INT UNSIGNED NOT NULL DEFAULT 1 COMMENT '层级深度，从1开始',
  `category_name` VARCHAR(128) NOT NULL COMMENT '分类名称',
  `category_code` VARCHAR(64) DEFAULT NULL COMMENT '分类编码',
  `image_url` VARCHAR(1024) DEFAULT NULL COMMENT '分类图片URL',
  `description` TEXT COMMENT '分类描述',
  `sort` INT NOT NULL DEFAULT 0 COMMENT '排序值，越小越靠前',
  `status` TINYINT NOT NULL DEFAULT 1 COMMENT '状态：1启用，0禁用',
    `dept_id` bigint(20) NULL DEFAULT NULL COMMENT '部门ID',
    `create_by` bigint(20) NULL DEFAULT NULL COMMENT '创建者',
    `create_time` datetime(0) NULL DEFAULT NULL COMMENT '创建时间',
    `update_by` bigint(20) NULL DEFAULT NULL COMMENT '更新者',
    `update_time` datetime(0) NULL DEFAULT NULL COMMENT '更新时间',
    `state` tinyint(1) NULL DEFAULT 0 COMMENT '操作状态（0正常 -1删除）',
  PRIMARY KEY (`id`),
  KEY `uk_category_code` (`category_code`),
  KEY `idx_parent_id` (`parent_id`),
  KEY `idx_ancestor_path` (`ancestor_path`(191)),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='商品分类表';


CREATE TABLE IF NOT EXISTS `shop_goods` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `shop_category_id`  bigint(20) NOT NULL DEFAULT 0 COMMENT '分类id',
  `goods_id` VARCHAR(64) NOT NULL COMMENT '商品ID，对应goodsID',
  `goods_name` VARCHAR(255) NOT NULL COMMENT '商品名称',
  `goods_code` VARCHAR(128) DEFAULT NULL COMMENT '商品编码',
  `outer_id` VARCHAR(128) DEFAULT NULL COMMENT '商品商家编码',
  `image_url` VARCHAR(1024) DEFAULT NULL COMMENT '商品主图URL',
  `retail_price` DECIMAL(10,2) NOT NULL DEFAULT 0.00 COMMENT '零售价',
  `gallery_images` TEXT COMMENT '商品子图列表，JSON数组字符串',
  `video_url` VARCHAR(1024) DEFAULT NULL COMMENT '商品视频URL',
  `description` TEXT COMMENT '商品描述',
  `weight` DECIMAL(10,3) NOT NULL DEFAULT 0.000 COMMENT '商品重量',
  `weight_unit` VARCHAR(16) NOT NULL DEFAULT 'kg' COMMENT '重量单位',
  `unit` VARCHAR(32) NOT NULL DEFAULT '件' COMMENT '计量单位',
  `is_on_sale` TINYINT NOT NULL DEFAULT 0 COMMENT '是否在售：1是，0否',
  `quantity` INT NOT NULL DEFAULT 0 COMMENT '商品总库存',
    `dept_id` bigint(20) NULL DEFAULT NULL COMMENT '部门ID',
    `create_by` bigint(20) NULL DEFAULT NULL COMMENT '创建者',
    `create_time` datetime(0) NULL DEFAULT NULL COMMENT '创建时间',
    `update_by` bigint(20) NULL DEFAULT NULL COMMENT '更新者',
    `update_time` datetime(0) NULL DEFAULT NULL COMMENT '更新时间',
    `state` tinyint(1) NULL DEFAULT 0 COMMENT '操作状态（0正常 -1删除）',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_goods_id` (`goods_id`),
  KEY `idx_goods_code` (`goods_code`),
  KEY `idx_outer_id` (`outer_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='商品主表';

CREATE TABLE IF NOT EXISTS `shop_goods_sku` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `goods_id` VARCHAR(64) NOT NULL COMMENT '商品ID，对应shop_goods.goods_id',
  `sku_id` VARCHAR(64) NOT NULL COMMENT 'SKU ID，对应skuID',
  `sku_name` VARCHAR(255) DEFAULT NULL COMMENT 'SKU名称',
  `sku_code` VARCHAR(128) DEFAULT NULL COMMENT 'SKU编码',
  `outer_id` VARCHAR(128) DEFAULT NULL COMMENT '规格商家编码',
  `barcode` VARCHAR(128) DEFAULT NULL COMMENT '条码',
  `image_url` VARCHAR(1024) DEFAULT NULL COMMENT 'SKU图片URL',
  `retail_price` DECIMAL(10,2) NOT NULL DEFAULT 0.00 COMMENT '零售价',
  `gallery_images` TEXT COMMENT 'SKU子图列表，JSON数组字符串',
  `video_url` VARCHAR(1024) DEFAULT NULL COMMENT 'SKU视频URL',
  `description` TEXT COMMENT 'SKU描述',
  `weight` DECIMAL(10,3) NOT NULL DEFAULT 0.000 COMMENT 'SKU重量',
  `weight_unit` VARCHAR(16) NOT NULL DEFAULT 'kg' COMMENT '重量单位',
  `unit` VARCHAR(32) NOT NULL DEFAULT '件' COMMENT '计量单位',
  `quantity` INT NOT NULL DEFAULT 0 COMMENT 'SKU库存',
    `dept_id` bigint(20) NULL DEFAULT NULL COMMENT '部门ID',
    `create_by` bigint(20) NULL DEFAULT NULL COMMENT '创建者',
    `create_time` datetime(0) NULL DEFAULT NULL COMMENT '创建时间',
    `update_by` bigint(20) NULL DEFAULT NULL COMMENT '更新者',
    `update_time` datetime(0) NULL DEFAULT NULL COMMENT '更新时间',
    `state` tinyint(1) NULL DEFAULT 0 COMMENT '操作状态（0正常 -1删除）',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_sku_id` (`sku_id`),
  KEY `idx_goods_id` (`goods_id`),
  KEY `idx_sku_code` (`sku_code`),
  KEY `idx_outer_id` (`outer_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='商品SKU表';

CREATE TABLE IF NOT EXISTS `shop_user` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `username` VARCHAR(64) NOT NULL COMMENT '用户名',
  `nickname` VARCHAR(128) DEFAULT NULL COMMENT '用户昵称',
  `mobile` VARCHAR(32) DEFAULT NULL COMMENT '手机号',
  `email` VARCHAR(128) DEFAULT NULL COMMENT '邮箱',
  `password` VARCHAR(255) DEFAULT NULL COMMENT '密码摘要',
  `user_type` TINYINT NOT NULL COMMENT '用户类型：1代理商，2分销商，3工厂',
  `avatar` VARCHAR(512) DEFAULT NULL COMMENT '头像',
  `company_name` VARCHAR(255) DEFAULT NULL COMMENT '企业名称',
  `contact_name` VARCHAR(128) DEFAULT NULL COMMENT '联系人',
  `contact_phone` VARCHAR(32) DEFAULT NULL COMMENT '联系人手机号',
  `status` tinyint(1) NULL DEFAULT 0 COMMENT  '状态：1启用，0禁用',
    `dept_id` bigint(20) NULL DEFAULT NULL COMMENT '部门ID',
    `create_by` bigint(20) NULL DEFAULT NULL COMMENT '创建者',
    `create_time` datetime(0) NULL DEFAULT NULL COMMENT '创建时间',
    `update_by` bigint(20) NULL DEFAULT NULL COMMENT '更新者',
    `update_time` datetime(0) NULL DEFAULT NULL COMMENT '更新时间',
    `state` tinyint(1) NULL DEFAULT 0 COMMENT '操作状态（0正常 -1删除）',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_username` (`username`),
  KEY `idx_mobile` (`mobile`),
  KEY `idx_user_type` (`user_type`),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='商城用户表';

CREATE TABLE IF NOT EXISTS `shop_user_address` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `user_id` bigint(20) NOT NULL COMMENT '用户业务ID，对应shop_user.user_id',
    `receiver_name` VARCHAR(128) NOT NULL COMMENT '收货人姓名',
    `receiver_mobile` VARCHAR(32) NOT NULL COMMENT '收货人手机号',
    `province_code` VARCHAR(32) DEFAULT NULL COMMENT '省编码',
    `province_name` VARCHAR(64) NOT NULL COMMENT '省名称',
    `city_code` VARCHAR(32) DEFAULT NULL COMMENT '市编码',
    `city_name` VARCHAR(64) NOT NULL COMMENT '市名称',
    `district_code` VARCHAR(32) DEFAULT NULL COMMENT '区编码',
    `district_name` VARCHAR(64) NOT NULL COMMENT '区名称',
    `street_code` VARCHAR(32) DEFAULT NULL COMMENT '街道编码',
    `street_name` VARCHAR(64) DEFAULT NULL COMMENT '街道名称',
    `detail_address` VARCHAR(255) NOT NULL COMMENT '详细地址',
    `postal_code` VARCHAR(20) DEFAULT NULL COMMENT '邮政编码',
    `address_label` VARCHAR(32) DEFAULT NULL COMMENT '地址标签，如家/公司',
    `is_default` TINYINT NOT NULL DEFAULT 0 COMMENT '是否默认地址：1是，0否',
    `status` TINYINT NOT NULL DEFAULT 1 COMMENT '状态：1启用，0禁用',
    `dept_id` bigint(20) NULL DEFAULT NULL COMMENT '部门ID',
    `create_by` bigint(20) NULL DEFAULT NULL COMMENT '创建者',
    `create_time` datetime(0) NULL DEFAULT NULL COMMENT '创建时间',
    `update_by` bigint(20) NULL DEFAULT NULL COMMENT '更新者',
    `update_time` datetime(0) NULL DEFAULT NULL COMMENT '更新时间',
    `state` tinyint(1) NULL DEFAULT 0 COMMENT '操作状态（0正常 -1删除）',
    PRIMARY KEY (`id`),
    KEY `idx_user_id` (`user_id`),
    KEY `idx_receiver_mobile` (`receiver_mobile`),
    KEY `idx_is_default` (`is_default`),
    KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='商城用户地址表';

CREATE TABLE IF NOT EXISTS `shop_user_cart` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `user_id` BIGINT(20) NOT NULL COMMENT '用户ID，对应shop_user.id',
    `goods_id` VARCHAR(64) NOT NULL COMMENT '商品ID，对应shop_goods.goods_id',
    `sku_id` VARCHAR(64) NOT NULL COMMENT 'SKU ID，对应shop_goods_sku.sku_id',
    `goods_name` VARCHAR(255) NOT NULL COMMENT '商品名称快照',
    `sku_name` VARCHAR(255) DEFAULT NULL COMMENT 'SKU名称快照',
    `image_url` VARCHAR(1024) DEFAULT NULL COMMENT '商品或SKU图片快照',
    `retail_price` DECIMAL(10,2) NOT NULL DEFAULT 0.00 COMMENT '加入购物车时零售价快照',
    `quantity` INT NOT NULL DEFAULT 1 COMMENT '购买数量',
    `selected` TINYINT NOT NULL DEFAULT 1 COMMENT '是否选中：1选中，0未选中',
    `status` TINYINT NOT NULL DEFAULT 1 COMMENT '状态：1有效，0失效',
    `dept_id` bigint(20) NULL DEFAULT NULL COMMENT '部门ID',
    `create_by` bigint(20) NULL DEFAULT NULL COMMENT '创建者',
    `create_time` datetime(0) NULL DEFAULT NULL COMMENT '创建时间',
    `update_by` bigint(20) NULL DEFAULT NULL COMMENT '更新者',
    `update_time` datetime(0) NULL DEFAULT NULL COMMENT '更新时间',
    `state` tinyint(1) NULL DEFAULT 0 COMMENT '操作状态（0正常 -1删除）',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_user_sku` (`user_id`, `sku_id`),
    KEY `idx_user_id` (`user_id`),
    KEY `idx_goods_id` (`goods_id`),
    KEY `idx_sku_id` (`sku_id`),
    KEY `idx_selected` (`selected`),
    KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='商城用户购物车表';



CREATE TABLE IF NOT EXISTS `shop_store_combination` (
    `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '自增ID',
    `product_id` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '商品id',
    `mer_id` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '商户id',
    `image` varchar(255) NOT NULL DEFAULT '' COMMENT '推荐图',
    `images` varchar(2000) NOT NULL DEFAULT '' COMMENT '轮播图',
    `title` varchar(255) NOT NULL DEFAULT '' COMMENT '活动标题',
    `attr` varchar(255) NOT NULL DEFAULT '' COMMENT '活动属性',
    `people` int(2) UNSIGNED NOT NULL DEFAULT '0' COMMENT '参团人数',
    `info` varchar(255) NOT NULL DEFAULT '' COMMENT '简介',
    `price` decimal(12,2) UNSIGNED NOT NULL DEFAULT '0.00' COMMENT '价格',
    `sort` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '排序',
    `sales` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '销量',
    `stock` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '库存',
    `add_time` varchar(128) NOT NULL DEFAULT '0' COMMENT '添加时间',
    `is_host` tinyint(1) UNSIGNED NOT NULL DEFAULT '0' COMMENT '推荐',
    `is_show` tinyint(1) UNSIGNED NOT NULL DEFAULT '1' COMMENT '商品状态',
    `is_del` tinyint(1) UNSIGNED NOT NULL DEFAULT '0' COMMENT '是否删除',
    `combination` tinyint(1) UNSIGNED NOT NULL DEFAULT '1' COMMENT '拼团',
    `mer_use` tinyint(1) UNSIGNED NOT NULL DEFAULT '0' COMMENT '商户是否可用1可用0不可用',
    `is_postage` tinyint(1) UNSIGNED NOT NULL DEFAULT '0' COMMENT '是否包邮1是0否',
    `postage` decimal(12,2) UNSIGNED NOT NULL DEFAULT '0.00' COMMENT '邮费',
    `start_time` int(11) UNSIGNED NOT NULL DEFAULT '0' COMMENT '拼团开始时间',
    `stop_time` int(11) UNSIGNED NOT NULL DEFAULT '0' COMMENT '拼团结束时间',
    `effective_time` int(11) NOT NULL DEFAULT '0' COMMENT '拼团订单有效时间',
    `cost` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '拼图商品成本',
    `browse` int(11) NOT NULL DEFAULT '0' COMMENT '浏览量',
    `unit_name` varchar(32) NOT NULL DEFAULT '' COMMENT '单位名',
    `temp_id` int(11) NOT NULL DEFAULT '0' COMMENT '运费模板ID',
    `weight` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '重量',
    `volume` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '体积',
    `num` int(11) NOT NULL DEFAULT '0' COMMENT '单次购买数量',
    `once_num` int(11) NOT NULL DEFAULT '0' COMMENT '每个订单可购买数量',
    `quota` int(10) NOT NULL DEFAULT '0' COMMENT '限购总数',
    `quota_show` int(10) NOT NULL DEFAULT '0' COMMENT '限量总数显示',
    `virtual` int(11) NOT NULL DEFAULT '100' COMMENT '虚拟成团百分比',
    `logistics` varchar(11) NOT NULL DEFAULT '1,2' COMMENT '物流方式',
    `freight` tinyint(1) NOT NULL DEFAULT '2' COMMENT '运费设置',
    `custom_form` varchar(2000) NOT NULL DEFAULT '' COMMENT '自定义表单',
    `virtual_type` tinyint(1) NOT NULL DEFAULT '0' COMMENT '商品类型',
    `is_commission` tinyint(1) NOT NULL DEFAULT '0' COMMENT '拼团是否返佣',
    `head_commission` int(11) NOT NULL DEFAULT '0' COMMENT '团长佣金比例',
    `dept_id` bigint(20) NULL DEFAULT NULL COMMENT '部门ID',
    `create_by` bigint(20) NULL DEFAULT NULL COMMENT '创建者',
    `create_time` datetime(0) NULL DEFAULT NULL COMMENT '创建时间',
    `update_by` bigint(20) NULL DEFAULT NULL COMMENT '更新者',
    `update_time` datetime(0) NULL DEFAULT NULL COMMENT '更新时间',
    `state` tinyint(1) NULL DEFAULT 0 COMMENT '操作状态（0正常 -1删除）',
    PRIMARY KEY (`id`) USING BTREE
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='拼团商品表';


CREATE TABLE IF NOT EXISTS `shop_store_pink` (
    `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '自增ID',
    `uid` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '用户id',
    `nickname` varchar(64) NOT NULL DEFAULT '' COMMENT '用户昵称',
    `avatar` varchar(256) NOT NULL DEFAULT '' COMMENT '用户头像',
    `order_id` varchar(32) NOT NULL DEFAULT '' COMMENT '订单id 生成',
    `order_id_key` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '订单id  数据库',
    `total_num` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '购买商品个数',
    `total_price` decimal(12,2) UNSIGNED NOT NULL DEFAULT '0.00' COMMENT '购买总金额',
    `cid` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '拼团商品id',
    `pid` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '商品id',
    `people` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '拼图总人数',
    `price` decimal(12,2) UNSIGNED NOT NULL DEFAULT '0.00' COMMENT '拼团商品单价',
    `add_time` varchar(24) NOT NULL DEFAULT '0' COMMENT '开始时间',
    `stop_time` varchar(24) NOT NULL DEFAULT '0' COMMENT '结束时间',
    `k_id` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '团长id 0为团长',
    `is_tpl` tinyint(1) UNSIGNED NOT NULL DEFAULT '0' COMMENT '是否发送模板消息0未发送1已发送',
    `is_refund` tinyint(1) UNSIGNED NOT NULL DEFAULT '0' COMMENT '是否退款 0未退款 1已退款',
    `status` tinyint(1) UNSIGNED NOT NULL DEFAULT '1' COMMENT '状态1进行中2已完成3未完成',
    `is_virtual` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否虚拟拼团',
    `dept_id` bigint(20) NULL DEFAULT NULL COMMENT '部门ID',
    `create_by` bigint(20) NULL DEFAULT NULL COMMENT '创建者',
    `create_time` datetime(0) NULL DEFAULT NULL COMMENT '创建时间',
    `update_by` bigint(20) NULL DEFAULT NULL COMMENT '更新者',
    `update_time` datetime(0) NULL DEFAULT NULL COMMENT '更新时间',
    `state` tinyint(1) NULL DEFAULT 0 COMMENT '操作状态（0正常 -1删除）',
    PRIMARY KEY (`id`) USING BTREE
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='拼团表';
