CREATE TABLE IF NOT EXISTS `shop_category` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `parent_id` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '父分类ID，0表示根分类',
  `ancestor_path` VARCHAR(1024) NOT NULL DEFAULT '/' COMMENT '祖先路径，例如/1/3/8/',
  `depth` INT UNSIGNED NOT NULL DEFAULT 1 COMMENT '层级深度，从1开始',
  `category_name` VARCHAR(128) NOT NULL COMMENT '分类名称',
  `category_code` VARCHAR(64) DEFAULT NULL COMMENT '分类编码',
  `sort` INT NOT NULL DEFAULT 0 COMMENT '排序值，越小越靠前',
  `status` TINYINT NOT NULL DEFAULT 1 COMMENT '状态：1启用，0禁用',
  `is_deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0否，1是',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_category_code` (`category_code`),
  UNIQUE KEY `uk_parent_name` (`parent_id`, `category_name`, `is_deleted`),
  KEY `idx_parent_id` (`parent_id`),
  KEY `idx_ancestor_path` (`ancestor_path`(191)),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='商品分类表';

CREATE TABLE IF NOT EXISTS `shop_goods` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `goods_id` VARCHAR(64) NOT NULL COMMENT '商品ID，对应goodsID',
  `goods_name` VARCHAR(255) NOT NULL COMMENT '商品名称',
  `goods_code` VARCHAR(128) DEFAULT NULL COMMENT '商品编码',
  `outer_id` VARCHAR(128) DEFAULT NULL COMMENT '商品商家编码',
  `image_url` VARCHAR(1024) DEFAULT NULL COMMENT '商品主图URL',
  `retail_price` DECIMAL(10,2) NOT NULL DEFAULT 0.00 COMMENT '零售价',
  `gallery_images` TEXT COMMENT '商品子图列表，JSON数组字符串',
  `video_url` VARCHAR(1024) DEFAULT NULL COMMENT '商品视频URL',
  `description` TEXT COMMENT '商品描述',
  `weight` DECIMAL(10,3) NOT NULL DEFAULT 0.000 COMMENT '商品重量',
  `weight_unit` VARCHAR(16) NOT NULL DEFAULT 'kg' COMMENT '重量单位',
  `unit` VARCHAR(32) NOT NULL DEFAULT '件' COMMENT '计量单位',
  `is_on_sale` TINYINT NOT NULL DEFAULT 0 COMMENT '是否在售：1是，0否',
  `quantity` INT NOT NULL DEFAULT 0 COMMENT '商品总库存',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_goods_id` (`goods_id`),
  KEY `idx_goods_code` (`goods_code`),
  KEY `idx_outer_id` (`outer_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='商品主表';

CREATE TABLE IF NOT EXISTS `shop_goods_sku` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `goods_id` VARCHAR(64) NOT NULL COMMENT '商品ID，对应shop_goods.goods_id',
  `sku_id` VARCHAR(64) NOT NULL COMMENT 'SKU ID，对应skuID',
  `sku_name` VARCHAR(255) DEFAULT NULL COMMENT 'SKU名称',
  `sku_code` VARCHAR(128) DEFAULT NULL COMMENT 'SKU编码',
  `outer_id` VARCHAR(128) DEFAULT NULL COMMENT '规格商家编码',
  `barcode` VARCHAR(128) DEFAULT NULL COMMENT '条码',
  `image_url` VARCHAR(1024) DEFAULT NULL COMMENT 'SKU图片URL',
  `retail_price` DECIMAL(10,2) NOT NULL DEFAULT 0.00 COMMENT '零售价',
  `gallery_images` TEXT COMMENT 'SKU子图列表，JSON数组字符串',
  `video_url` VARCHAR(1024) DEFAULT NULL COMMENT 'SKU视频URL',
  `description` TEXT COMMENT 'SKU描述',
  `weight` DECIMAL(10,3) NOT NULL DEFAULT 0.000 COMMENT 'SKU重量',
  `weight_unit` VARCHAR(16) NOT NULL DEFAULT 'kg' COMMENT '重量单位',
  `unit` VARCHAR(32) NOT NULL DEFAULT '件' COMMENT '计量单位',
  `quantity` INT NOT NULL DEFAULT 0 COMMENT 'SKU库存',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_sku_id` (`sku_id`),
  KEY `idx_goods_id` (`goods_id`),
  KEY `idx_sku_code` (`sku_code`),
  KEY `idx_outer_id` (`outer_id`),
  CONSTRAINT `fk_sku_goods_id` FOREIGN KEY (`goods_id`) REFERENCES `shop_goods` (`goods_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='商品SKU表';

CREATE TABLE IF NOT EXISTS `shop_user` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `user_id` VARCHAR(64) NOT NULL COMMENT '用户业务ID',
  `username` VARCHAR(64) NOT NULL COMMENT '用户名',
  `nickname` VARCHAR(128) DEFAULT NULL COMMENT '用户昵称',
  `mobile` VARCHAR(32) DEFAULT NULL COMMENT '手机号',
  `email` VARCHAR(128) DEFAULT NULL COMMENT '邮箱',
  `password` VARCHAR(255) DEFAULT NULL COMMENT '密码摘要',
  `user_type` TINYINT NOT NULL COMMENT '用户类型：1代理商，2分销商，3工厂',
  `company_name` VARCHAR(255) DEFAULT NULL COMMENT '企业名称',
  `contact_name` VARCHAR(128) DEFAULT NULL COMMENT '联系人',
  `contact_phone` VARCHAR(32) DEFAULT NULL COMMENT '联系人手机号',
  `status` TINYINT NOT NULL DEFAULT 1 COMMENT '状态：1启用，0禁用',
  `is_deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0否，1是',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_user_id` (`user_id`),
  UNIQUE KEY `uk_username` (`username`),
  KEY `idx_mobile` (`mobile`),
  KEY `idx_user_type` (`user_type`),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='商城用户表';
