CREATE TABLE IF NOT EXISTS `shop_order_refund` (
    `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `order_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '订单主表ID',
    `tid` VARCHAR(50) NOT NULL COMMENT '网店订单编号',
    `user_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '申请人ID',
    `pay_channel` TINYINT DEFAULT 0 COMMENT '原支付通道：0未知 1微信 2支付宝',
    `refund_channel` TINYINT DEFAULT 0 COMMENT '实际退款通道：0未知 1微信 2支付宝',
    `out_refund_no` VARCHAR(64) NOT NULL COMMENT '商户退款单号',
    `refund_amount` DECIMAL(10,2) DEFAULT 0.00 COMMENT '退款金额',
    `total_amount` DECIMAL(10,2) DEFAULT 0.00 COMMENT '原订单金额',
    `reason` VARCHAR(500) DEFAULT NULL COMMENT '退款原因',
    `previous_status` VARCHAR(50) DEFAULT NULL COMMENT '售前订单状态',
    `status` TINYINT NOT NULL DEFAULT 0 COMMENT '售后状态：0待审核 1已审核 2退款中 3退款成功 4退款失败 5退款关闭 6已拒绝',
    `audit_remark` VARCHAR(500) DEFAULT NULL COMMENT '审核备注',
    `audit_by` BIGINT(20) DEFAULT NULL COMMENT '审核人',
    `audit_time` DATETIME(0) DEFAULT NULL COMMENT '审核时间',
    `third_transaction_id` VARCHAR(64) DEFAULT NULL COMMENT '三方交易号',
    `third_refund_id` VARCHAR(64) DEFAULT NULL COMMENT '三方退款单号',
    `details_json` LONGTEXT COMMENT '退款明细JSON',
    `erp_platform_id` BIGINT(20) DEFAULT NULL COMMENT 'erp平台ID',
    `erp_sync_status` TINYINT NOT NULL DEFAULT 0 COMMENT 'erp同步状态：0待同步 1成功 2失败',
    `erp_sync_message` VARCHAR(500) DEFAULT NULL COMMENT '同步结果描述',
    `erp_sync_time` DATETIME(0) DEFAULT NULL COMMENT '同步时间',
    `erp_sync_bill_code` VARCHAR(100) DEFAULT NULL COMMENT 'erp返回单号',
    `create_by` BIGINT(20) NULL DEFAULT NULL COMMENT '创建者',
    `create_time` DATETIME(0) NULL DEFAULT NULL COMMENT '创建时间',
    `update_by` BIGINT(20) NULL DEFAULT NULL COMMENT '更新者',
    `update_time` DATETIME(0) NULL DEFAULT NULL COMMENT '更新时间',
    `state` TINYINT(1) NULL DEFAULT 0 COMMENT '操作状态（0正常 -1删除）',
    PRIMARY KEY (`id`),
    UNIQUE INDEX `uk_out_refund_no` (`out_refund_no`) USING BTREE,
    INDEX `idx_shop_order_refund_tid` (`tid`) USING BTREE,
    INDEX `idx_shop_order_refund_status` (`status`) USING BTREE,
    INDEX `idx_shop_order_refund_user_id` (`user_id`) USING BTREE,
    INDEX `idx_shop_order_refund_erp_sync_status` (`erp_sync_status`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='商城售后单主表';
-- 插入自动退款开关配置（默认关闭）
INSERT INTO shop_sys_config (config_key, config_value, config_type, remark, state) 
VALUES ('shop_auto_refund_unshipped_enabled', 'false', 'shop', '未发货订单是否允许自动退款', 0);
