// Code generated by tools/addonsync. DO NOT EDIT.

package business

import (
	"github.com/google/wire"
	admin "nova-factory-server/app/business/admin"
	ai "nova-factory-server/app/business/ai"
	datasyncapi "nova-factory-server/app/business/datasyncapi"
	erp "nova-factory-server/app/business/erp"
	iot "nova-factory-server/app/business/iot"
	shop "nova-factory-server/app/business/shop"
)

type Plugins struct {
	Admin       *admin.Admin
	AI          *ai.AI
	DataSyncApi *datasyncapi.DataSyncApi
	Erp         *erp.Erp
	Iot         *iot.Iot
	Shop        *shop.Shop
}

func NewPlugins(
	adminPlugin *admin.Admin,
	aiPlugin *ai.AI,
	datasyncapiPlugin *datasyncapi.DataSyncApi,
	erpPlugin *erp.Erp,
	iotPlugin *iot.Iot,
	shopPlugin *shop.Shop,
) *Plugins {
	return &Plugins{
		Admin:       adminPlugin,
		AI:          aiPlugin,
		DataSyncApi: datasyncapiPlugin,
		Erp:         erpPlugin,
		Iot:         iotPlugin,
		Shop:        shopPlugin,
	}
}

var ProviderSet = wire.NewSet(
	admin.ProviderSet,
	ai.ProviderSet,
	datasyncapi.ProviderSet,
	erp.ProviderSet,
	iot.ProviderSet,
	shop.ProviderSet,
	NewPlugins,
)
