-- 批次追溯模块SQL文件

-- 创建批次记录表
DROP TABLE IF EXISTS `wm_batch`;
CREATE TABLE IF NOT EXISTS `wm_batch` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '批次ID',
  `batch_code` varchar(64) NOT NULL COMMENT '批次编号',
  `item_id` bigint(20) NOT NULL COMMENT '产品物料ID',
  `item_code` varchar(64) DEFAULT NULL COMMENT '产品物料编码',
  `item_name` varchar(255) DEFAULT NULL COMMENT '产品物料名称',
  `specification` varchar(500) DEFAULT NULL COMMENT '规格型号',
  `unit_of_measure` varchar(64) DEFAULT NULL COMMENT '单位',
  `produce_date` datetime DEFAULT NULL COMMENT '生产日期',
  `expire_date` datetime DEFAULT NULL COMMENT '有效期',
  `recpt_date` datetime DEFAULT NULL COMMENT '入库日期',
  `vendor_id` bigint(20) DEFAULT NULL COMMENT '供应商ID',
  `vendor_code` varchar(64) DEFAULT NULL COMMENT '供应商编码',
  `vendor_name` varchar(255) DEFAULT NULL COMMENT '供应商名称',
  `vendor_nick` varchar(255) DEFAULT NULL COMMENT '供应商简称',
  `client_id` bigint(20) DEFAULT NULL COMMENT '客户ID',
  `client_code` varchar(64) DEFAULT NULL COMMENT '客户编码',
  `client_name` varchar(255) DEFAULT NULL COMMENT '客户名称',
  `client_nick` varchar(255) DEFAULT NULL COMMENT '客户简称',
  `co_code` varchar(64) DEFAULT NULL COMMENT '销售订单编号',
  `po_code` varchar(64) DEFAULT NULL COMMENT '采购订单编号',
  `workorder_id` bigint(20) DEFAULT NULL COMMENT '生产工单ID',
  `workorder_code` varchar(64) DEFAULT NULL COMMENT '生产工单编码',
  `task_id` bigint(20) DEFAULT NULL COMMENT '生产任务ID',
  `task_code` varchar(64) DEFAULT NULL COMMENT '生产任务编号',
  `workstation_id` bigint(20) DEFAULT NULL COMMENT '工作站ID',
  `workstation_code` varchar(64) DEFAULT NULL COMMENT '工作站编码',
  `tool_id` bigint(20) DEFAULT NULL COMMENT '工具ID',
  `tool_code` varchar(64) DEFAULT NULL COMMENT '工具编号',
  `mold_id` bigint(20) DEFAULT NULL COMMENT '模具ID',
  `mold_code` varchar(64) DEFAULT NULL COMMENT '模具编号',
  `lot_number` varchar(128) DEFAULT NULL COMMENT '生产批号',
  `quality_status` varchar(64) DEFAULT NULL COMMENT '质量状态',
  `remark` varchar(500) DEFAULT '' COMMENT '备注',
  `attr1` varchar(64) DEFAULT NULL COMMENT '预留字段1',
  `attr2` varchar(255) DEFAULT NULL COMMENT '预留字段2',
  `attr3` int(11) DEFAULT 0 COMMENT '预留字段3',
  `attr4` int(11) DEFAULT 0 COMMENT '预留字段4',
  `create_by` varchar(64) DEFAULT '' COMMENT '创建者',
  `update_by` varchar(64) DEFAULT '' COMMENT '更新者',
  `create_by_id` bigint(20) NOT NULL COMMENT '创建者ID',
  `update_by_id` bigint(20) NOT NULL COMMENT '更新者ID',
  `created_at` timestamp DEFAULT NULL COMMENT '创建时间',
  `updated_at` timestamp DEFAULT  NULL COMMENT '更新时间',
  `deleted_at` timestamp DEFAULT NULL COMMENT '删除时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='批次记录表';