-- `ktg-mes`.qc_ipqc definition
DROP TABLE IF EXISTS `qc_ipqc`;
CREATE TABLE `qc_ipqc` (
    `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `ipqc_code` varchar(64) NOT NULL COMMENT '检验单编号',
    `ipqc_name` varchar(128) DEFAULT NULL COMMENT '检验单名称',
    `ipqc_type` varchar(32) DEFAULT NULL COMMENT '检验类型',
    `template_id` bigint(20) DEFAULT NULL COMMENT '检验模板ID',
    `source_doc_id` bigint(20) DEFAULT NULL COMMENT '来源单据ID',
    `source_doc_type` varchar(32) DEFAULT NULL COMMENT '来源单据类型',
    `source_doc_code` varchar(64) DEFAULT NULL COMMENT '来源单据编号',
    `source_line_id` bigint(20) DEFAULT NULL COMMENT '来源单据行ID',
    `workorder_id` bigint(20) DEFAULT NULL COMMENT '工单ID',
    `workorder_code` varchar(64) DEFAULT NULL COMMENT '工单编号',
    `workorder_name` varchar(128) DEFAULT NULL COMMENT '工单名称',
    `task_id` bigint(20) DEFAULT NULL COMMENT '任务ID',
    `task_code` varchar(64) DEFAULT NULL COMMENT '任务编号',
    `task_name` varchar(128) DEFAULT NULL COMMENT '任务名称',
    `workstation_id` bigint(20) DEFAULT NULL COMMENT '工位ID',
    `workstation_code` varchar(64) DEFAULT NULL COMMENT '工位编号',
    `workstation_name` varchar(128) DEFAULT NULL COMMENT '工位名称',
    `process_id` bigint(20) DEFAULT NULL COMMENT '工序ID',
    `process_code` varchar(64) DEFAULT NULL COMMENT '工序编号',
    `process_name` varchar(128) DEFAULT NULL COMMENT '工序名称',
    `item_id` bigint(20) DEFAULT NULL COMMENT '物料ID',
    `item_code` varchar(64) DEFAULT NULL COMMENT '物料编码',
    `item_name` varchar(128) DEFAULT NULL COMMENT '物料名称',
    `specification` varchar(128) DEFAULT NULL COMMENT '规格型号',
    `unit_of_measure` varchar(32) DEFAULT NULL COMMENT '单位',
    `unit_name` varchar(32) DEFAULT NULL COMMENT '单位名称',
    `quantity_check` decimal(18,6) DEFAULT NULL COMMENT '检测数量',
    `quantity_unqualified` decimal(18,6) DEFAULT NULL COMMENT '不合格数',
    `quantity_qualified` decimal(18,6) DEFAULT NULL COMMENT '合格品数量',
    `quantity_labor_scrap` decimal(18,6) DEFAULT NULL COMMENT '工废数量',
    `quantity_material_scrap` decimal(18,6) DEFAULT NULL COMMENT '料废数量',
    `quantity_other_scrap` decimal(18,6) DEFAULT NULL COMMENT '其他废品数量',
    `cr_rate` decimal(10,4) DEFAULT NULL COMMENT '严重不合格率',
    `maj_rate` decimal(10,4) DEFAULT NULL COMMENT '主要不合格率',
    `min_rate` decimal(10,4) DEFAULT NULL COMMENT '次要不合格率',
    `cr_quantity` decimal(18,6) DEFAULT NULL COMMENT '严重不合格数',
    `maj_quantity` decimal(18,6) DEFAULT NULL COMMENT '主要不合格数',
    `min_quantity` decimal(18,6) DEFAULT NULL COMMENT '次要不合格数',
    `check_result` varchar(32) DEFAULT NULL COMMENT '检测结果',
    `inspect_date` datetime DEFAULT NULL COMMENT '检测日期',
    `inspector` varchar(64) DEFAULT NULL COMMENT '检验员',
    `status` varchar(16) DEFAULT NULL COMMENT '单据状态',
    `remark` varchar(255) DEFAULT NULL COMMENT '备注',
    `attr1` varchar(128) DEFAULT NULL COMMENT '预留字段1',
    `attr2` varchar(128) DEFAULT NULL COMMENT '预留字段2',
    `attr3` int DEFAULT NULL COMMENT '预留字段3',
    `attr4` int DEFAULT NULL COMMENT '预留字段4',
    `create_by` varchar(64) DEFAULT NULL COMMENT '创建者',
    `update_by` varchar(64) DEFAULT NULL COMMENT '更新者',
    `create_by_id` bigint(20) DEFAULT NULL COMMENT '创建者ID',
    `update_by_id` bigint(20) DEFAULT NULL COMMENT '更新者ID',
    `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at` datetime DEFAULT NULL COMMENT '更新时间',
    `deleted_at` datetime DEFAULT NULL COMMENT '删除时间',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='过程检验单表';