-- 来料检验单表
DROP TABLE IF EXISTS `qc_iqc`;
CREATE TABLE `qc_iqc` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '来料检验单ID',
  `iqc_code` varchar(64) NOT NULL COMMENT '来料检验单编号',
  `iqc_name` varchar(500) NOT NULL COMMENT '来料检验单名称',
  `template_id` bigint(20) NOT NULL COMMENT '检验模板ID',
  `source_doc_id` bigint(20) DEFAULT NULL COMMENT '来源单据ID',
  `source_doc_type` varchar(64) DEFAULT NULL COMMENT '来源单据类型',
  `source_doc_code` varchar(64) DEFAULT NULL COMMENT '来源单据编号',
  `source_line_id` bigint(20) DEFAULT NULL COMMENT '来源单据行ID',
  `vendor_id` bigint(20) NOT NULL COMMENT '供应商ID',
  `vendor_code` varchar(64) NOT NULL COMMENT '供应商编码',
  `vendor_name` varchar(255) NOT NULL COMMENT '供应商名称',
  `vendor_nick` varchar(255) DEFAULT NULL COMMENT '供应商简称',
  `vendor_batch` varchar(64) DEFAULT NULL COMMENT '供应商批次号',
  `item_id` bigint(20) NOT NULL COMMENT '产品物料ID',
  `item_code` varchar(64) DEFAULT NULL COMMENT '产品物料编码',
  `item_name` varchar(255) DEFAULT NULL COMMENT '产品物料名称',
  `specification` varchar(500) DEFAULT NULL COMMENT '规格型号',
  `unit_of_measure` varchar(64) DEFAULT NULL COMMENT '单位',
  `unit_name` varchar(64) DEFAULT NULL COMMENT '单位名称',
  `quantity_min_check` int(11) DEFAULT 1 COMMENT '最低检测数',
  `quantity_max_unqualified` int(11) DEFAULT 0 COMMENT '最大不合格数',
  `quantity_recived` double(12,2) NOT NULL COMMENT '本次接收数量',
  `quantity_check` int(11) DEFAULT NULL COMMENT '本次检测数量',
  `quantity_qualified` int(11) DEFAULT 0 COMMENT '合格数',
  `quantity_unqualified` int(11) DEFAULT 0 COMMENT '不合格数',
  `cr_rate` double(12,2) DEFAULT 0.00 COMMENT '致命缺陷率',
  `maj_rate` double(12,2) DEFAULT 0.00 COMMENT '严重缺陷率',
  `min_rate` double(12,2) DEFAULT 0.00 COMMENT '轻微缺陷率',
  `cr_quantity` int(11) DEFAULT 0 COMMENT '致命缺陷数量',
  `maj_quantity` int(11) DEFAULT 0 COMMENT '严重缺陷数量',
  `min_quantity` int(11) DEFAULT 0 COMMENT '轻微缺陷数量',
  `check_result` varchar(64) DEFAULT NULL COMMENT '检测结果',
  `recive_date` datetime DEFAULT NULL COMMENT '来料日期',
  `inspect_date` datetime DEFAULT NULL COMMENT '检测日期',
  `inspector` varchar(64) DEFAULT NULL COMMENT '检测人员',
  `status` varchar(64) DEFAULT NULL COMMENT '单据状态',
  `remark` varchar(500) DEFAULT '' COMMENT '备注',
  `attr1` varchar(64) DEFAULT NULL COMMENT '预留字段1',
  `attr2` varchar(255) DEFAULT NULL COMMENT '预留字段2',
  `attr3` int(11) DEFAULT 0 COMMENT '预留字段3',
  `attr4` int(11) DEFAULT 0 COMMENT '预留字段4',
  `create_by` varchar(64) DEFAULT '' COMMENT '创建者',
  `update_by` varchar(64) DEFAULT '' COMMENT '更新者',
  `create_by_id` bigint(20) NOT NULL COMMENT '创建者ID',
  `update_by_id` bigint(20) NOT NULL COMMENT '更新者ID',
  `created_at` timestamp DEFAULT NULL COMMENT '创建时间',
  `updated_at` timestamp DEFAULT  NULL COMMENT '更新时间',
  `deleted_at` timestamp DEFAULT NULL COMMENT '删除时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='来料检验单表';