-- 退料检验单表
DROP TABLE IF EXISTS `qc_rqc`;
CREATE TABLE `qc_rqc` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '检验单ID',
  `rqc_code` varchar(64) NOT NULL COMMENT '检验单编号',
  `rqc_name` varchar(500) DEFAULT NULL COMMENT '检验单名称',
  `template_id` bigint(20) NOT NULL COMMENT '检验模板ID',
  `source_doc_id` bigint(20) DEFAULT NULL COMMENT '来源单据ID',
  `source_doc_type` varchar(64) DEFAULT NULL COMMENT '来源单据类型',
  `source_doc_code` varchar(64) DEFAULT NULL COMMENT '来源单据编号',
  `source_line_id` bigint(20) DEFAULT NULL COMMENT '来源单据行ID',
  `item_id` bigint(20) NOT NULL COMMENT '产品物料ID',
  `item_code` varchar(64) DEFAULT NULL COMMENT '产品物料编码',
  `item_name` varchar(255) DEFAULT NULL COMMENT '产品物料名称',
  `specification` varchar(500) DEFAULT NULL COMMENT '规格型号',
  `unit_of_measure` varchar(64) DEFAULT NULL COMMENT '单位',
  `unit_name` varchar(128) DEFAULT NULL COMMENT '单位名称',
  `batch_id` bigint(20) DEFAULT NULL COMMENT '批次ID',
  `batch_code` varchar(128) DEFAULT NULL COMMENT '批次号',
  `quantity_check` double(12,4) DEFAULT 1.0000 COMMENT '检测数量',
  `quantity_unqualified` double(12,4) DEFAULT 0.0000 COMMENT '不合格数',
  `quantity_qualified` double(12,4) DEFAULT NULL COMMENT '合格品数量',
  `check_result` varchar(64) DEFAULT NULL COMMENT '检测结果',
  `inspect_date` datetime DEFAULT NULL COMMENT '检测日期',
  `user_id` bigint(20) DEFAULT NULL COMMENT '检测人员ID',
  `user_name` varchar(64) DEFAULT NULL COMMENT '检测人员名称',
  `nick_name` varchar(64) DEFAULT NULL COMMENT '检测人员',
  `status` varchar(64) DEFAULT NULL COMMENT '单据状态',
  `remark` varchar(500) DEFAULT '' COMMENT '备注',
  `attr1` varchar(64) DEFAULT NULL COMMENT '预留字段1',
  `attr2` varchar(255) DEFAULT NULL COMMENT '预留字段2',
  `attr3` int(11) DEFAULT 0 COMMENT '预留字段3',
  `attr4` int(11) DEFAULT 0 COMMENT '预留字段4',
  `create_by` varchar(64) DEFAULT '' COMMENT '创建者',
  `update_by` varchar(64) DEFAULT '' COMMENT '更新者',
  `create_by_id` bigint(20) NOT NULL COMMENT '创建者ID',
  `update_by_id` bigint(20) NOT NULL COMMENT '更新者ID',
  `created_at` timestamp DEFAULT NULL COMMENT '创建时间',
  `updated_at` timestamp DEFAULT  NULL COMMENT '更新时间',
  `deleted_at` timestamp DEFAULT NULL COMMENT '删除时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='退料检验单表';
