
Create TABLE `sys_dataset` (
    `dataset_id` bigint NOT NULL COMMENT '出库id',
    `dataset_avatar` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '' COMMENT 'base64 编码的头像。',
    `dataset_chunk_method` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '' COMMENT '要创建的数据集的分块方法',
    `dataset_create_date` datetime DEFAULT NULL COMMENT '创建时间',
    `dataset_create_time` bigint NOT NULL COMMENT '创建时间',
    `dataset_created_by` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '' COMMENT '创建人',
    `dataset_description` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci COMMENT '描述',
    `dataset_document_count` bigint NOT NULL DEFAULT '0' COMMENT '文档数',
    `dataset_embedding_model` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '' COMMENT '嵌入模型',
    `dataset_uuid` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '' COMMENT '知识库id',
    `dataset_language` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '' COMMENT '知识库语言',
    `dataset_name` varchar(136) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '' COMMENT '要创建的数据集的唯一名称',
    `dataset_pagerank` int DEFAULT '0' COMMENT '页面排名',
    `dataset_parser_config` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci COMMENT '数据集解析器的配置设置。',
    `dataset_permission` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '' COMMENT '指定谁可以访问要创建的数据集。',
    `dataset_similarity_threshold` decimal(10,2) DEFAULT '0.00' COMMENT '最小相似度分数',
    `dataset_token_num` bigint NOT NULL DEFAULT '0' COMMENT 'token num',
    `dataset_chunk_count` bigint NOT NULL DEFAULT '0' COMMENT 'chunk num',
    `dataset_update_date` datetime DEFAULT NULL COMMENT '更新时间',
    `dataset_update_time` bigint NOT NULL COMMENT '更新时间',
    `dataset_vector_similarity_weight` decimal(10,2) DEFAULT '0.00' COMMENT '矢量余弦相似性的权重。',
    `dept_id` bigint DEFAULT NULL COMMENT '部门ID',
    `create_by` bigint DEFAULT NULL COMMENT '创建者',
    `create_time` datetime DEFAULT NULL COMMENT '创建时间',
    `update_by` bigint DEFAULT NULL COMMENT '更新者',
    `update_time` datetime DEFAULT NULL COMMENT '更新时间',
    `state` tinyint(1) DEFAULT '0' COMMENT '操作状态（0正常 -1删除）',
    PRIMARY KEY (`dataset_id`) USING BTREE,
    UNIQUE KEY `dataset_name` (`dataset_name`,`state`) USING BTREE
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='物料出库管理';

CREATE TABLE `sys_dataset_document`  (
     `document_id` bigint(20) NOT NULL COMMENT '文档id',
     `dataset_id` bigint(20) NOT NULL COMMENT '数据集id',
     `dataset_chunk_method` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT '' COMMENT '要创建的数据集的分块方法',
     `dataset_created_by` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT '' COMMENT '创建人',
     `dataset_document_uuid` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT '' COMMENT '文档id',
     `dataset_dataset_uuid` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT '' COMMENT '知识库id',
     `dataset_language` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT '' COMMENT '知识库语言',
     `dataset_location` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT '' COMMENT '知识库定位',
     `dataset_name` varchar(136) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT '' COMMENT '要创建的数据集的唯一名称',
     `dataset_parser_config` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL  COMMENT '数据集解析器的配置设置。',
     `dataset_run` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT '' COMMENT '知识库运行状态',
     `dataset_size` bigint(20) NOT NULL DEFAULT 0 COMMENT '知识库尺寸大小',
     `dataset_thumbnail` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT '' COMMENT '知识库锁略图',
     `dataset_type` varchar(136) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT '' COMMENT '知识库类型',
     `dataset_chunk_count` bigint NOT NULL DEFAULT '0' COMMENT 'chunk num',
     `dept_id` bigint(20) NULL DEFAULT NULL COMMENT '部门ID',
     `create_by` bigint(20) NULL DEFAULT NULL COMMENT '创建者',
     `create_time` datetime(0) NULL DEFAULT NULL COMMENT '创建时间',
     `update_by` bigint(20) NULL DEFAULT NULL COMMENT '更新者',
     `update_time` datetime(0) NULL DEFAULT NULL COMMENT '更新时间',
     `state` tinyint(1) NULL DEFAULT 0 COMMENT '操作状态（0正常 -1删除）',
     PRIMARY KEY (`document_id`) USING BTREE
) ENGINE = InnoDB  CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci COMMENT = '文档管理' ROW_FORMAT = Dynamic;

CREATE TABLE `sys_ai_prediction_list`  (
     `id` bigint(20) NOT NULL COMMENT 'id',
     `reason_id` bigint(20) NOT NULL COMMENT '模型推理id',
     `action_id` bigint(20) NOT NULL COMMENT '处理通知id',
     `threshold` bigint(5) NOT NULL COMMENT 'threshold',
     `name` varchar(255) not null comment '智能预警名称',
     `dev` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci COMMENT '测点名称',
     `advanced` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci COMMENT '告警规则',
     `model` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT '' COMMENT '预测模型',
     `field` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT '' COMMENT '预测字段',
     `interval` bigint(20) NOT NULL COMMENT '预测时间段',
     `predict_length` bigint(20) unsigned NULL DEFAULT 0 COMMENT '预测长度',
     `agg_function` varchar(125) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT '' COMMENT '聚合函数，用来计算图表',
     `perturbation_variables` varchar(2048) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT '' COMMENT '关联变量',
     `dept_id` bigint(20) NULL DEFAULT NULL COMMENT '部门ID',
     `create_by` bigint(20) NULL DEFAULT NULL COMMENT '创建者',
     `create_time` datetime(0) NULL DEFAULT NULL COMMENT '创建时间',
     `update_by` bigint(20) NULL DEFAULT NULL COMMENT '更新者',
     `update_time` datetime(0) NULL DEFAULT NULL COMMENT '更新时间',
     `state` tinyint(1) NULL DEFAULT 0 COMMENT '操作状态（0正常 -1删除）',
     PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB  CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci COMMENT = '预测列表' ROW_FORMAT = Dynamic;

CREATE TABLE `sys_ai_prediction_exception`  (
    `id` bigint(20) NOT NULL COMMENT 'id',
    `reason_id` bigint(20) NOT NULL COMMENT '模型推理id',
    `action_id` bigint(20) NOT NULL COMMENT '处理通知id',
    `threshold` bigint(5) NOT NULL COMMENT 'threshold',
    `name` varchar(255) not null comment '智能预警名称',
    `dev` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci COMMENT '测点名称',
    `model` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT '' COMMENT '预测模型',
    `interval` bigint(20) NOT NULL COMMENT '预测时间段',
    `predict_length` bigint(20) unsigned NULL DEFAULT 0 COMMENT '预测长度',
    `agg_function` varchar(125) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT '' COMMENT '聚合函数，用来计算图表',
    `dept_id` bigint(20) NULL DEFAULT NULL COMMENT '部门ID',
    `create_by` bigint(20) NULL DEFAULT NULL COMMENT '创建者',
    `create_time` datetime(0) NULL DEFAULT NULL COMMENT '创建时间',
    `update_by` bigint(20) NULL DEFAULT NULL COMMENT '更新者',
    `update_time` datetime(0) NULL DEFAULT NULL COMMENT '更新时间',
    `state` tinyint(1) NULL DEFAULT 0 COMMENT '操作状态（0正常 -1删除）',
    PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB  CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci COMMENT = '异常预警' ROW_FORMAT = Dynamic;

CREATE TABLE `sys_ai_prediction_control`  (
    `id` bigint(20) NOT NULL COMMENT 'id',
    `device_gateway_id` bigint(20) NOT NULL  COMMENT '网关id',
    `name` varchar(255) not null comment '智能预警名称',
    `parallelism` bigint(5) NOT NULL COMMENT '并发',
    `threshold` bigint(5) NOT NULL COMMENT 'threshold',
    `model` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT '' COMMENT '预测模型',
    `interval` bigint(20) NOT NULL COMMENT '预测时间段',
    `predict_length` bigint(20) unsigned NULL DEFAULT 0 COMMENT '预测长度',
    `agg_function` varchar(125) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT '' COMMENT '聚合函数，用来计算图表',
    `dept_id` bigint(20) NULL DEFAULT NULL COMMENT '部门ID',
    `create_by` bigint(20) NULL DEFAULT NULL COMMENT '创建者',
    `create_time` datetime(0) NULL DEFAULT NULL COMMENT '创建时间',
    `update_by` bigint(20) NULL DEFAULT NULL COMMENT '更新者',
    `update_time` datetime(0) NULL DEFAULT NULL COMMENT '更新时间',
    `state` tinyint(1) NULL DEFAULT 0 COMMENT '操作状态（0正常 -1删除）',
    PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB  CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci COMMENT = '趋势控制' ROW_FORMAT = Dynamic;